### ISSUE TITLE
Response template format should be saved (Space, tab etc)

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#101]
![2017-02-25 12 11 58](https://cloud.githubusercontent.com/assets/1748857/23328046/e0fa7266-fb53-11e6-9d23-5305a8b28d78.gif)

**Comment by boldkhuu** [comment]
@mendorshikh Why did you remove this issue from Project? Should it be done?

**Comment by mendorshikh** [comment]
@boldkhuu i didn't remove. Please make changes.

**Comment by mendorshikh** [comment]
@boldkhuu oh lol. I did removed but i don't remember why.

**Comment by boldkhuu** [comment]
@batamar Maybe it's postponed because of Draft.js possibility?

This issue is mistakenly included in the patch-0.1.1.

**Comment by mendorshikh** [comment]
@boldkhuu yes. It is postponed because of Draft.js.
