### ISSUE TITLE
Widget API Error.

### ISSUE THREAD

**Issue by nishantbhat** [erxes/erxes#1030]
I install the erxes with the help of docker and started the service login working when I added the widget it's not working .Please help to resolve the problem.
![Screenshot from 2019-07-12 08-48-23-01](https://user-images.githubusercontent.com/30562513/61100136-a0ae6c00-a482-11e9-8c17-5f8bf13a3351.jpeg)

**Comment by shinebayar-g** [comment]
Hi @nishantbhat , looks like you've incomplete env settings. I'll revise docker installation docs and will let you know. thanks.

**Comment by nishantbhat** [comment]
Can you tell me how to add the env setting.am not able to use widget of the application so am stopped using platform at present.

**Comment by shinebayar-g** [comment]
Hi @nishantbhat I've just finished updating docker installation docs.
Please check this out https://docs.erxes.io/docs/installation/docker
