### ISSUE TITLE
There's something wrong with erxes-api:0.9.17 on Docker

### ISSUE THREAD

**Issue by lovetatfitties** [erxes/erxes#1032]
Hi, I followed this steps ([docs.erxes.io/docs/installation/docker](https://docs.erxes.io/docs/installation/docker)) and everything went fine until I went to localhost:3000, "Network error: Failed to fetch"

This are the errors on the console:
![Screenshot from 2019-07-13 20-49-38](https://user-images.githubusercontent.com/3211879/61179710-70b7b380-a5bd-11e9-8a53-b9b9f05b012c.png)

Then I run 'docker ps' and notice one container is missing (erxes-api):
![Screenshot from 2019-07-13 22-18-14](https://user-images.githubusercontent.com/3211879/61179743-eae83800-a5bd-11e9-91df-b5429636f427.png)

I run 'docker-compose start' and erxes-api is up again, but as soon as I go to localhost:3000 it dies again.

This is what 'docker logs erxes-api' looks like:
```
tgs@x2040:~/erxes$ sudo docker logs erxes-api
net.js:1396
      throw new ERR_SOCKET_BAD_PORT(options.port);
      ^

RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received .
    at Server.listen (net.js:1396:13)
    at Object.<anonymous> (/erxes-api/dist/index.js:265:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

I thought my machine was the problem so I tried to install it on a server, same results.

Looking around, mostly on #801, I noticed that @shinebayar-g is using "erxes-api:develop-latest" so I changed that in the docker-compose file and voila! The erxes-api containter stays up and localhost:3000 works as expected.

**Comment by shinebayar-g** [comment]
hi @lovetatfitties . Imho documentation needs to updated with latest 0.9.17 version. I'll revise docs asap when I get to work. If you run other containers on `0.9.17` and api on `develop-latest` tag there will be version mismatch between containers. So it's best to use `develop-latest` tag on all containers (some containers weren't introduce when we using `develop-latest` tag tho) or you could set `PORT=3300` env for erxes-api in your docker-compose file.

**Comment by lovetatfitties** [comment]
Ok, noted. I just wanted to bring attention to this issue so you can close it now or let me know if you need help testing something on my end related to `0.9.17`.

**Comment by shinebayar-g** [comment]
Ok will let you know once I revise docs :)

**Comment by shinebayar-g** [comment]
Hi @lovetatfitties  I've just finished updating docker installation docs.
Please check this out https://docs.erxes.io/docs/installation/docker

**Comment by lovetatfitties** [comment]
Everything works perfectly now, good work thank you! :D 

![Screenshot from 2019-07-16 14-44-46](https://user-images.githubusercontent.com/3211879/61334185-3b3de080-a7de-11e9-86cc-7ae7baca18e1.png)

I don't wanna be a bother but I think I found another hiccup totally unrelated to this. After the install when you select the Deal tab it shows: 

![Screenshot from 2019-07-16 15-44-52](https://user-images.githubusercontent.com/3211879/61334998-bb654580-a7e0-11e9-8871-001934edd5e5.png)

But there's no way to add a new board, you have to go to Settings > Deal Settings > Boards and Pipelines and there you can add a new one. I wanted to take a screenshot but when I tried to delete the board I just made it said "Can't remove board" (the same is correct for Pipelines), but if I make another board I'm able to delete it just fine so only the first one is 'locked'.

Should I open a new ticket?

**Comment by shinebayar-g** [comment]
@lovetatfitties Glad it's working for you. I believe we can close this one start new issue for this deal pipeline problem.

**Comment by lovetatfitties** [comment]
Gotcha, just let me wipe everything and make a new install just to rule out some sort of error form the last deployment. If I don't open an issue by tomorrow it means that fixed it. Thank you!

**Comment by shinebayar-g** [comment]
@lovetatfitties gotcha, I guess what you encountered was really a bug..
