### ISSUE TITLE
[enhancement] Responsive web design (RWD) for the dashboard.

### ISSUE THREAD

**Issue by veerjainATgmail** [erxes/erxes#1046]
**Is your feature request related to a problem? Please describe.**
The erxes dashboard do not render well on the mobile devices or tablets.

**Describe the solution you'd like**
Responsive web design (RWD), rendering of components/containers adoptive to the screen size.

**Describe alternatives you've considered**
None. This will enhance the user experience. Downloading the App is an alternative.

**Additional context**
Mobile first workflow would prefer accessing conversations and tasks in their tablets or mobile devices through web.

**Comment by Mambatukaa** [comment]
Hey there, 
Thank you for your suggestion. We've moved our enhancement/feature requests into roadmap.erxes.io.
Please use this link in the future to submit your features. I've already copied and submitted this insight there.

Thank you.
