### ISSUE TITLE
Real time related issues

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1055]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [e.g docker, manual]

**Additional context**

**Comment by batamar** [comment]
Too vague
