### ISSUE TITLE
Number of segments incorrect

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1096]
**To Reproduce**
1. Go to 'nmg.app.erxes.io>Customer detail'
2. See the sidebar > Segment section> Gerege.agency > 2829
3. Click on Manage segments > Gerege.agency> 0
4. Error: Number is not equal

![1](https://user-images.githubusercontent.com/16484133/61938400-908aa680-afc3-11e9-9a80-59f0c35b1664.png)
![s](https://user-images.githubusercontent.com/16484133/61938474-cb8cda00-afc3-11e9-9dc7-ca6ea3e27655.png)

**Comment by batamar** [comment]
Saas issue
