### ISSUE TITLE
Add task type 

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1098]
<img width="447" alt="1" src="https://user-images.githubusercontent.com/16484133/61939123-270b9780-afc5-11e9-94c1-6be36a155099.png">
![2](https://user-images.githubusercontent.com/16484133/61939125-270b9780-afc5-11e9-9c44-0e0173bdd151.png)
![3](https://user-images.githubusercontent.com/16484133/61939129-27a42e00-afc5-11e9-9619-2a229e76dc30.png)

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.
