### ISSUE TITLE
Improve engage rule UI

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1111]
<img width="517" alt="ss1" src="https://user-images.githubusercontent.com/16484133/62021593-9f0ed300-b1fa-11e9-9a55-2f4c34d10f39.png">

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.
