### ISSUE TITLE
realtime notification

### ISSUE THREAD

**Issue by batamar** [erxes/erxes#1121]

**Comment by sergeychikanov** [comment]
@batamar - Any plans to make this sub per-user? I experimented with the same change to make sure users always get notified when a conversation is assigned to them. It worked well but I didn't have time for a PR. You can find it here: https://github.com/sergeychikanov/erxes/commit/bb9a3c840b77a27220b236ae5de24ddb47d64156

**Comment by batamar** [comment]
@sergeychikanov Hi. What do you mean by per-user ?

**Comment by batamar** [comment]
@sergeychikanov Okey. I see. Good idea. We will include this fix in 0.11.0

**Comment by sergeychikanov** [comment]
@batamar - Thank you! Let me know if you need any input on the Team Inbox as this is a killer feature of yours =) .

**Comment by batamar** [comment]
@sergeychikanov Sure. Thank you

**Comment by batamar** [comment]
@sergeychikanov
