### ISSUE TITLE
The "last online"  in customer detail  and "Last seen at" in customer list that field values  are incorrect

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1169]
![ss1](https://user-images.githubusercontent.com/16484133/62757400-ccd30200-baad-11e9-9e11-e7c541f6e4cb.png)
![ss2](https://user-images.githubusercontent.com/16484133/62757401-ccd30200-baad-11e9-9f7e-97e5ed6a0d96.png)

**Comment by batamar** [comment]
Working properly. Checked
