### ISSUE TITLE
it's coming to be a notification on its own chat

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1198]
![ss1](https://user-images.githubusercontent.com/16484133/63249262-b42bce80-c29b-11e9-9ff3-bf50bd6a38a8.png)
![ss2](https://user-images.githubusercontent.com/16484133/63249264-b42bce80-c29b-11e9-806b-33d4244f9929.png)

**Comment by batamar** [comment]
Resolved in 0.10.1
