### ISSUE TITLE
The contact menu filter is broken

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1226]
<img width="1265" alt="123" src="https://user-images.githubusercontent.com/16484133/63834865-d531a500-c9a8-11e9-896a-c5809a9ebf95.png">

**Comment by schmelto** [comment]
what is to do at this issue?

**Comment by indraganzorig** [comment]
- [ ] Ensure multiple filter chips at the top navbar do not overlap with the icons at the top right.
- [ ] 'Filter by Integration' selection does not appear at the top as a chip
