### ISSUE TITLE
Make realtime deal/task/ticket board and pipeline 

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1240]
**Is your enhancement request related to a problem? Please describe.**
any item move another stage but hasn't listen other user's pipeline

**Describe the solution you'd like**
other user's pipeline like main users's pipeline

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.
