### ISSUE TITLE
The search didn't work  when  assign customer in the deal / task / ticket.

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1251]
Didn't work in the following conditions:
1. Write large and lowercase letters
2. Write a space 
3. Write search keywords incomplete
![ss1](https://user-images.githubusercontent.com/16484133/64472282-92cd4c80-d18e-11e9-9a09-eb27c908ffd9.png)

**Comment by batamar** [comment]
resolved in 0.11.0
