### ISSUE TITLE
Make it possible to switch attachment photos in preview section

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1256]
![captured (1)](https://user-images.githubusercontent.com/16484133/64586198-293b8100-d3ce-11e9-9975-d42fff3e4bc0.gif)

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.
