### ISSUE TITLE
Improve UI -  Quick message in customer detail

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1258]
![ss1](https://user-images.githubusercontent.com/16484133/64610019-dd55ff80-d400-11e9-81a6-5eea8e794d5f.png)
![ss2](https://user-images.githubusercontent.com/16484133/64612264-f44b2080-d405-11e9-8b97-3a6183101177.png)

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.
