### ISSUE TITLE
Pop up is closed when selecting title in the all pop up windows.

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1285]
![captured (28)](https://user-images.githubusercontent.com/16484133/65597120-f5b24680-dfca-11e9-8201-24e083c507ce.gif)

In the following sections: 
1. Deal pop up
2. Task pop up
3. Ticket pop up
4. Growth Hack pop up
5. Customer edit form
6. Company edit form
7. Knowledgebase edit form
8. Permission>User group edit form
9. Team members list> Edit form
10.Property edit form etc

**Comment by batamar** [comment]
resolved in 0.11.1
