### ISSUE TITLE
Get fields in script code

### ISSUE THREAD

**Issue by yagobski** [erxes/erxes#1330]
Hi How to get the firstName, lastName, Department injected to Erxes directly from the script like intercom. It is not working like this.

window.erxesSettings = {
      messenger: {
        email: props.email,
        firstName: props.firstname,
        lastName: props.lastname,
        department: props.department,
        brand_id: props.brandId,
        created_at: props.memberSince,
      },
    };

**Comment by shinebayar-g** [comment]
You have to generate your customized script code from erxes - settings - app store - integrations - messengers section.

**Comment by yagobski** [comment]
Yes is already generated but I want to map fields like first name, last
name, department and custom fields. Like that I can send this information
from my app using the script exactly the same way like intercom.

The only fields working email and phone.
