### ISSUE TITLE
Different login error messages can reveal if email address has account

### ISSUE THREAD

**Issue by zjuul** [erxes/erxes#1354]
**Login error messages can reveal if email address has account**
When logging in from an unknown email address, an error message is shown that is different than wen logging in with a wrong password. In this way, one can check if a username is valid.

**To Reproduce**
1. Try to log in with a random email address - `User not found`
2. Try to log in with an existing account (wrong pw) - `The email address or password you entered was incorrect`

**Expected behavior**
Same error message on all login errors.

**Comment by Buyantogtokh** [comment]
User sign in process takes the following steps:
Frontend:
1. https://github.com/erxes/erxes/blob/master/src/modules/auth/containers/SignIn.tsx (User sees this form & submits)
2. https://github.com/erxes/erxes/blob/master/src/modules/auth/components/SignIn.tsx (renders the following generic mutation button)
3. https://github.com/erxes/erxes/blob/master/src/modules/common/components/ButtonMutate.tsx (Calls graphql login mutation & shows error message)

Backend:
1. https://github.com/erxes/erxes-api/blob/master/src/data/resolvers/mutations/users.ts (calls User model method)
2. https://github.com/erxes/erxes-api/blob/master/src/db/models/Users.ts (authentication takes place here)

@zjuul as mentioned above, we don't reveal any user email. If you feel different, please provide some proof.

**Comment by zjuul** [comment]
@Buyantogtokh Thanks for the reply.

You don't reveal the user emails, you only reveal _the existence_ of the entered email address in the database.

If you don't mind that, you can change
`The email address or password you entered was incorrect` -> to -> `The password you entered was incorrect.`
