### ISSUE TITLE
erxes as helpdesk app? imap/email support?

### ISSUE THREAD

**Issue by niksfirefly** [erxes/erxes#1432]
Can we use erxes as helpdesk app? 
I found NO imap/email support in docker installation

**Comment by Jason-2020** [comment]
Hi @niksfirefly. erxes can be perfect fit for helpdesk app. Through our omni channel feature, you can connect all of your customer engagement platforms in a single team inbox.

We've got IMAP support by https://www.nylas.com/. Here's an example.

![image](https://user-images.githubusercontent.com/58852063/71735305-0bb48a80-2e89-11ea-8c82-8379d419b979.png)

Also you can connect your gmail account directly without 3rd party integration.
