### ISSUE TITLE
User/pass for demo?

### ISSUE THREAD

**Issue by seanpowell** [erxes/erxes#15]
The link on the homepage takes you to a demo that requires basic authentication but no user/password is supplied.  The username and password on the github repo readme also doesn't work for it.

**Comment by mendorshikh** [comment]
@seanpowell Hello there, sorry for the inconvenience. We have just changed the call-to-action button to "Demo is coming soon". We will let u know once the demo is ready.

**Comment by mendorshikh** [comment]
@seanpowell Hello again, we have just launched our demo. Please check it out. Have a great day!

**Comment by w3update** [comment]
this link (http://demoapp.erxes.io/login) is not working which is linked to homepage demo rather this working https://demo.erxes.io/sign-in may I know demo credentials?

**Comment by w3update** [comment]
the readme default credentials are not working
email: 'admin@erxes.io'
password: 'admin123'

**Comment by mendorshikh** [comment]
@w3update Hello there, we have updated our demo. Please check it out. Have a great day!
