### ISSUE TITLE
Attempted import error: 'compose' is not exported from 'react-apollo'

### ISSUE THREAD

**Issue by ankitkhadria1** [erxes/erxes#1522]
**Describe the bug**

After upgrading react-apollo to 3.0.0 the following error message is presented:

Attempted import error: 'compose' is not exported from 'react-apollo'

**Fix**
import * as compose from 'lodash.flowright';

**Context (please include the related information if applicable):**
 - OS: Mac OS
 - Browser version chrome 75.0.3770.142
 - erxes version 0.11.2
 - installation type manual

**Comment by batamar** [comment]
@ankitkhadria1 Fixed
