### ISSUE TITLE
Form name of growth hack template stage is not being saved 

### ISSUE THREAD

**Issue by Buyantogtokh** [erxes/erxes#1537]
**Describe the bug**
Form name of growth hack template stage is not being saved 

**To Reproduce**
1. Go to '/settings/boards/growthHackTemplate
2. Pick any existing GH template or create a new one
3. In 'Stages' section, click 'Build a form' icon & save a form. 
4. See the connected form from the database, from 'forms' collection

**Comment by batamar** [comment]
Maybe fixed
