### ISSUE TITLE
Cannot save a customer after an error occurs

### ISSUE THREAD

**Issue by munkhjin0223** [erxes/erxes#1547]
**Describe the bug**
Cannot save a customer after an error occurs. Because save buttons are disabled after that.

**To Reproduce**
1. Go to 'customer list'
2. Click on 'add new customer'
3. Enter a 'duplicated email' (in order to see any error)
4. You will see an error message and after that save buttons will be disabled

**Context (please include the related information if applicable):**
 - erxes version: 0.11.4

**Comment by batamar** [comment]
Maybe fixed
