### ISSUE TITLE
Add new customer to open email input field

### ISSUE THREAD

**Issue by batchimeg-a** [erxes/erxes#1573]
![0 0756341127828073ss1](https://user-images.githubusercontent.com/15863495/72034458-fd72ce00-32cf-11ea-948c-55193e126e11.png)

**Comment by mooreT1881** [comment]
Why do I keep getting these notifications from y'all's page? On Jan 8, 2020 9:05 PM, "Batchimeg.a" <notifications@github.com> wrote:—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
