### ISSUE TITLE
Improve campaign in growth hack

### ISSUE THREAD

**Issue by Anu-Ujin** [erxes/erxes#1586]
**Is your enhancement request related to a problem? Please describe.**
Can't find the campaign add button.  
![Screenshot from 2020-01-10 14-14-20](https://user-images.githubusercontent.com/23444147/72130202-b958f980-33b3-11ea-993b-012608e9483a.png)

**Describe the solution you'd like**
Add green button with add new campaign in sidebar (add new project etc..)

**Comment by indraganzorig** [comment]
Hey there,

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
This idea has already been implemented.
Please use this link in the future to submit your features. 

Thank you.
