### ISSUE TITLE
Some module has no back action in settings

### ISSUE THREAD

**Issue by Anu-Ujin** [erxes/erxes#1587]
**Is your enhancement request related to a problem? Please describe.**
Some module has no back action in settings. (ex: segments, app store etc )

**Describe the solution you'd like**
Add back to settings action in segments, appstore like other modules in settings menu

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.
