### ISSUE TITLE
Improve warning message of account`s remove action 

### ISSUE THREAD

**Issue by Enkhtuvshin0513** [erxes/erxes#1607]
![Screen Shot 2020-01-13 at 5 13 32 PM](https://user-images.githubusercontent.com/37796969/72244325-fe399600-3628-11ea-9d28-addf9ade59f6.png)

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.
