### ISSUE TITLE
 Popups notification email settings are not working

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1616]
**To Reproduce**
1. Create popup
2. Goto  the thank content tab
3. Select the email type 
4. Fill the admin email, title, content
5. Click the save button

Problem1: When you go back, the settings are not saved. 
Problem2: Email not received. 

![ss1](https://user-images.githubusercontent.com/16484133/72410669-ee928c80-37a3-11ea-93be-54d440a3b4d2.png)

**Comment by batamar** [comment]
Too old
