### ISSUE TITLE
Not to show every available integration list

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#1617]
**Is your enhancement request related to a problem? Please describe.**
We don't need to show all the available integrations.

**Describe the solution you'd like**
Only to show connected integrations and its numbers.

**Additional context**

![Screen Shot 2020-01-15 at 4 38 01 PM](https://user-images.githubusercontent.com/1748857/72418287-80ef5c00-37b5-11ea-964f-52ae59d3f26b.png)

**Comment by batamar** [comment]
@mendorshikh Not important
