### ISSUE TITLE
When edit task item and opened it again, the changes were not saved.

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1620]
![captured (23)](https://user-images.githubusercontent.com/16484133/72496635-24e41080-3865-11ea-9c9b-6e1cf3d8f077.gif)

**To Reproduce**
1. Go to task
2. Click on task item
3. Edit task item
4. Close the window
5. Reopen the task
6. See the unchanged item name

**Comment by ganzorig** [comment]
it's fixed
