### ISSUE TITLE
Add checkbox in selected product service in deal section

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1630]
Distinguish exactly paid or used product, services from total selected products. Only the products checked will be charged. 

![ss1](https://user-images.githubusercontent.com/16484133/72706874-0c903080-3b9a-11ea-874d-d614fd3a0666.png)

**Comment by indraganzorig** [comment]
Hey there,

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
This idea has already been copied there as an insight.
Please use this link in the future to submit your features. 

Thank you.
