### ISSUE TITLE
Fix failing pipeline of PR

### ISSUE THREAD

**Issue by shinebayar-g** [erxes/erxes#1653]
**Describe the bug**
Currently PRs are failing because of bad CI/CD pipeline script.

**To Reproduce**
1. Make PR
2. Check pipeline status

**Expected behavior**
PR pipelines successfully pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/3091558/73586799-05a9cd80-4478-11ea-96d3-7a6ca9b075ab.png)

**Additional context**
https://gitlab.com/erxes/foss/cicd/erxes/pipelines/113536278

**Comment by Jason-2020** [comment]
See: https://github.com/erxes/erxes/issues/1911
