### ISSUE TITLE
Can't cancel poup

### ISSUE THREAD

**Issue by Anu-Ujin** [erxes/erxes#1671]
**Describe the bug**
When I click the close button, the popup is not closing.

**To Reproduce**
1. Go to erxes
2. Click on widget popup close
3. See error

**Expected behavior**
Closing the popup

**Screenshots**
![Screenshot from 2020-02-07 17-27-53](https://user-images.githubusercontent.com/23444147/74017437-3ab1a500-49cf-11ea-9989-e64309ee5c03.png)

**Context (please include the related information if applicable):**
 - OS: Ubuntu 18.04.3 LTS
 - Browser version chrome 79.0.3945.117
 - erxes version 0.12.3
 - installation type docker

**Comment by batamar** [comment]
Resolved in 0.13.0
