### ISSUE TITLE
confirm archive list in Board

### ISSUE THREAD

**Issue by batchimeg-a** [erxes/erxes#1679]
![Screen Shot 2020-02-11 at 3 01 26 PM](https://user-images.githubusercontent.com/15863495/74216547-bd907380-4cdf-11ea-865b-0652f3f059bf.png)

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.

**Comment by davidkartuzinski** [comment]
@ganzorig @batchimeg-a - Has this issue been resolved? Has this been implemented?

**Comment by ganzorig** [comment]
it's resolved
