### ISSUE TITLE
Team Inbox-н response template дээр хадгалсан template харагдахгүй байна

### ISSUE THREAD

**Issue by xypmact** [erxes/erxes#1716]
hi Free plan дээр бүртгэл үүсгээд Team Inbox-н response template дээр шинэ template үүсгээд хадгалхаар хадгалсан template Settings доторх response templates дотор байгаа хэрнээ team inbox дээр хариу өгөхөд харагдахгүй байна

**Comment by Batchimegb** [comment]
misunderstood.

**Comment by Batchimegb** [comment]
misunderstood.
