### ISSUE TITLE
Add a search to the Knowledge Base list

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#1728]
It's difficult to find when there are many rows in a list.

![ss1](https://user-images.githubusercontent.com/16484133/76137781-ae50db80-607b-11ea-825d-2ffe1ab39bd8.png)

**Comment by indraganzorig** [comment]
Knowledgebase articles are now searchable:
<img width="978" alt="Screenshot 2020-07-30 13 12 42" src="https://user-images.githubusercontent.com/53030705/88883338-a8e07180-d266-11ea-8ef0-16a703c0cfde.png">
