### ISSUE TITLE
Do you have an organization, Sign in

### ISSUE THREAD

**Issue by jsxs0** [erxes/erxes#1774]
The website page askes, for **Do you have an organization, Sign in**
I honestly believe that the organizational form should open there itself. Shouldn't redirect to the new page. And, the linguistics part should be looked after.
Thanks

**Comment by indraganzorig** [comment]
Hey there Jasveen,

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
This idea has already been copied there as an insight.
Please use this link in the future to submit your features. 

Thank you.
