### ISSUE TITLE
Chatbot crash

### ISSUE THREAD

**Issue by jsxs0** [erxes/erxes#1775]
The chatbot crashes (at times) at the [Create a new organization](https://erxes.io/create).
Honestly, the chatbot loads a bit late (too), probably because the scripting is to load heavy.
Also, the form floats, make the page statically dynamic for a while.
Thanks

**Comment by Mambatukaa** [comment]
Hey there, 
Thank you for your suggestion. We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features. I've already copied and submitted this insight there.

Thank you.

**Comment by davidkartuzinski** [comment]
@jsxs0 - Thanks for your report. This fell through the cracks. Are you using the latest version of erxes? On you using WordPress or how are you using Chat? Ar you still seeing the crashes?
