### ISSUE TITLE
Resources page doesn't open

### ISSUE THREAD

**Issue by jsxs0** [erxes/erxes#1776]
The resources option when clicked doesn't redirect.
It just changes to [nothing](https://erxes.io/#resources). So, either of the 2 things can be done:

- Either create a new resources page, which would help facilitate the process.

- Remove the option of clicking over the link, and just add an option to hover around. [This](https://erxes.io/#resources) shouldn't appear.
Thanks!

**Comment by ME200-Senses** [comment]
Hi, @jsxs0 Is this the link that the resources option should link to - https://erxes.io/resource-center. If not can you please give the link to the resources page?

**Comment by ME200-Senses** [comment]
Hi @jsxs0  Still waiting for the response
