### ISSUE TITLE
New constumer box should be round curved ast edges

### ISSUE THREAD

**Issue by aryangulati** [erxes/erxes#1788]
**Is your enhancement request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by indraganzorig** [comment]
Hey there,

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
This idea has already been copied there.
Please use this link in the future to submit your features. 

Thank you.
