### ISSUE TITLE
Login Animation Issue

### ISSUE THREAD

**Issue by DevenRathod2** [erxes/erxes#1791]
**Is your enhancement request related to a problem? Please describe.**
Their is a bug when we login/signup in to erxes and when we logout a quick animation execute so that animation is not working well you can improve it  

**Describe the solution you'd like**
right now rocket animation is moving up side so you can stick in center and play animation on same place it look perfect

**Comment by Mambatukaa** [comment]
Hey there, 
Thank you for your suggestion. We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features. I've already copied and submitted this insight there.

Thank you.

**Comment by davidkartuzinski** [comment]
@ganzorig - This is actually a bug.

**Comment by ganzorig** [comment]
I think it's solved or do i misunderstand that?

**Comment by davidkartuzinski** [comment]
@ganzorig - I tried to recreate the bug and it looks fixed. Let's close the issue unless @DevenRathod2 clarifies it again.
