### ISSUE TITLE
Provide Android SDK Sample Project on GitHub

### ISSUE THREAD

**Issue by DevenRathod2** [erxes/erxes#1792]
**Is your feature request related to a problem? Please describe.**
Erxes installation documentation is easy to understand but in some case some developer couldn't understand so if you provide a sample android or IOS SDK project on github it easy to under and learn erxes for android / IOS
**Describe the solution you'd like**
you can upload a sample project on github for Android SDK and IOS SDK so developer can easy understand how to implement or add sdk on android/IOS

**Comment by indraganzorig** [comment]
Hey there,

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
This idea has already been copied there as an insight.
Please use this link in the future to submit your features. 

Thank you.

**Comment by davidkartuzinski** [comment]
@DevenRathod2 - We are already improving the installation docs and also the installation process to make it even easier for all developers. Look out for new stuff over the next 2-4 weeks.

You should know that the apps are being considered for a total rework and will soon be going into a planning stage. 

Can you please clarify what you need for the sample android or iOS SDK?  We can add your feedback to the the process.

Thank you.
