### ISSUE TITLE
Add Telegram Apps on App Store

### ISSUE THREAD

**Issue by DevenRathod2** [erxes/erxes#1793]
**Is your feature request related to a problem? Please describe.**
I just check you app store and i would like to suggest you that please add telegram on app store it really important for you also 

**Describe the solution you'd like**
if you add telegram on app store you will get more users because is more secure that other messaging app like whatsapp and etc.

**Comment by indraganzorig** [comment]
We have Telegram available as integration in our OSS App Store now!
