### ISSUE TITLE
Marketplace for sales-experts 

### ISSUE THREAD

**Issue by dhairyaostwal** [erxes/erxes#1796]
## Enhancement to Knowledge Base
**Creating a marketplace for sales-experts**
1.  In addition to writing blogs to attract customers and help us market we should instead work on *creating a community*
2. A marketplace to promote learning. A place where not only potential new learners come to learn but 
also sales-expert come to share their knowledge.
3. This thing along with Blogs could help us in marketing and reaching out to several potential customers.
4. This thing can also be viewed as creating business like subscription base model for sales-experts' content.

**Comment by Mambatukaa** [comment]
Hey there, 
Thank you for your suggestion. We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features. I've already copied and submitted this insight there.

Thank you.

**Comment by davidkartuzinski** [comment]
> 1. In addition to writing blogs to attract customers and help us market we should instead work on _creating a community_
> 2. A marketplace to promote learning. A place where not only potential new learners come to learn but
>    also sales-expert come to share their knowledge.
> 3. This thing along with Blogs could help us in marketing and reaching out to several potential customers.
> 4. This thing can also be viewed as creating business like subscription base model for sales-experts' content.

@dhairyaostwal Thank you for your points here.  

1. I was recently hired as the Developer Advocate here at erxes. I would love to hear your ideas on how we can improve and make the community feel more welcoming and especially how it can be more helpful to you?
2. The learning and education hub is something that the founders are passionate about. As a internet marketer myself, I totally understand that we at erxes need to help our community with teaching best practices around marketing in general but also how to use our tool.  Do you consider yourself an expert in any part internet marketing (emailing, social media, SEO, etc) and do you have ideas or content you could contribute? What would it take for you to help out on this?
3. Are you saying we should allow you to blog on our blog and this could help you to be seen as more of an expert when you talk to your clients? Or are you suggesting something different? 
4. This idea of Premium content is very interesting. Are you saying that we at erxes should create premium courses and content that anyone could pay for and/or are you saying we should allow users in the community to create premium content and get paid for it?
