### ISSUE TITLE
Video Marketing

### ISSUE THREAD

**Issue by dhairyaostwal** [erxes/erxes#1797]
## Enhancement to Pop-ups & Forms
**Addition of tool to create short video**
1.  Content marketing via video is growing rapidly. 
2. One must also be provided with an ability to create short and interactive video along with posters and banners which can help out in marketing.

**Comment by Mambatukaa** [comment]
Hey there, 
Thank you for your suggestion. We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features. I've already copied and submitted this insight there.

Thank you.

**Comment by davidkartuzinski** [comment]
@dhairyaostwal - As a fellow internet marketer I totally agree that Video marketing is probably the most effective form of marketing. I am having a little trouble understand your idea.

Are you want us to provide a way to add a video from YouTube, Dailymotion, etc in the pop-up? Or are you asking for the ability to edit and create videos? 

Or perhaps are you suggesting an integration with an outside service that might help with this? If so, which services were you thinking about?

Thank you for your feedback and I look forward to your clarification and specific use case.

**Comment by dhairyaostwal** [comment]
Hey @davidkartuzinski thanks very much for your interest! Here I was referring to the feature to edit videos and images since it's going to be a marketing software.
Marketing in terms of short movie clips and with new features like Instagram Reels I think it'd be a good feature to add in.

@davidkartuzinski also one kind request if you could check in for my goodies to be delivered. Thanks 😄

**Comment by davidkartuzinski** [comment]
@dhairyaostwal - Thank you for clarifying about the videos and images. Unfortunately editing videos (and therefore hosting them) is beyond the scope and vision for erxes. 

Image editing could one day be implemented. What use case do you see you mostly using image editing for?

As to your goodies. Who were you talking to about them? Were you promised some goodies? @indraganzorig
