### ISSUE TITLE
Hamburger icon not visible in iphone X.

### ISSUE THREAD

**Issue by imrishabh18** [erxes/erxes#1800]
**Describe the bug**
The hamburger icon for navbar is not there .

**Comment by luko0610** [comment]
I could take that issue if you want. The main reason for that happening is the social icons in the footer increasing overall width.
I would fix it by splitting them up into two columns.

Please let me know if you want me to fix it.

**Comment by davidkartuzinski** [comment]
@ganzorig - Could you please help with this?

**Comment by ganzorig** [comment]
@davidkartuzinski ok
