### ISSUE TITLE
Not showing as mail - gmail

### ISSUE THREAD

**Issue by fasalmbt** [erxes/erxes#1812]
Gmail mail shows as a message

reproduction of bug:- 

    Create Gmail integration
    Send email to integrated Gmail
    Email shows as a message

Expected behavior
Shows as email

Context (please include the related information if applicable):

    erxes version [0.12.0]

**Comment by munkhorgil** [comment]
Hello @fasalmbt,
It's already fixed in Relase [0.13.0](https://github.com/erxes/erxes/releases/tag/0.13.0)
