### ISSUE TITLE
Don't show clear button when a deal card shows up

### ISSUE THREAD

**Issue by munkhorgil** [erxes/erxes#1824]
**Describe the bug**
Do not show clear filter button shows when the deal card modal show up

**To Reproduce**
1. Go to a Deal section
2. Click on any deal card
3. Clear filter button shows up in  the action bar

**Expected behavior**
Do not show clear filter button shows when the deal card modal show up

**Context (please include the related information if applicable):**
 - OS: [macOS 10.15]
 - Browser version [chrome 80.0]
 - erxes version [0.13.0]

**Comment by ganzorig** [comment]
It's fixed
