### ISSUE TITLE
Appearance change

### ISSUE THREAD

**Issue by lakshyatyagi24** [erxes/erxes#1837]
Font and font size should be change.

**Comment by ganzorig** [comment]
@lakshyatyagi24 can you explain more specifically?

**Comment by ShyamPraveenSingh** [comment]
Hi, I would like to work on this issue.

**Comment by batamar** [comment]
Hi @ShyamPraveenSingh. Please

**Comment by ShyamPraveenSingh** [comment]
Can you please tell me in detail of which file I have to fonts?

**Comment by davidkartuzinski** [comment]
@lakshyatyagi24 - Could you please describe which fonts need to be changed and include screenshots?
