### ISSUE TITLE
Missing image file

### ISSUE THREAD

**Issue by indraganzorig** [erxes/erxes#1843]
**Describe the bug**
Missing image file for "magicwand" in knowledgebase category

**To Reproduce**
1. Open Knowledgebase
2. Add/Edit Category
3. Scroll down to "magicwand" in "Icon"

**Screenshots**
<img width="571" alt="Screenshot 2020-03-25 13 43 24" src="https://user-images.githubusercontent.com/53030705/77615434-5fa3ac80-6f6a-11ea-97e3-c84156f64b2c.png">

**Context (please include the related information if applicable):**
Chrome 80 on macOS (Mojave)

**Comment by batamar** [comment]
resolved in 0.14.0
