### ISSUE TITLE
German Date in Live Chat is Russian

### ISSUE THREAD

**Issue by QuickTrans** [erxes/erxes#1854]
If you set the language in the Live Chat Widget to German, the date is displayed in a strange format (Russian or something). All other translations are correct (in german)

![Bildschirmfoto 2020-03-28 um 02 08 34](https://user-images.githubusercontent.com/41891479/77811200-30d82400-7099-11ea-9da2-9eb2c088bc33.png)

**Comment by gunjanmimo** [comment]
I want to take this issue

**Comment by Jason-2020** [comment]
Actually it's in Mongolian. @gunjanmimo please feel free to raise PR.
