### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by Anant016** [erxes/erxes#1857]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [e.g docker, manual]

**Additional context**

**Comment by indraganzorig** [comment]
Hey @Anant016 
We reviewed your free swag submission and it seems like it's incomplete.
Also, the email you gave us is not working.
Could you please check these and submit your request again? 
https://erxes.io/hubspot-alternative-erxes-swag
