### ISSUE TITLE
Smooch integration doc enhancement

### ISSUE THREAD

**Issue by MujiGMJ** [erxes/erxes#1886]
Smooch integration instruction needs to update the followings. 
1. Write a brief description. Smooch API for conversation or for what? Make clear it such what is the purpose of that integration...
2. Insert additional instruction for how to find out Viber token.
3. Telegram.n Botfather link correct or not?
4. If integration is successful, how it is shown, please insert the figure of results.

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.

**Comment by davidkartuzinski** [comment]
@MujiGMJ @soyombo-baterdene - Has this issue been handled? It seems this was accidentally closed.
