### ISSUE TITLE
Permissions not showing

### ISSUE THREAD

**Issue by sahil9001** [erxes/erxes#1890]
**Describe the bug**
I recently set up the exres using docker on Ubuntu, while running it on firefox and doing initial setup of the interface I came across a page of user creation for brand, in that page I'm able to fill the email section(required) but when I try to select the permission option(required) it's blank.

**To Reproduce**
1. Setup exres on docker in Ubuntu 16.04.
2. Go to `localhost:8000`.
3. Setup the brand upto User creation page.

**Expected behavior**
I expected some options to show up in the permission column.

**Screenshots**
![Screenshot from 2020-04-03 23-25-56](https://user-images.githubusercontent.com/32628578/78390745-b6605480-7602-11ea-8a17-57fc4eda9866.png)

**Context (please include the related information if applicable):**
 - OS:  Ubuntu 16.04
 - Browser version: Mozilla Firefox 74.0
 - erxes version: 0.9.17
 - installation type: docker

**Comment by sahil9001** [comment]
@MujiGMJ

**Comment by sahil9001** [comment]
@MujiGMJ Can you see this issue?

**Comment by sahil9001** [comment]
@mendorshikh please have a look at this issue

**Comment by Jason-2020** [comment]
Hi, @sahil9001 . Could you install it on [debian](https://docs.erxes.io/installation/debian10)/[centos ](https://docs.erxes.io/installation/centos8)machine and see how it's working? Because our Ubuntu / Docker installation methods are little bit outdated.
