### ISSUE TITLE
Clarify stage remove error message 

### ISSUE THREAD

**Issue by Buyantogtokh** [erxes/erxes#1895]
**Is your enhancement request related to a problem? Please describe.**
When removing a deal/task pipeline stage that has items inside, it throws error with message "There is a stage that has item" which is very confusing. Users want to see the exact stage, item names & go check them out. 

**Describe the solution you'd like**
Show a clear message with exact stage & item names.

**Comment by batamar** [comment]
resolved in 0.14.0
