### ISSUE TITLE
Notification links are broken

### ISSUE THREAD

**Issue by Buyantogtokh** [erxes/erxes#1914]
**Describe the bug**
When a Deal/task/ticket/growthHack is moved between stages, all links of notifications related to this item will be broken.

**To Reproduce**
1. Go to any deal/task/ticket/growthHack & assign someone.
2. Make some edits, so that multiple notifications will be created.
3. Move it between any board/pipeline/stage.
4. Login as the newly assigned team member.
5. Click the old notifications
6. The item will not be shown

**Expected behavior**
Old & new notifications should show the item properly regardless of stage changes.

**Comment by batamar** [comment]
resolved in 0.14.0
