### ISSUE TITLE
Segment new rules

### ISSUE THREAD

**Issue by batamar** [erxes/erxes#1915]
**Is your feature request related to a problem? Please describe.**
Currently, we covered the following scenarios

1. Trigger action before some date occurs
2. Trigger action after some date occurs
3. Trigger action on exact days.

**Describe the solution you'd like**
Add the following new segment rules
  { name: 'will occur before on following n-th minute', value: 'wobm' },
  { name: 'will occur after on following n-th minute', value: 'woam' },
  { name: 'will occur before on following n-th day', value: 'wobd' },
  { name: 'will occur after on following n-th day', value: 'woad' },
  { name: 'date relative less than', value: 'drlt' },
  { name: 'date relative greater than', value: 'drgt' },

**Comment by MujiGMJ** [comment]
> **Is your feature request related to a problem? Please describe.**
> Currently, we covered the following scenarios
> 
> 1. Trigger action before some date occurs
> 2. Trigger action after some date occurs
> 3. Trigger action on exact days.
> 
> **Describe the solution you'd like**
> Add the following new segment rules
> { name: 'will occur before on following n-th minute', value: 'wobm' },
> { name: 'will occur after on following n-th minute', value: 'woam' },
> { name: 'will occur before on following n-th day', value: 'wobd' },
> { name: 'will occur after on following n-th day', value: 'woad' },
> { name: 'date relative less than', value: 'drlt' },
> { name: 'date relative greater than', value: 'drgt' },

What does it meaning of all this rule's value?
