### ISSUE TITLE
docker 0.13.0 tag is missing

### ISSUE THREAD

**Issue by karser** [erxes/erxes#1918]
**Describe the bug**
The tag 0.13.0 is present for erxes/erxes-api but is missing for the following repos:
https://hub.docker.com/r/erxes/erxes/tags
https://hub.docker.com/r/erxes/erxes-integrations/tags
https://hub.docker.com/r/erxes/erxes-widgets/tags
https://hub.docker.com/r/erxes/erxes-widgets-api/tags
https://hub.docker.com/r/erxes/erxes-logger/tags
https://hub.docker.com/r/erxes/erxes-engages-email-sender/tags

**Comment by Jason-2020** [comment]
Hi @karser . We're working on the [issue](https://github.com/erxes/erxes/issues/1911).

TLDR; Our releases process are broken because of merging repos together and changing our CI platform.

**Comment by karser** [comment]
I see, got it

**Comment by Jason-2020** [comment]
Hi. Sorry for the long delay.
We've finally pushed new images with `0.14.0` tag. Unfortunately `0.13.0` is still missing, but you should be able to use `0.14.0` without issues.

Hope this resolves this issue.

**Comment by karser** [comment]
Cool, thanks!
