### ISSUE TITLE
Populate placeholder text on demo website

### ISSUE THREAD

**Issue by notpallav** [erxes/erxes#1924]
**Describe the solution you'd like**
On the demo website, populate the fields with email/pass instead of just being placeholder text.

**Comment by Mambatukaa** [comment]
Hey there, 
Thank you for your suggestion. We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features. I've already copied and submitted this insight there.

Thank you.

**Comment by davidkartuzinski** [comment]
This should probably be considered a "bug". Our Demo site should have realistic information. @batamar - I am not sure who should deal with this?
