### ISSUE TITLE
Error when creating first Sales Pipeline Board

### ISSUE THREAD

**Issue by XUBIUM** [erxes/erxes#1925]
**Describe the bug**
When an admin or a non-admin user attempts to create the first Sales Pipeline board on a freshly installed system, error message "Attempting to restore connection. Changes made now may not be saved" is displayes. It doesn't seem to cause any error. I tested it both in a DO Marketplace image and on a freshly installed Debian 10 system.

**To Reproduce**
1. Install a new system from the DO Marketplace or following instructions at https://docs.erxes.io/installation/debian10
1. Go to 'Sales Pipeline' (pig icon in the left bar)
2. Click on the gear icon next to 'Choose Pipeline' to create the first board
3. Error is shown at the top of the screen

**Expected behavior**
An error message shouldn't be shown.

**Screenshots**

**Context (please include the related information if applicable):**
 - OS: Ubuntu 18.04 x64 and Debian 10.3 x64
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version 0.13.0
 - installation type Debian 10 manual and Ubuntu by using the DO Marketplace

**Comment by mendorshikh** [comment]
@Xubium Thank you for reporting an issue. We will resolve asap.

**Comment by batamar** [comment]
@XUBIUM Please use new version. I hope that it is fixed
