### ISSUE TITLE
Error Message "No customers found who have valid emails" 

### ISSUE THREAD

**Issue by akhileshcse** [erxes/erxes#1931]
1)In Menu click on contacts (Url:- http://165.22.218.63/contacts/customers/all)
![1](https://user-images.githubusercontent.com/4433985/79188709-6c1a7700-7e3d-11ea-9bc8-6a84ba3b94bb.PNG)
2)Select one contact and click on the message button on top.
![2](https://user-images.githubusercontent.com/4433985/79188707-6c1a7700-7e3d-11ea-9be4-fde932b410f0.PNG)
3)Quick message Pop box open then fill Channel->Email, Titel, Email Subject, Email templates->any templates, click on the SEND button.
![3](https://user-images.githubusercontent.com/4433985/79188706-6b81e080-7e3d-11ea-86b7-c858f9012937.PNG)
4)Error Message "No customers found who have valid emails"
![4](https://user-images.githubusercontent.com/4433985/79188701-69b81d00-7e3d-11ea-8f27-102f95cb675d.png)

In settings -> engage-configs->setup SES config
Not able to send an email template to any contact user.

**Comment by mendorshikh** [comment]
Hello @akhileshcse, thanks for the feedback. First of all, it seems a fixed problem for the later release 0.13.0. Please update it.

In the new release, when you try to send EMAIL from your customer profile, you need to connect EMAIL not AMAZON SES. Amazon SES is for the BULK email broadcast.

PS: Please join our community via https://community.erxes.io/register/Gw4WRJnk9fSbyAXTq and get technical chat support.

**Comment by akhileshcse** [comment]
Thanks, MJ for the reply, we are using later release 0.13.0, and we are not able to send a BULK email the same issue and it was also not working in your live site https://adstuckconsulting.app.erxes.io/.
please check.

**Comment by mendorshikh** [comment]
@akhileshcse Oh, I got it. I've just tested and your right. We will fix it ASAP. Thanks for the feedback.

**Comment by batamar** [comment]
@akhileshcse Added Unverified emails limit config. Default is 100

<img width="774" alt="Screen Shot 2020-05-03 at 00 28 41" src="https://user-images.githubusercontent.com/1748899/80869821-18c97500-8cd5-11ea-9489-f08b39fcf441.png">
