### ISSUE TITLE
Make possible to add tag on customer and company import

### ISSUE THREAD

**Issue by Enkhtuvshin0513** [erxes/erxes#1932]

**Comment by indraganzorig** [comment]
Hey there,

This issue is outdated or there is a more recent duplicate.
Closing this issue to keep the Issues less cluttered.

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
Please use this link in the future to submit your features.

Thank you.

**Comment by davidkartuzinski** [comment]
@Enkhtuvshin0513 - With your recent import/export improvement. Can we now add a tag on a customer or company when we import? I think so? 

If yes, can you reopen and close this issue and reference the Pull Request you made?
