### ISSUE TITLE
Fix social media icons on mobile

### ISSUE THREAD

**Issue by tadhglewis** [erxes/erxes#1956]
**Describe the bug**
Social media buttons in website footer do not wrap

**To Reproduce**
1. Go to https://erxes.io/
2. Scroll down to the footer
3. On mobile/small screens the social media icons do not wrap and instead because very small

**Expected behavior**
Social media icons should wrap into multiple lines

**Screenshots**
![image](https://user-images.githubusercontent.com/53756558/80300811-249fcd80-87e3-11ea-9624-6a293e422a93.png)

**Context (please include the related information if applicable):**
N/A

**Additional context**
CSS property `flex-wrap: wrap;` should be added to `.main-footer .social-bar .social`

**Comment by Niravprajapati1** [comment]
can i work on this issue
