### ISSUE TITLE
Fix try the live demo button being covered

### ISSUE THREAD

**Issue by tadhglewis** [erxes/erxes#1958]
**Describe the bug**
On mobile < 600px the 'Try The Live Demo' button is covered by the hero line

**To Reproduce**
1. Go to https://erxes.io/
2. On mobile the hero buttons are covered

**Expected behavior**
Be able to fully see hero buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/53756558/80301048-e7d4d600-87e4-11ea-817e-c6846ecd2413.png)
![image](https://user-images.githubusercontent.com/53756558/80301053-f02d1100-87e4-11ea-992b-8c1b36e3580d.png)

**Context (please include the related information if applicable):**
N/A

**Additional context**
N/A

**Comment by mendorshikh** [comment]
@tadhglewis Well received. Thank you for the issues. Please join our community via https://community.erxes.io/register/Gw4WRJnk9fSbyAXTq
