### ISSUE TITLE
Different licenses in different files

### ISSUE THREAD

**Issue by pahaz** [erxes/erxes#1963]
- You have LICENSE file with `GPL` license.
 - You have `package.json` with https://github.com/erxes/erxes/blob/cb641b2184c6e2f7d90d10c5b91f080c8660d1b6/package.json#L14 `MIT` license.

**Comment by heyakyra** [comment]
The new clause is incompatible with GPL and violates the copyright of all contributors before the clause was added: 

> Without limiting other conditions in the License, the grant of rights under the License will not include, and the License does not grant to you, the right to Sell the Software.

You probably want something like AGPL for better protection without infringing on your contributors license.
