### ISSUE TITLE
Some erxes pages are blocked with uBlock Origin

### ISSUE THREAD

**Issue by ulziibay** [erxes/erxes#1966]
**Describe the bug**
When loading erxes.mn/swag with uBlock origin v1.26, the form is hidden because it makes requests to https://www.googletagmanager.com/gtm.js?id=GTM-KBQC2JN

**To Reproduce**
1. Enable uBlock origin
2. Go to erxes.mn/swag
3. See nothing for the form

**Expected behavior**
The ublock log: 
```
Filter
||googletagmanager.com/gtm.js$script
Filter list
uBlock filters – Privacy 
Context
erxes.mn
Partyness
(3) erxes.mn ⇒ googletagmanager.com
Type
script
URL
https://www.googletagmanager.com/gtm.js?id=GTM-KBQC2JN
```
**Screenshots**

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [e.g docker, manual]
<img width="440" alt="Screen Shot 2020-04-30 at 1 44 41 PM" src="https://user-images.githubusercontent.com/1626382/80752462-c3c90b80-8ae8-11ea-971d-7848bb95adb5.png">

**Additional context**

**Comment by ulziibay** [comment]
@batamar: tanai hed heden page chin AdBlock deer orod baij bolzoshgum bn. https://www.googletagmanager.com/gtm.js heregledeg bol, blocklodog yum bn!

**Comment by batamar** [comment]
@ulziibay Ok. Bayrlalaa. Shalgaad zasay

**Comment by Buyantogtokh** [comment]
@ulziibay After some research, ad blocking extensions such as "ublock" blocks google tag manager by default. We've linked the swag popup & messenger without google tag manager as an easy solution.
