### ISSUE TITLE
Add success message after "Find your organization

### ISSUE THREAD

**Issue by indraganzorig** [erxes/erxes#1969]
**Is your enhancement request related to a problem? Please describe.**
No message is displayed when a user tries to recover their organization name from https://erxes.io/search-organizations. It just goes back to home page.

**Describe the solution you'd like**

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.
