### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by fatihbaskaya** [erxes/erxes#1974]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [e.g docker, manual]

**Additional context**

**Comment by indraganzorig** [comment]
Hello @fatihbaskaya 
Thanks for your interest in erxes.
Please submit a clear description of the issue...
