### ISSUE TITLE
Clarify new sign up / email confirmation process

### ISSUE THREAD

**Issue by indraganzorig** [erxes/erxes#1983]
**Is your enhancement request related to a problem? Please describe.**
Some SaaS users are confused by the initial sign up. My theory is that they just close the https://erxes.io/create after entering their email address and go to their inbox to confirm their email address. This results in broken sign up process: no username/password is set. Also, right after entering the 6 digit code as email confirmation, the visitor is just taken to the home page without any success message or whatsoever. 

**Describe the solution you'd like**
- Ask the new user not to close the initial tab and to stay on the page after step 1 (entering email address)
- Display success message after email confirmation or take them to their subdomain.

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.
