### ISSUE TITLE
Italian translation for date in Messenger is missing

### ISSUE THREAD

**Issue by indraganzorig** [erxes/erxes#1995]
**Describe the bug**
When the default language for Messenger is set to Italian, everything is translated except the date on top.

**To Reproduce**
Change the Messenger default language to Italian.

**Screenshots**
![image](https://user-images.githubusercontent.com/53030705/82030713-6083cf80-96cb-11ea-90df-fa85dfc49f27.png)

**Comment by batamar** [comment]
Planning general fix. Not just for italian
