### ISSUE TITLE
Deprecation warning on yarn initProject command

### ISSUE THREAD

**Issue by hangai247** [erxes/erxes#2008]
**Is your enhancement request related to a problem? Please describe.**
When during project initialization for development purpose, I got an error with the following message when I ran `yarn initProject` command
DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

**Describe the solution you'd like**
I don't want to see any warning. 

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by batamar** [comment]
@hangai247 Depending on mongodb version, It says different things
