### ISSUE TITLE
Facebook Messenger / Post Integration

### ISSUE THREAD

**Issue by JovanS-BAD** [erxes/erxes#2012]
**Describe the bug**
Integration for Facebook Messaenger / Post doesnt work any more due API changes.
On May 5, 2020, we released six new Page permissions to replace the manage_pages and publish_pages permissions. The manage_pages permission has been replaced with pages_manage_ads, pages_manage_metadata, pages_read_engagement, and pages_read_user_content. The publish_pages permission has been replaced with pages_manage_posts and pages_manage_engagement.

Please visit our V7.0 Blog post, Graph API Changelog, and Pages API Overview for more information.
https://developers.facebook.com/docs/facebook-login/permissions/#reference-manage_pages

**To Reproduce**
Go to Integrations
Select Facebook Messenger, follow the docs

**Context (please include the related information if applicable):**
- erxes 0.14.1 ver

**Comment by engmsaleh** [comment]
Are these changes are applied yet?

**Comment by engmsaleh** [comment]
Any updates on new Facebook policy change ?

**Comment by davidkartuzinski** [comment]
@engmsaleh - we are nearly ready to release our fixes and they should be released on Friday. This includes some corrections/edits on the documentation. We are also releases a few improvements to the Facebook integration which you will be excited about when you see the changelog.

@Enkhtuvshin0513 - do you want to say anything else about this?

**Comment by engmsaleh** [comment]
Great news @davidkartuzinski I will be waiting for the release 👍
