### ISSUE TITLE
Twitter Integration

### ISSUE THREAD

**Issue by JovanS-BAD** [erxes/erxes#2016]
**Describe the bug**
Twitter integration doesnt work either. When you click add acount in modal of Twitter integration, it keeps spinning(sending request) and at the end you get 504 bad gateway.

**To Reproduce**
1. Go to Twitter Integration
2. Press Add account

**Context (please include the related information if applicable):**

 - erxes version 0.14.1

**Comment by batamar** [comment]
Resolved
