### ISSUE TITLE
Segment creation - Customers/Companies - On show count taking leads instead.

### ISSUE THREAD

**Issue by JovanS-BAD** [erxes/erxes#2020]
**Describe the bug**
When you create new segment for Customers and add a rule/event what ever.
By clicking show count I noticed that its showing count of Leads and not actual customers.
i.e. I have 7900 leads and 800 customers.
Show count should show: 800 as I am creating customer segment and not leads one.
But its showing: 7900.
Probably same happening for **Companies**.

**To Reproduce**
Go to Manage Segments / Customers

**Expected behavior**
Show count of customers only
+ defined rules/events

**Screenshots**

![image](https://user-images.githubusercontent.com/63701628/82734253-21ccc580-9d1a-11ea-9165-ea1bb9f1c689.png)

**Context (please include the related information if applicable):**

 - erxes version 0.14.1 - develop

**Comment by batamar** [comment]
@JovanS-BAD There is state property available in filters.

For example: If you want to show only customers Add the following filter first

state - equals - customer

**Comment by JovanS-BAD** [comment]
Aha I see.
Alright you can close this one.
Thanks
