### ISSUE TITLE
Relate company to lead/customer - Search for existing company doesnt work

### ISSUE THREAD

**Issue by JovanS-BAD** [erxes/erxes#2021]
**Describe the bug**
If you want to relate a company to lead/customer, you can only add new company, but you cant relate existing as if you search for existing nothing pop ups. What ever you type nothing happens.

Adding new company works.

**To Reproduce**
Go to relate company tab
Try to search fo existing company

**Expected behavior**
Display list of companies based on keyword inputed in search bar

**Screenshots**
<img width="1368" alt="Screenshot 2020-05-23 at 21 54 09" src="https://user-images.githubusercontent.com/63701628/82739496-48055c00-9d40-11ea-8948-8f1d61084881.png">

**Context (please include the related information if applicable):**
 - erxes version 0.14.1 - develop

**Comment by batamar** [comment]
@JovanS-BAD Currently it is searching the whole word. Please show companies list for this company to confirm that it is the whole company name.

**Comment by JovanS-BAD** [comment]
Check screenshoots, even with full exact name of company nothing appears.
<img width="1355" alt="Screenshot 2020-05-24 at 10 23 30" src="https://user-images.githubusercontent.com/63701628/82749341-de6d6800-9da8-11ea-8a0e-14579ad01cb0.png">
<img width="1372" alt="Screenshot 2020-05-24 at 10 23 52" src="https://user-images.githubusercontent.com/63701628/82749344-e0cfc200-9da8-11ea-8b1e-2d290453f3cc.png">
