### ISSUE TITLE
Guide on upgrading to latest Erxes for 1-Click DO

### ISSUE THREAD

**Issue by roshanjonah** [erxes/erxes#2024]
What is the proper way to upgrade 1-click DO to the latest erxes? If there is a guide on upgrading rather than a generic upgrade guide which I see in documentation - that would make things much easier to iron out some of the bugs that have been addressed already!

**Comment by Youssef-Harby** [comment]
i have the same Inquiry

**Comment by roshanjonah** [comment]
The wonderful team at Erxes have helped me upgrade it from 0.13 to 0.14 and they asked me to follow this guide - https://docs.erxes.io/installation/upgrade

The guide has a script you can run so you can easily upgrade using that script - it does most of the work for you. Just make sure to backup and also move the old files as sometimes that's been known to cause issues. I hope that helps. You can always talk to them via Rocketchat - see link on their website.
