### ISSUE TITLE
Twitter - Linked Accounts - Add failure

### ISSUE THREAD

**Issue by iammattmartin** [erxes/erxes#2029]
**Describe the bug**
When trying to link a Twitter account, you click on "+ Add Account" and nothing seems to happen. Browser has a loading icon on the tab but then this times out entirely then gives a "504 Gateway Time-out" error.

**To Reproduce**
Go to the integrations, add Twitter DM, click +Add Account for the linked account.

**Expected behavior**
Would expect this to forward me over to Twitter to validate the the app and then pass back.

**Context (please include the related information if applicable):**
 - OS: Ubuntu 18
 - Browser version: Firefox, latest.
 - erxes version Latest as per install docs (non-docker).
 - installation type: manual.

**Additional context**
Nginx error:

> 2020/05/26 20:01:47 [error] 11096#11096: *355 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: xxxxx.xxx, request: "GET /integrations/twitter/login?kind=twitter&userId=WR4Xs7QAMmbpTt73m HTTP/1.1", upstream: "http://127.0.0.1:3400/twitter/login?kind=twitter&userId=WR4Xs7QAMmbpTt73m", host: "xxxxx.xxx", referrer: "https://xxxxx.xxx/settings/integrations?type=All%20integrations"

Trying to go to that URL does just timeout.

> root@xxx:~# curl http://127.0.0.1:3400/twitter/login
> curl: (52) Empty reply from server

**Comment by Enkhtuvshin0513** [comment]
outdated
