### ISSUE TITLE
Engage module to use custom SMTP

### ISSUE THREAD

**Issue by roshanjonah** [erxes/erxes#2031]
**Is your feature request related to a problem? Please describe.**
When trying to engage with our customers, we do not use Amazon SES, we have our own SMTP provider and we need to be able to use them.

**Describe the solution you'd like**
Allow the use of custom SMTP services like Mandrill, Postmark, and other popular transactional email services!

**Comment by Mambatukaa** [comment]
Hey there, 
Thank you for your suggestion. We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features. I've already copied and submitted this insight there.

Thank you.
