### ISSUE TITLE
Add .env.sample in the frontend / Update docs.

### ISSUE THREAD

**Issue by sahil9001** [erxes/erxes#2034]
**Is your enhancement request related to a problem? Please describe.**
Docs at https://docs.erxes.io/developer/developer/ for frontend states to run the command ```cp .env.sample .env``` while in the frontend repository there's no ```.env.sample``` file.

**Describe the solution you'd like**
Solution would either be to update the docs or to add the ```.env.sample``` file.

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by hangai247** [comment]
#2009 Duplicated

**Comment by sahil9001** [comment]
I solved that lol
