### ISSUE TITLE
Viewed Pages

### ISSUE THREAD

**Issue by joepa37** [erxes/erxes#2039]
It might be a good idea to collect data from pages visited by date

![image](https://user-images.githubusercontent.com/15274305/83321616-0e37c800-a20e-11ea-9631-b2cf2f6b2cd9.png)

**Comment by ganzorig** [comment]
@joepa37 we can collect data from pages visited. You want to view by date? ![Page views](https://i.ibb.co/zQF1TGG/Screen-Shot-2020-08-03-at-00-16-47.png)

**Comment by joepa37** [comment]
@ganzorig yes, after a few time collecting data, will be a better way to see the flow how the user moves within the website ordering by date; as a real visit history.
