### ISSUE TITLE
Property 'byLifecycleState' does not exist on type 'CompanyCounts | { byLifecycleState: {}; }'

### ISSUE THREAD

**Issue by meSingh** [erxes/erxes#2063]
**Describe the bug**
I'm trying to install using the Debian install script, have tried several times using different VPS's and even deployed a fresh one, but it just doesn't work. Keep getting this error:  

**To Reproduce**
1. Get a fresh Ubuntu 18.04.3 installation  
2. Login as root
3. Run the Debian install script
```
bash -c "$(wget -O - https://raw.githubusercontent.com/erxes/erxes/master/scripts/install/debian10.sh)"
```

**Screenshots**
<img width="909" alt="Screenshot 2020-06-18 at 5 13 38 PM" src="https://user-images.githubusercontent.com/2369397/85016684-d924f280-b187-11ea-9865-bcb723ec045b.png">

**Context (please include the related information if applicable):**
 - OS: Ubuntu 18.04.3
 - erxes version 0.14.1
 - installation type Debain Install Script

**Comment by batamar** [comment]
@meSingh fixed
