### ISSUE TITLE
bug: Undefined issues in the network calls.

### ISSUE THREAD

**Issue by geekyoperand** [erxes/erxes#2064]
**Describe the bug**
Got undefined in the URL of network calls which is resulting to 404 error.

**To Reproduce**
1. Go to https://demo.erxes.io/inbox/index?_id=5FpMoeTqcBC5tQbWZ
2. Click on the dev tools and go to network tab.
3. Scroll down
4. You can see that requests are calling with some undefined in URLs.

https://demo.erxes.io/widgets/undefined/graphql

**Expected behavior**
The link must not contain undefined.

**Screenshots**
![image](https://user-images.githubusercontent.com/52500177/85066178-114e2480-b1cc-11ea-8b2d-edc9e0c47b3b.png)

**Comment by batamar** [comment]
@geekyoperand fixed
