### ISSUE TITLE
bug: Page becomes blank due to url of undefined issue of urls

### ISSUE THREAD

**Issue by geekyoperand** [erxes/erxes#2065]
**Describe the bug**

**To Reproduce**
1. Go to https://demo.erxes.io/inbox/index?_id=5FpMoeTqcBC5tQbWZ
2. Click on Robot Image at left bottom
![image](https://user-images.githubusercontent.com/52500177/85068434-02697100-b1d0-11ea-9a85-d8d291197f2e.png)

3. Click on start on boarding in the overlay panel.

![image](https://user-images.githubusercontent.com/52500177/85068576-48bed000-b1d0-11ea-98c2-dadc1a96570c.png)

4. Click on any one of the item in the screenshot below. For example I clicked on Sales Pipeline
![image](https://user-images.githubusercontent.com/52500177/85068654-6c821600-b1d0-11ea-8633-b7f4cc74563f.png)

5. The page goes blank due to some issues in the console. which is due to non-proper checks but on Refresh it loads perfectly.

**Expected behavior**
The page must not break due to errors in the react.

**Screenshots**
![image](https://user-images.githubusercontent.com/52500177/85068878-c7b40880-b1d0-11ea-97c1-7833bb7332fe.png)
![image](https://user-images.githubusercontent.com/52500177/85068931-da2e4200-b1d0-11ea-8b39-1a6dc95ec01e.png)

**Comment by batamar** [comment]
@geekyoperand fixed
