### ISSUE TITLE
Property 'byLifecycleState' does not exist on type 'CompanyCounts

### ISSUE THREAD

**Issue by RileySeaburg** [erxes/erxes#2074]
**Describe the bug**
I'm trying to upgrade from 0.13.0 to 0.14.1 this is the error I get when I try.

TypeScript error in /home/erxes/erxes/ui/src/modules/companies/containers/filters/LifecycleStateFilter.tsx(23,22):
Property 'byLifecycleState' does not exist on type 'CompanyCounts | { byLifecycleState: {}; }'.
  Property 'byLifecycleState' does not exist on type 'CompanyCounts'.  TS2339

    21 | 
    22 |     const updatedProps = {
    23 | >  counts: counts.byLifecycleState || {},
         |                      ^
    24 |       loading: (companyCountsQuery ? companyCountsQuery.loading : null) || false
    25 |     };

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 18.04]
 - erxes version [0.13.0]
 - installation type [manual]

**Comment by batamar** [comment]
@RileySeaburg fixed
