### ISSUE TITLE
Zapier Support

### ISSUE THREAD

**Issue by ned-kelly** [erxes/erxes#2079]
Just wondering what the ETA on Zapier support is and/or what would be required if I was to submit a PR myself with the support?

(Am a dev so happy to look at integrating if there's some sort of standard I can follow to make it easier).

Cheers,

**Comment by davidkartuzinski** [comment]
@ned-kelly I would love to talk to you about contributing.  Is there a way we can chat in the community chat https://community.erxes.io/?

**Comment by ned-kelly** [comment]
Thanks @davidkartuzinski - Will hopefully join next week once I pick this project back up (have some other ones we're just wrapping up).

Cheers,

**Comment by davidkartuzinski** [comment]
@ned-kelly - Next week can come fast enough.  

I am going to close this issue as I think we're now on each others radar.  I look forward to chatting with you once your other projects are under control or wrapped up!
