### ISSUE TITLE
There are zero customer testimonials visible on the main website.

### ISSUE THREAD

**Issue by abhy-kumar** [erxes/erxes#2081]
**Describe the bug**
There are zero customer testimonials visible on the main website.

**To Reproduce**
1. Go to 'https://erxes.io/'
2. Scroll down to 'Here's what our customers say about us:'
3. See error

**Expected behavior**
Some testimonials from existing users, or a WIP message if it is in works.

**Screenshots**
![image](https://user-images.githubusercontent.com/35186422/86493125-f4018480-bd8d-11ea-8f44-917876bb61ec.png)

**Desktop (please complete the following information):**
 - OS: [Manjaro Linux, kernel v5.8]
 - Browser [Firefox]
 - Version [78.0.1]

**Comment by davidkartuzinski** [comment]
@abhy-kumar This now seems fixed.  Could you please recheck? Please try a chromium based browser if it doesn't work in firefox. Please let me know the results.

Thank you for reporting this issue.
