### ISSUE TITLE
more enhancement in documentation 

### ISSUE THREAD

**Issue by sakshamtaneja21** [erxes/erxes#2082]
take a little time on documentation and add some images as well

**Comment by davidkartuzinski** [comment]
@sakshamtaneja21 Yes yes yes!

I am the new developer advocate at erxes, and the documentation is a top priority.  I just published this comprehensive step by step guide on how to install erxes on your own server.

https://www.erxes.org/installation/ubuntu/

i will be continuing to publish more and more including expanding the user manual. I will be using lots of pictures, when appropriate but look out for long form tutorials in video format.

What do you think I need to document first?  What do you need, right now?

**Comment by sakshamtaneja21** [comment]
Hi 
I think you can start while working on projects 

You can first do documentation and after working we can add picture

**Comment by davidkartuzinski** [comment]
@sakshamtaneja21 

Thank you. I will definitely then continue to focus on the documentation!

I would appreciate if you join the erxes community. Here is the link to join [Join Community Link](https://community.erxes.io/register/Gw4WRJnk9fSbyAXTq)>. Your feedback is helpfu.

When you join the community there are others who can also answer questions and maybe you can also help if you have time and know the answer. We are here to help support the community.

Thanks again, I will be closing this issue.  Feel free to open additional issues or to ask in the chat.
