### ISSUE TITLE
add more UI feature 

### ISSUE THREAD

**Issue by sakshamtaneja21** [erxes/erxes#2083]
the graphics are cool but  add some UI/ UX feature

**Comment by davidkartuzinski** [comment]
@sakshamtaneja21 

Thanks for the compliments! What type of features do you think we should add?

**Comment by sakshamtaneja21** [comment]
basic things
dont have anything specific in mind



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
07/13/20,
10:32:55 AM

**Comment by davidkartuzinski** [comment]
Totally understand. We would love to hear about any ideas and features that you think about specifically in the future. We have a dedicated Feedback form here: https://erxes.io/feedback.

You can also open another issue, or join our chat community here: [Chat community](https://community.erxes.io/register/Gw6WRJnk9fSbyAXTq)

I am going to close this issue, but would love to see what ideas you come up with.
