### ISSUE TITLE
Add deployment method | Google Cloud 

### ISSUE THREAD

**Issue by sakshamtaneja21** [erxes/erxes#2084]
i would like to add a new enhancement i.e add deployment method on Google Cloud

**Comment by davidkartuzinski** [comment]
@sakshamtaneja21 - Thank you for your feedback.

Your should be able to use erxes with Google Cloud.

You can start by create an account, and then following this instructions to to create an instance. 

1. https://cloud.google.com/compute/docs/quickstart-linux 
2. On this step (see picture) make sure to choose **Ubuntu 18.04**

Don't forget to check off HTTPS and HTTP.  

You will need to choose 4cpus and your settings will look  like this:

![Example Settings for Google Cloud with Erxes](https://user-images.githubusercontent.com/29503118/87298656-d4472a80-c50a-11ea-88f8-57a52b45f7bb.png)


3. Follow these instructions to point your domain name to Google Cloud.

4. The instructions for SSL in the Ubuntu installation docs (see below) should work on your server with Google Cloud, if not, maybe these instructions can help you: https://cloud.google.com/appengine/docs/standard/python/securing-custom-domains-with-ssl

4A. Follow these instructions to all SSH from your Terminal. 

https://cloud.google.com/compute/docs/instances/connecting-advanced#thirdpartytools

5. After you do the above, you will be able to install Ubuntu with these instructions. https://www.erxes.org/installation/ubuntu

I didn't complete all the steps as it's a time consuming process. But if you already use Google Cloud, then you should have much of the set-up already completed.

Please let me know if you have any questions.  Would be great if you could confirm the successful installation.
