### ISSUE TITLE
Engage email preview

### ISSUE THREAD

**Issue by Anu-Ujin** [erxes/erxes#2098]
**Is your enhancement request related to a problem? Please describe.**
I think that the Engage tools could use another step at the end that lets users finalize everything, or test it. At least from what I experienced through the onboarding, if I set up a message to send, there is no way to preview it or QC it, your only option is to just "Send" and at that point it's off into the world wide web with it, unless I create contacts for myself, and send to my test segment first before recreating my efforts. 

**Describe the solution you'd like**
Add preview after editing email content

**Comment by indraganzorig** [comment]
This has been implemented.
Closing this issue.
