### ISSUE TITLE
Enhancement in Team Members

### ISSUE THREAD

**Issue by drqasimali** [erxes/erxes#2103]
Are you all facing issue due to less number of team members in Erxes?

I, personally facing issue in my account to allowing only 10 team members to add in my organization. You should allow atleast 50 members in one organization account so that different people can work better.

**Comment by davidkartuzinski** [comment]
@muhammadshahzadUET - Thank you for your comments. 

I totally agree that we should allow more team members.  We do. 

The **open source version** of erxes has **no limits** to the number of team members.

If you are on the **paid version**, each new team member after 10, is **$2 per month**. You can have as many team members as you want at that pricing (purchased 10 at a time), for your organization.

Please let me know if you have any questoins.

Thanks again for your comments.
