### ISSUE TITLE
buttons of settings in profile are not working

### ISSUE THREAD

**Issue by vrashankraom** [erxes/erxes#2114]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [e.g docker, manual]

**Additional context**

**Comment by davidkartuzinski** [comment]
@vrashankraom - Unfortunately, we do not have enough information here to try and fix this issue.  Could you please replace the template below, with all the information we need to track down what is happen. You just need to fill it out. Screenshots are extremely valuable.

Please indicate which buttons are not working and if you're using the Open Source version or the paid version. If you're using the Open Source version please include the operating system and other technical data about your server.

```Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
...

```

**Comment by ganzorig** [comment]
It's already fixed
