### ISSUE TITLE
Animations not found for UI 

### ISSUE THREAD

**Issue by vrashankraom** [erxes/erxes#2115]
**Is your enhancement request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by davidkartuzinski** [comment]
@vrashankraom - Unfortunately, we do not have enough information here .  Could you please replace the template below, with all the information we need to track down what is happen. You just need to fill it out. Screenshots are extremely valuable.

Please tell us what error messages you are getting about the Animations? Include Screen shots if you can and please describe technical environment.

```Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
...

```
