### ISSUE TITLE
Mobile view is not 100% responsive

### ISSUE THREAD

**Issue by vrashankraom** [erxes/erxes#2116]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [e.g docker, manual]

**Additional context**

**Comment by davidkartuzinski** [comment]
@vrashankraom - Thank you for your feedback.  We are aware that erxes is not 100% mobile friendly. Your comment has been noted. 

We are working on this improvement and you should see some releases about this over the next few months.

Again thank you!

Please join us in the chat: https://community.erxes.io/register/Gw6WRJnk9fSbyAXTq - we would love to hear how youre using erxes and if you need any help?

For now I am closing this issue and there is nothing further to be done at this time.
