### ISSUE TITLE
Notify the chat operator via email about missing message in erxes if operator is offline

### ISSUE THREAD

**Issue by karser** [erxes/erxes#2118]
**Is your enhancement request related to a problem? Please describe.**

The chat operator doesn't always keep erxes open. And he often misses the customers inquiries via chat widget.

**Describe the solution you'd like**
It would be great to send a notification by email to the chat operator (to all channel members) about the missing message in erxes.

**Comment by indraganzorig** [comment]
Hey there,

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
This idea has already been copied there as an insight.
Please use this link in the future to submit your features. 

Thank you.

**Comment by davidkartuzinski** [comment]
This issue is related to https://github.com/erxes/erxes/issues/2181. @karser I will ask you to comment on this linked issue. Thank you for your input. This is definitely a key point for anyone using the Chat.
