### ISSUE TITLE
Having copyright information at the site!!

### ISSUE THREAD

**Issue by falguniraina** [erxes/erxes#2123]
![Screenshot from 2020-07-18 20-45-34](https://user-images.githubusercontent.com/48027052/87855712-ab260000-c937-11ea-9eb3-1516bde54c37.png)
It does not has the copyright information

**Comment by indraganzorig** [comment]
Did you mean this one: https://erxes.io/dmca ?

Please create a different issue with valid context and more in-depth description.

Closing this issue until then.
