### ISSUE TITLE
Putting the feedback content inside boxes

### ISSUE THREAD

**Issue by falguniraina** [erxes/erxes#2125]
![Screenshot from 2020-07-18 20-55-34](https://user-images.githubusercontent.com/48027052/87855932-3358d500-c939-11ea-8a08-84f9d18f8ecc.png)

This looks messed up .
Adding these contents in boxes to make it look better

**Comment by ganzorig** [comment]
@falguniraina Thank you for giving us feedback. We are using 3rd party app for showing testimonials. We will fix soon
