### ISSUE TITLE
A deactivated team member should be eliminated from the current TASKS

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#2130]
**To Reproduce**
1. Go to Task and see a team member who is deactivated.

**Expected behavior**
A deactivated team member should be eliminated from everywhere (Task, Sales pipeline, Growth hacking)

**Screenshots**
URL: https://bit.ly/32D4pRm

**Context (please include the related information if applicable):**
 - SaaS

**Comment by batamar** [comment]
@mendorshikh  we can not just hide this user. Maybe we should look as disabled
