### ISSUE TITLE
Editing my own internal note is impossible after filtering a team member

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#2131]
**Describe the bug**
After filtering a team member, I couldn't edit my own internal note. It is unclickable.

**Screenshots**
Video URL: https://bit.ly/2E38QuD

**Context (please include the related information if applicable):**
 - SaaS

**Comment by soyombo-baterdene** [comment]
@mendorshikh I think the video is not relevant

**Comment by munkhorgil** [comment]
Close [579b0bc](https://github.com/erxes/erxes/commit/579b0bca36a9fb4ec24ec54a2e7a1c064a97621d)
