### ISSUE TITLE
Segment's containing lead/customer numbers differently showing on Engage..

### ISSUE THREAD

**Issue by amrakun** [erxes/erxes#2132]
**Describe the bug**
![Screenshot from 2020-07-21 11-29-47](https://user-images.githubusercontent.com/65434827/88009607-87d0a000-cb45-11ea-8cb1-3bdcbb74dba2.png)

**To Reproduce**
1. Go to 'First, Create some segment and include some leads or customer'
2. Click on 'then send Engage to new segment'
3. Scroll down to ''
4. See error - You will see different numbers (it means behind of segments number

)

**Expected behavior**

**Screenshots**
![Screenshot from 2020-07-21 11-29-47](https://user-images.githubusercontent.com/65434827/88009747-cebe9580-cb45-11ea-9ac9-eff0734a4ec6.png)

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [manual]

**Additional context**
nothing.

**Comment by Buyantogtokh** [comment]
@batamar the count shows result from 2 different queries, which are **customerCounts** (at engage form) and **customersMain** (at customers list page).
When I downloaded "office.erxes" db & test it on my machine, it shows different results. (even the counts were different from office.erxes.io after running elksyncer indexing)
But when I completely remove db & all indices and start from fresh database, the count shows correctly.
There seems to be elastic search index issue, the queries working are fine.
