### ISSUE TITLE
E-mail integration: cannot attach image/file. 

### ISSUE THREAD

**Issue by UsuhuuBatbold** [erxes/erxes#2135]
**Describe the bug**
On the e-mail integration, when you try to attach a file, it displays 'Uploading' and nothing happens

**To Reproduce**
1. Go to SAAS Team Inbox
2. Click on Reply to e-mail
3. Attach image/file
4. See error: "Uploading..."

**Expected behavior**
Any file or image is expected to be attached

**Screenshots**
![image](https://user-images.githubusercontent.com/68526193/88018275-fd466b80-cb59-11ea-873a-cc3248ca3d74.png)

**Context (please include the related information if applicable):**
SAAS
Found within Team Inbox, reply to customer, attach JPEG image.

**Additional context**

**Comment by batamar** [comment]
@UsuhuuBatbold It happens when trying to upload a file using deleted nylas account
