### ISSUE TITLE
Duplicate "Website" integration inside SaaS App Store

### ISSUE THREAD

**Issue by indraganzorig** [erxes/erxes#2148]
**Describe the bug**
Website integration is shown twice inside the SaaS AppStore

**To Reproduce**
1. Go to Settings / App Store

**Expected behavior**
Remove one of them

**Screenshots**
[screenshot](https://www.dropbox.com/s/nldmff3n3mw64ot/Screenshot%202020-07-23%2014.19.29.png?dl=0)

**Context (please include the related information if applicable):**
 - erxes version: SaaS

**Comment by batamar** [comment]
@indraganzorig fixed
