### ISSUE TITLE
Code not show on Website

### ISSUE THREAD

**Issue by kang28ivan** [erxes/erxes#2150]
Hello,

I try installing code to my website but not show on website, even though I have followed the documentation on the website https://www.erxes.org/user/script-install#web-messenger--pop-ups-or-knowledgebase

This makes me tired because it has repeatedly not produced results 😅
![Screenshot_4](https://user-images.githubusercontent.com/53988458/88301298-080a2780-cd37-11ea-9947-9ac9e38cb4f5.png)

actually I only need a messenger + knowledge base, is there any other code that has to be applied?

**Comment by batamar** [comment]
Hi @kang28ivan. Can I have some screenshots and browser console messages ?

**Comment by kang28ivan** [comment]
> Hi @kang28ivan. Can I have some screenshots and browser console messages ?

Sorry, I already remove the system 😅 but I try with platform erxes.io also not show code.

Here when I use erxes.io
![Screenshot_2](https://user-images.githubusercontent.com/53988458/88365074-7989ba80-cdb7-11ea-8f1b-506255dc67ae.png)

**Comment by kang28ivan** [comment]
> Hi @kang28ivan. Can I have some screenshots and browser console messages ?

Hi @batamar I already reinstall now, error from console like a screenshot
![Screenshot_2](https://user-images.githubusercontent.com/53988458/88380823-d8f7c280-cdd7-11ea-9e4a-f5ff929b77a9.png)

Is ee on header website Access-Control-Allow-Credentials: true
But I check on nginx config not found about Access-Control-Allow-Credentials, where this setting on admin erxes?

**Comment by davidkartuzinski** [comment]
@kang28ivan - [autooptimize](https://wordpress.org/plugins/autoptimize/) is a great plugin. Have you tried to "exclude from autooptimize"? Sometimes javascript gets screwed up.

**Comment by kang28ivan** [comment]
> @kang28ivan - [autooptimize](https://wordpress.org/plugins/autoptimize/) is a great plugin. Have you tried to "exclude from autooptimize"? Sometimes javascript gets screwed up.

This not only on wordpress, I try in html template with localhost stil same error 
![Screenshot_3](https://user-images.githubusercontent.com/53988458/88383586-5eca3c80-cddd-11ea-87ff-a17473f8833e.png)

this seems to be from the js settings but I don't know which file to look for because I have disabled nginx.conf with add_header 'Access-Control-Allow-Origin' '';

**Comment by kang28ivan** [comment]
To make sure, I also trace javascript address with curl 
![Screenshot_6](https://user-images.githubusercontent.com/53988458/88384380-e2385d80-cdde-11ea-9699-cb09ee5b0f78.png)
Because on main domain already disable Access-Control-Allow-Origin
![Screenshot_2](https://user-images.githubusercontent.com/53988458/88384456-03994980-cddf-11ea-8871-fe061b1b7ddf.png)

Is there a solution to solve this problem?

**Comment by kang28ivan** [comment]
The above problem has been solved.

I have another question, what if I want to move an installation that is already running to another server? Does this have to install like new?
