### ISSUE TITLE
HELP WANTED: Integrate multilanguage chat on membership website

### ISSUE THREAD

**Issue by FrancisSamo** [erxes/erxes#2151]
**NEED HELP** with multilanguage chat on a membership website

### REQUIREMENTS

- Logedin users on _sub.domain.com_ should never have to write their email address & phone number in the chat
- The email address and phone number used in the erxes messenger on _sub.domain.com_ should always use the personal data from the membership website. 
- Depending what language settings a logedin user has, it should load the appropriate erxes messenger in that language (german or english).

### CURRENT STATUS
- The membership website is built on top of [SuiteDash](https://suitedash.com/)
- The erxes platform used for this is not self-hosted, but hosted by [Erxes](https://app.erxes.io/)

I already started developing an integration on SuiteDash with my limited JS skills. As of now SuiteDash doesn't offer the ability to  translate portal pages. But thanks to the [Custom JS feature SuiteDash provides](https://suitedash.com/updates-log/), I could successfully code a multilingual page that recognizes the user language & shows the appropriate language to a logedin user. I then used that custom language condition to determine which erxes chat messenger to integrate. 

**So, what I did in a nutshell:**
1. Defining the email address of the logedin user into the variable "clientEmailAddress"
var clientEmailAddress = $("#sysVarClientEmail em").text();

2. If the user has german language setting --> load erxes in german & add "clientEmailAddress" to erxes settings
if (logoutTxt.toLowerCase().indexOf("ausloggen") >= 0) { ... }

3. (Else) Any other language setting --> load erxes in english & add "clientEmailAddress" to erxes settings
else { ... }

So, that's how I tried to accomplish the requirements **which I need help with**:
```
jQuery(document).ready(function ($) {
    var clientEmailAddress = $("#sysVarClientEmail em").text();

    var logoutTxt = $(".heading-row .functional-btns .btn-wrap a:last-child").text();
    if (logoutTxt.toLowerCase().indexOf("ausloggen") >= 0) {
        console.log("Language Settings: DEUTSCH");
        var curLanguage = "DE";
        $(".lang-section-de").show();
        $(".lang-section-en").hide();

        window.erxesSettings = {
            email: clientEmailAddress,
            messenger: {
                brand_id: "XXXXXX",
                language: "de",
            },
        };

        (function () {
            var script = document.createElement("script");
            script.src = "https://company.app.erxes.io/widgets/build/messengerWidget.bundle.js";
            script.async = true;
            var entry = document.getElementsByTagName("script")[0];
            entry.parentNode.insertBefore(script, entry);
        })();
    } else {
        console.log("Language Settings: ENGLISH");
        var curLanguage = "EN";
        $(".lang-section-en").show();
        $(".lang-section-de").hide();

        var clientEmailAddress = $("#sysVarClientEmail em").text();
        console.log("(EN) Email Address");

        if (clientEmailAddress == null) {
            console.log("Got no Email Address");
            window.erxesSettings = {
                messenger: {
                    brand_id: "XXXXXX",
                    language: "en",
                },
                knowledgeBase: {
                    topic_id: "XXXXXXXXXXXXXXX",
                },
            };
        } else {
            console.log("Got Email Address");
            window.erxesSettings = {
                email: clientEmailAddress,
                messenger: {
                    brand_id: "XXXXXX",
                    language: "en",
                },
                knowledgeBase: {
                    topic_id: "XXXXXXXXXXXXXXX",
                },
            };
        }

        (function () {
            var script = document.createElement("script");
            script.src = "https://company.app.erxes.io/widgets/build/messengerWidget.bundle.js";
            script.async = true;
            var entry = document.getElementsByTagName("script")[0];
            entry.parentNode.insertBefore(script, entry);
        })();

        (function () {
            var script = document.createElement("script");
            script.src = "https://company.app.erxes.io/widgets/build/knowledgebaseWidget.bundle.js";
            script.async = true;
            var entry = document.getElementsByTagName("script")[0];
            entry.parentNode.insertBefore(script, entry);
        })();
    }
});
```

### WHAT WORKS (ALREADY):
- [x] Check & define user settings language into variable "curLanguage"
- [x] Check & define user email address into variable "clientEmailAddress"
- [ ] When user language is german, load erxes settings in german
- [x] When user language is any other language, load erxes settings in english
- [ ] Pass the variable "clientEmailAddress" to erxes

Saddly I somehow can't pass the "clientEmailAddress" to erxes evan though it returns the user email address in the browser console. Now, I'm not an experienced developer but I hope there's someone who can help. Maybe **YOU** can help?! 😳

I NEED HELP **WITH** CODE EXAMPLES 🙏

**Comment by batamar** [comment]
Hi @FrancisSamo 

```
<html>
<body>
    <button id="lang_en">EN</button>
    <button id="lang_mn">MN</button>

    <p>
      <label>Email</label>
      <span id="email">mrbatamar@@yahoo.com</span>
    </p>

    <p>
      <label>Phone</label>
      <span id="phone">97696221050</span>
    </p>

    <p>
      <label>Language</label>
      <span id="lang"></span>
    </p>

    <script>
      document.addEventListener('DOMContentLoaded', function(event) {
        document.getElementById('lang').innerText = localStorage.getItem('language') || 'en';

        document.getElementById('lang_en').addEventListener('click', () => {
          localStorage.setItem('language', 'en');
          location.reload();
        });

        document.getElementById('lang_mn').addEventListener('click', () => {
          localStorage.setItem('language', 'mn');
          location.reload();
        });

        window.erxesSettings = {
          messenger: {
            brand_id: "KK3cJ7",
            language: document.getElementById('lang').innerText,
            email: document.getElementById('email').innerText,
            phone: document.getElementById('phone').innerText,
          },
        };
        
        (function() {
          var script = document.createElement('script');
          script.src = "http://localhost:3200/build/messengerWidget.bundle.js";
          script.async = true;
          var entry = document.getElementsByTagName('script')[0];
          entry.parentNode.insertBefore(script, entry);
        })();
      })
  
    </script>
</body>
</html>
```

Here is the working example made for you

**Comment by FrancisSamo** [comment]
@batamar **Thank you very much!** So, I have to set the email variable into "messenger" and not into "erxesSettings" as I did before. 🤦‍♂️ This makes totally sense! Thanks alot for your help. Really appreciate it! 🙏

**Та бүхэнд энэ долоо хоногт сайн сайхан бүхнийг хүсье!** (* Google Translate 😳)
