### ISSUE TITLE
Online Hours Schedule Not Working?

### ISSUE THREAD

**Issue by kang28ivan** [erxes/erxes#2152]
Hello,

I have successfully installed erxes and it works fine I like this software 🤩, but in the messenger settings and online hours schedule does not work, ex I set everyday with hour from 8:00 AM (_08:00_) to 10:00 PM (_22:00_) 
![Screenshot_2](https://user-images.githubusercontent.com/53988458/88460749-0e340b80-ced1-11ea-957e-5515ba10a4fc.png)
but the widget appears round green icon (_online_), even though it should be offline because it has passed working hours
![Screenshot_3](https://user-images.githubusercontent.com/53988458/88460757-1c822780-ced1-11ea-9dbe-45a7c4cb204f.png)

how to correctly set up online hour scheduling?

Thank you in advance for being kind 🙏

**Comment by Buyantogtokh** [comment]
@kang28ivan are you still experiencing this?

**Comment by kang28ivan** [comment]
> @kang28ivan are you still experiencing this?

Yes, still 😅
And no sound notification when incoming chat from client

**Comment by Buyantogtokh** [comment]
> > @kang28ivan are you still experiencing this?
> 
> Yes, still 😅
> And no sound notification when incoming chat from client also when agent reply (visitor end)

@kang28ivan can you share your screen? Cuz when I test it from Mongolia, it is working fine.

**Comment by kang28ivan** [comment]
> > > @kang28ivan are you still experiencing this?
> > 
> > 
> > Yes, still 😅
> > And no sound notification when incoming chat from client also when agent reply (visitor end)
> 
> @kang28ivan can you share your screen? Cuz when I test it from Mongolia, it is working fine.

Ok I'll screenshot later, i'm still out of the house 🙏

**Comment by kang28ivan** [comment]
Hi @Buyantogtokh 
Here when I set from 8:00 AM (08:00) to 10:00 PM (22:00)
![Screenshot_2](https://user-images.githubusercontent.com/53988458/88799018-6b350780-d1d8-11ea-86db-8b83e54ea059.png)
On widget
![Screenshot_6](https://user-images.githubusercontent.com/53988458/88800861-63c32d80-d1db-11ea-81a2-1975a1acc261.png)

Still not working and I try update to 0.16.0 from 0.15.5
but error occurred while working on https widget does not appear on the website

`messenger.bundle.js:1 Mixed Content: The page at 'https://mydomain.com/widgets/messenger' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://mydomain.com/api/subscriptions'. This request has been blocked; this endpoint must be available over WSS.`
![Screenshot_4](https://user-images.githubusercontent.com/53988458/88800099-31fd9700-d1da-11ea-8fa5-a15d7f60e5d8.png)
Though there are no settings whatsoever, it's just that the socket doesn't work on https/wss, if on non-https its working 😅
I plan to reinstall

**Comment by kang28ivan** [comment]
Update!
It seems that this is correct now after reinstalling with 0.16.0, also set timezone to Asia/Hong_Kong and reboot server.
But for the notification sound still silent when it comes chat from new client chat or when I reply to a client, there is no notification sound.

**Comment by Buyantogtokh** [comment]
@kang28ivan we've discovered and fixed this bug. Please check out the latest version.
