### ISSUE TITLE
Can't delete leads

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#2161]
Deleted Lead is in the LEAD LIST which should be deleted too  
Video: <https://bit.ly/2E38QuD>

**Comment by mendorshikh** [comment]
Link to feature: https://erxes.productboard.com/feature-board/planning/features/5190736

**Comment by batamar** [comment]
@mendorshikh @soyombo-baterdene checked it. It seems working fine. Feel free to reopen
