### ISSUE TITLE
Add more social links to Constants

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#2163]
- Slack

- Rocketchat

- Whatsapp

- WeChat

- LINE

- QQ

- Skype

- QZone

- Viber

- Snapchat

- Telegram

- Foursquare

- TikTok

- Review

**Comment by mendorshikh** [comment]
Link to feature: https://erxes.productboard.com/feature-board/planning/features/5190666

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.

**Comment by davidkartuzinski** [comment]
This is being closed as not needed at this time. It was automatically generated by ProductBoard where we are planning and tracking upcoming releases.
