### ISSUE TITLE
Changing the color of Download Template to green and leave the rest to blue

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#2165]

**Comment by mendorshikh** [comment]
Link to subfeature: https://erxes.productboard.com/feature-board/planning/features/5179859

**Comment by Mambatukaa** [comment]
Hey there,
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.

**Comment by piyush9311** [comment]
I wanna work on this issue
