### ISSUE TITLE
[Feature Request] Screen Sharing

### ISSUE THREAD

**Issue by joepa37** [erxes/erxes#2190]
Screen Sharing for support teams and customers on desktop explorer browsers.

**Comment by davidkartuzinski** [comment]
@joepa37 

Thank you very much for your request.  Could you describe the exact use case? That would help as we consider the implementation of a new feature or integration that does this.

For example, would the agent already be on the phone with the person? Just chatting? Would it be similar to the Microsoft Customer service sharing link or act more like teamviewer? How do you see this working? How would you like to see this work? 

Screen sharing can be tricky, and it would be great to get your use case!
