### ISSUE TITLE
Custom email appearanse - not allow modification

### ISSUE THREAD

**Issue by ViabGit** [erxes/erxes#2195]
**Describe the bug**
It does not allow to modify texts

**To Reproduce**
1. Go to 'settings'
2. Click on 'email appearanse'
3. Click on  'Custom
4. Click on 'image propperies'
5. does not allow modification

**Expected behavior**
be able to modify the link

**Screenshots**
![image](https://user-images.githubusercontent.com/26825353/89369709-51526380-d6b5-11ea-9eeb-035a9ff9ad70.png)

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser version [Versión 84.0.4147.105 (Build oficial) (64 bits)]
 - erxes version [0.16.0]
 - installation type [ubuntu manual]

**Comment by davidkartuzinski** [comment]
@ViabGit - Did you try to click the lock? Are you referring to the Alt Text? or the image sizes? Please add a little bit more information about which text you're trying to edit? (Otherwise, thank you for a very nice issue submit! )

**Comment by ViabGit** [comment]
[https://youtu.be/tJVq5Wkj9VM](url)

**Comment by davidkartuzinski** [comment]
@ganzorig - This looks like a bug.

@ViabGit Thank you for the video.  That makes things clear.
