### ISSUE TITLE
How to add/change Mail Service providers?

### ISSUE THREAD

**Issue by uhlhosting** [erxes/erxes#2202]
**Describe the bug**
Integrating with custom mail server fails with Postal/Cpanel

**To Reproduce**
1. Go to Settings > Custom mail service
<img width="626" alt="image" src="https://user-images.githubusercontent.com/6324047/89631299-e5345300-d8a0-11ea-918d-e76e81190463.png">
2. Click on 'Custom mail service'
3. Scroll down to 'input settings form'

**Expected behavior**
A connection to my mail server and a way to test it via send message and to validate my mail.

**Screenshots**
<img width="610" alt="image" src="https://user-images.githubusercontent.com/6324047/89631483-1e6cc300-d8a1-11ea-9ffd-de1986164dc3.png">
<img width="596" alt="image" src="https://user-images.githubusercontent.com/6324047/89631522-2dec0c00-d8a1-11ea-9925-b359c27b129d.png">

**Context (please include the related information if applicable):**
 - OS: [Ubuntu 18.04]
 - Browser version [Safari 14.0, Chrome 86.0.4217.2]
 - erxes version [e.g. 0.16.0]
 - installation type [deploy script provided]

**Additional context**
There is a certain confusion on the usage and integration with mail providers, here we try to move away from providers like Gmail in favour of Open Source solutions and so we discovered Postal, it can do SMTP auth, API auth, much more Sendgrid can to, so can Postal. We also run a Zimbra mail solution, and the default one provided by Cpanel/WHM for web hosters. I have tested postal SMTP server and WHM/Cpanel at the moment, nothing worked as a custom mail service. Any help would be gratefull on setting up own mail service.

**Comment by davidkartuzinski** [comment]
@batamar - Can you please ask the correct person to help on this issue? @uhlhosting will need some basic instructions on how to do the Postal and/or Zimbra integration if it is at all possible. 

Postal:
https://postal.atech.media/
https://github.com/postalhq/postal

Zimbra:
https://www.zimbra.com/
https://github.com/Zimbra

Zimbra looks better maintained to me than Postal.

**Comment by uhlhosting** [comment]
> @batamar - Can you please ask the correct person to help on this issue? @uhlhosting will need some basic instructions on how to do the Postal and/or Zimbra integration if it is at all possible. 
> 
> 
> 
> Postal:
> 
> https://postal.atech.media/
> 
> https://github.com/postalhq/postal
> 
> 
> 
> Zimbra:
> 
> https://www.zimbra.com/
> 
> https://github.com/Zimbra
> 
> 
> 
> Zimbra looks better maintained to me than Postal. 
> 
> 
> 
> 

Zimbra its also a super solution for people who look exchange alternatives. 

On the other side Postal its for huge ammount of emails to send track and route. They are kinda two different solutions. 

See zimbra as office365/exchange alternative,

While postal its more a mailgun/sendgrid/aws ses alternative.

**Comment by uhlhosting** [comment]
The good part about postal, is that it has transactional API for sending mails. And their API is very simple!

[https://krystal.github.io/postal-api/](url)

**Comment by davidkartuzinski** [comment]
@batamar - Who should be looking at this?

**Comment by uhlhosting** [comment]
Would be more than happy to provide an account on our Postal instance for testing if needed.
