### ISSUE TITLE
Daily Video calls missing https:// cause errors

### ISSUE THREAD

**Issue by uhlhosting** [erxes/erxes#2203]
**Describe the bug**
Trying to get Daily.co integration to work. Made the account, activated API and made the team:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/6324047/89646994-17ec4480-d8bd-11ea-8493-9a27895e0b5c.png">

**To Reproduce**
1. Go to 'Chat on website'
2. Click on 'Video/Audio Call from messenger'
3. Go back to App dashboard 'there will be visible the request made'
4. See error only after the video button is used.

Call sent from Messenger:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/6324047/89647127-5124b480-d8bd-11ea-99d2-7b339319ab34.png">

Call received on App:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/6324047/89647164-626dc100-d8bd-11ea-8eb8-594064d624d7.png">

I tried to add directly Daily.co room, or just the team nothing helped, this is error for using team as requested in the official documentation:
<img width="605" alt="daily-vid" src="https://user-images.githubusercontent.com/6324047/89647338-b7113c00-d8bd-11ea-8eba-1b4ccd0fa91a.png">

And it will return:
  Error: Invalid URI "ecunative.daily.co/api/v1/rooms"

**Expected behavior**
Make use of video calls via daily

**Screenshots**

**Context (please include the related information if applicable):**
OS: [Ubuntu 18.04]
Browser version [Safari 14.0, Chrome 86.0.4217.2]
erxes version [e.g. 0.16.0]
installation type [deploy script provided]

**Additional context**
The issue is fixed if one uses the FQDN includig https:// it seems to do the trick in my case. without https:// will result in above errors.

**https://ecunative.daily.co** in my case is the right config.

<img width="223" alt="image" src="https://user-images.githubusercontent.com/6324047/89647676-33a41a80-d8be-11ea-9ff3-f94a90b19392.png">
Ignore the above image the ending / is not needed.
After some time there are blacking out the screens, maybe this is related to safari only, i will check this now that it works at least.

**Comment by davidkartuzinski** [comment]
@uhlhosting - Can you confirm that this is a Safari only bug? And did you try clearing the cache on Safari?

**Comment by uhlhosting** [comment]
> @uhlhosting - Can you confirm that this is a Safari only bug? And did you try clearing the cache on Safari?

@davidkartuzinski this seems to be mostly caused by missconfigured entry in END POINT, the documentation shows to enter FQDN without http:// or https:// doing so will fail on every browser.

**Comment by davidkartuzinski** [comment]
This was fixed with: https://github.com/erxes/erxes/commit/983920d1e65bb2e215b1a1f140559698fad7eaca.

Thank you @uhlhosting
