### ISSUE TITLE
Messenger supporter custom icons broken

### ISSUE THREAD

**Issue by uhlhosting** [erxes/erxes#2204]
**Describe the bug**
Icons displayed as broken in Safari 14.0

**To Reproduce**
1. Go to 'Messenger'
2. Click on 'Greetings > Supporters'
3. Add the name of the suporters. 

**Expected behavior**
See normal icons

**Screenshots**
<img width="692" alt="image" src="https://user-images.githubusercontent.com/6324047/89651041-977d1200-d8c3-11ea-81ac-a2c6954a0d56.png">

**Context (please include the related information if applicable):**
- OS: [Ubuntu 18.04]
- Browser version [Safari 14.0, Chrome 86.0.4217.2]
- erxes version [e.g. 0.16.0]
- installation type [deploy script provided]

**Additional context**

**Comment by davidkartuzinski** [comment]
@uhlhosting Thank you for your issue!

**Comment by uhlhosting** [comment]
It seems the icons are broken accross whole services, from email template:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/6324047/89741511-335c7880-da92-11ea-8ea0-76fe975225f4.png">

To the user area replies.

**Comment by davidkartuzinski** [comment]
@Enkhtuvshin0513 - Are you aware of this?

**Comment by batamar** [comment]
@uhlhosting Fixed in https://github.com/erxes/erxes/commit/352ea74df78b402c7b4520322ed62f995fd3549b
