### ISSUE TITLE
Native Gmail Integration Not Syncing [Successfully Configured]

### ISSUE THREAD

**Issue by RileySeaburg** [erxes/erxes#2207]
**Describe the bug**
The native gmail integration, not the Nylas one does not synchronize the gmail inboxes even after a successful gmail integration is configured.  

**To Reproduce**
1. Install Erxes
2. Create Gmail API Key
3. Add key to erxes
4. Add user email to Gmail integration on erxes
5. Get successful save in green box.
6. Sent test email from another account.
7. Verify in Gmail that test email was recieved.
8. Check erxes channel/ integration for email.
Nothing there.

**Expected behavior**
Email should appear here.

**Screenshots**
![no email](https://user-images.githubusercontent.com/48305658/89777693-295e6800-dada-11ea-96eb-5d4f788f30ce.png)

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser version [e.g. chrome]
 - erxes version [e.g. 0.16.0]
 - installation type [manual]

**Comment by davidkartuzinski** [comment]
@munkhorgil - Could you please let us know if this will be fixed in the next release for Friday 14 Aug or the next release? Thank you!

**Comment by RileySeaburg** [comment]
I should have put this under erxes-integrations right?

**Comment by davidkartuzinski** [comment]
> I should have put this under erxes-integrations right?

I don't think you can actually. I think only people in erxes can! But if you keep helping people in the community maybe we will have to give you the rights to participate more in the issues as well! ;)

**Comment by munkhorgil** [comment]
> @munkhorgil - Could you please let us know if this will be fixed in the next release for Friday 14 Aug or the next release? Thank you!

I will work on that

**Comment by sageirie** [comment]
you can remote pc
