### ISSUE TITLE
Issues with IMAP mails import in dashboard

### ISSUE THREAD

**Issue by uhlhosting** [erxes/erxes#2208]
**Describe the bug**
I am trying to make use of the helpdesk feature to have the emails sent to a certain mailbox imported into the dashboard where messennger messages are also visible.

**To Reproduce**
1. I went to settings > Nylas integration added the API and saved.
2. After that I clicked on IMAP by nylas
3. Added the server details imap/smtp details.
4. There are no emails imported in the system.

**Expected behavior**
I would expect to have the mailbox monitored in dashboard.

**Screenshots**
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/6324047/89783749-bf64b380-db17-11ea-9ac6-bf79859612ed.png">
<img width="557" alt="image" src="https://user-images.githubusercontent.com/6324047/89783780-cf7c9300-db17-11ea-9817-0446523c9dee.png">

**Context (please include the related information if applicable):**
- OS: [Ubuntu 18.04]
- Browser version [Safari 14.0, Chrome 86.0.4217.2]
- erxes version [e.g. 0.16.0]
- installation type [deploy script provided]

**Additional context**
Here is a raw log of email header sent from the dashboard:

```
Envelope-To: kosmos@highacid.com
X-Uhlhosting-Mailscanner: Found to be clean
User-Agent: Nylas-uhlhost.net/18.1.0
Return-Path: <helpdesk@ecunative.eu>
Return-Path: <helpdesk@ecunative.eu>
Mime-Version: 1.0
X-Uhlhosting-Mailscanner-Spamcheck: not spam, SpamAssassin (not cached, score=1.483, required 4, HTML_MESSAGE 0.00, TVD_SPACE_RATIO 0.00, TVD_SPACE_RATIO_MINFP 1.48)
X-Inbox-Id: c2tjdpv86lfcwim5emnhzqdgi-0
X-Uhlhosting-Mailscanner-Spamscore: s
**<c2tjdpv86lfcwim5emnhzqdgi-0@mailer.nylas.com>**
```

On nylas side I see only this:

```
Mon, Aug 10, 2020 3:01 PM CEST
No UIDs found for message
NO DATA
warning
97y94hgyso9e088ymx1vaaxu3
```

I have also contacted them to see what is this about. Meanwhile I will give it a try to a second server I have running another software.

The only issue with this is that when the user replies there is nothing returned to the system, yet there is emails received in the mailbox.

My suggestion would be to allow users to make direct imap integrations without a 3rd party since this is also a security reason and offers more control. Why would me as a services provider not be able to use own innfrastructure and to be forced to go to a paid 3rd party service.

Since IMAP / POP3/SMTP are new services are quite known in all languages and have support to be integrated without 3rd party.

Now for us here is very dificult to debug and trace the issue of this, since this would require much more to be legit emails, SPF records, DKIM and these received no instructions from nylas side nor erxes. 

I have control over my domains DNS records yet not over mailer.nylas.com domain. So checking why nylas does not put the emails from my mailbox, yet uses it just to send.

**Comment by davidkartuzinski** [comment]
@uhlhosting This turns out to be expected behavior. From my understanding this has been designed to only bring in new emails. @munkhorgil can confirm? 

@Enkhtuvshin0513 - Can emails be imported using the import/export?

**Comment by uhlhosting** [comment]
> @uhlhosting This turns out to be expected behavior. From my understanding this has been designed to only bring in new emails. @munkhorgil can confirm? 
> 
> 
> 
> @Enkhtuvshin0513 - Can emails be imported using the import/export?

The issue here is that no emails are adeed in. Not new not replies not old. 

See this scenario. I email someone from helpdesk@ he will reply to the mail and therefor i expect to see his reply in erxes not outside. Since main email is sent from there.

**Comment by davidkartuzinski** [comment]
@uhlhosting - yes. Your use case should work but it isn't. We are addressing this.  I was asking about import/export because it's related to this issue and this feature.
