### ISSUE TITLE
Engages API Not Accessible

### ISSUE THREAD

**Issue by RileySeaburg** [erxes/erxes#2215]
**Describe the bug**
The engages API is not accessible. 
When trying to update engages config setting a NGINX 405 Error appears

**To Reproduce**
1. Follow ubuntu detailed installation[ here ](https://www.erxes.org/installation/ubuntu/)
2. Log into Erxes
3. Open Settings & click on engages config
4. Add in Mail settings
5. Click save
6. See error

**Expected behavior**
Save engages config settings and send test email

**Screenshots**
![Engages Config](https://user-images.githubusercontent.com/48305658/89964800-17cfaa00-dc19-11ea-98af-1277d92b01ba.png)

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.16.0]
 - installation type [manual]

**Comment by davidkartuzinski** [comment]
@batamar - Not sure who should take care of this.

**Comment by batamar** [comment]
@RileySeaburg . Can i see the nginx config and pm2 list output ?

**Comment by RileySeaburg** [comment]
> @RileySeaburg . Can i see the nginx config and pm2 list output ?

I'm no longer actively maintaining this project.
