### ISSUE TITLE
Scripts created do not work on Wordpress sites.

### ISSUE THREAD

**Issue by uhlhosting** [erxes/erxes#2223]
**Describe the bug**
Using scripts in Wordpress is not working.

**To Reproduce**
1. Go to 'Settings > Scripts'
2. Click on 'New script'
3. Scroll down to 'Scripts > Copy the code to paste on website'
4. See error, nothing happends.

**Expected behavior**
```
<script>
  (function() {
    var script = document.createElement('script');
    script.src = "https://crm.uhlhosting.ch/widgets/build/manager.bundle.js?id=nQ3TJt2HJb4yvBcTb&apiUrl=https://crm.uhlhosting.ch/api";
    script.async = true;
    var entry = document.getElementsByTagName('script')[0];
    entry.parentNode.insertBefore(script, entry);
  })();
</script>
```
The code should allow users to get access quickly to messenger kb and this is simply conflicting while nothing works in reality.

**Screenshots**

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [e.g docker, manual]

**Additional context**

**Comment by davidkartuzinski** [comment]
@uhlhosting - Hi. People are getting it to work in WordPress. Where are you pasting the scripts?

**Comment by batamar** [comment]
@uhlhosting Please send the screenshot of browser console log messages?

**Comment by uhlhosting** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/6324047/90388564-4a99f800-e088-11ea-92e4-9d3c032389e2.png">

**Comment by uhlhosting** [comment]
@batamar how can I use that patch in my setup? Is there a way to upgrade to this patch?
