### ISSUE TITLE
There is a break markdown in the README

### ISSUE THREAD

**Issue by atharwa-24** [erxes/erxes#2227]
**Describe the bug**
The bettercode Badge code is broken 
it is appearing as a link out there

**To Reproduce**
1. Go to 'README.md'
2. Click on 'Bettercode'
3. Fix the Line
![issue](https://user-images.githubusercontent.com/54115798/90431720-199ce000-e0e7-11ea-990a-f9fae7a33fb5.PNG)

**Expected behavior**

**Screenshots**

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [e.g docker, manual]

**Additional context**

**Comment by davidkartuzinski** [comment]
@atharwa-24 - Thank you for your issue. I was **not** able to reproduce this issue. I tested the Readme in firefox, safari, chrome and microsoft. (On a mac). I checked also in Private Mode on each of these browsers.

I also checked on my mobile phone browsers.

Bettercode image is appearing in each of these browsers. Sometimes there is a little loading lag.

Could you please tell us your browser and and O/S?

**Comment by atharwa-24** [comment]
its seems fixed now!!!
I guess it would be a loading lag
@davidkartuzinski

**Comment by atharwa-24** [comment]
windows 8.1 
Mozilla Firefox
