### ISSUE TITLE
Minify and serve compressed JS ressources! SEO Factor

### ISSUE THREAD

**Issue by uhlhosting** [erxes/erxes#2234]
**Is your enhancement request related to a problem? Please describe.**
Enable compression for the following resources to reduce their transfer size by 774.9KiB (73% reduction).

```
Compressing https://crm.uhlhosting.ch/widgets/build/messenger.bundle.js could save 602.9KiB (73% reduction).
Compressing https://crm.uhlhosting.ch/widgets/build/messengerWidget.bundle.js could save 171.1KiB (74% reduction).
Compressing https://crm.uhlhosting.ch/api/read-file?key=0.6563244851882237user-headset.svg could save 488B (48% reduction).
Compressing https://crm.uhlhosting.ch/api/graphql could save 443B (39% reduction).
Compressing https://geo.erxes.io/ could save 27B (13% reduction).
```
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/6324047/90629956-7c45c700-e220-11ea-9032-517538aa3672.png">

**Describe the solution you'd like**
Serve minified JS to enduser integrations.

**Additional context**
https://gtmetrix.com/compare/Dytefq90/2pvJndsb See this report, with and without Erxes JS.

**Comment by davidkartuzinski** [comment]
@ganzorig - could you look at this?

**Comment by uhlhosting** [comment]
This is a website without integration: https://gtmetrix.com/reports/uhl.site/eREAkpmF ![Clipboard - September 1, 2020 8_45 AM](https://user-images.githubusercontent.com/6324047/91811562-fbc79300-ec2f-11ea-8e73-193c8d5bad0b.png)

Here is after: https://gtmetrix.com/reports/uhl.site/BZJQsfQ9 ![Clipboard - September 1, 2020 8_46 AM](https://user-images.githubusercontent.com/6324047/91811554-f9653900-ec2f-11ea-913e-76b60c13d290.png)

**Comment by davidkartuzinski** [comment]
@uhlhosting - I know we're looking into this.
