### ISSUE TITLE
Typo error in README.md

### ISSUE THREAD

**Issue by onkar-shaligram** [erxes/erxes#2255]
**Description of the bug**
Typo errors in README.md... All the spellings with 'Erxes' should be changed to 'erxes' as it is not matching the organization's name.

**To Reproduce**
1. Go to 'README.md'
2. Click on 'readme.md'
3. Scroll down to 'find the typo'
4. Do the required changes

**Comment by davidkartuzinski** [comment]
This issue can now be closed.
