### ISSUE TITLE
Some texts are not translated

### ISSUE THREAD

**Issue by soyombo-baterdene** [erxes/erxes#2272]
**Is your enhancement request related to a problem? Please describe.**
When I changed the language in the settings menu, it doesn't change some of the texts.

**Describe the solution you'd like**
Add missing translations.

**Additional context**
![Screen Shot 2020-09-03 at 12 36 10 PM](https://user-images.githubusercontent.com/40427263/92071737-1d687c00-ede2-11ea-8e0c-5c1e1b67d9ab.png)

**Comment by satishkollu** [comment]
Hey, I would love to work on this. Please assign me this.
