### ISSUE TITLE
Overlapping description text

### ISSUE THREAD

**Issue by ganzorig** [erxes/erxes#2295]
![description](https://lh3.googleusercontent.com/aN3kk2MtpF9O_-ovelp9d6B30yvcLvRvMQabwuXFEy9F7qgqwMk-TAuwtTHx4Q8LEkuCmXt_w-vwQmY9AdaldW9d8f0Wey83s7xeBtsLTAyMRwgjBo1sGv1fOJeRq4LBpw07aY8v)

**Comment by chrysillala** [comment]
Hi, I would love to work on this issue. Could you please assign this and guide me? Thank you.
