### ISSUE TITLE
Add "Awaiting Response" Status in the Conversations
Add "Awaiting Response" Status in the Conversations

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#2314]
**The problem**  
It's hard to filter conversations by the last responder. Users need to easily find the pending conversations where the last responder is the customer. When you start receiving a significant amount of messages in one channel, it would be hard to quickly find the ones that need a response.

**The solution**

- Add "Awaiting Response" filter which filters conversations by the last responder, when the last person who sent a message is the customer

![Screen Shot 2020-09-23 at 5 39 02 PM](https://user-images.githubusercontent.com/53030705/93996064-5c2b9980-fdc4-11ea-8745-4ec808926b08.png)

<p></p>

**Comment by mendorshikh** [comment]
Link to feature: https://erxes.productboard.com/feature-board/planning/features/5579127

**Comment by indraganzorig** [comment]
Hi @mungunshagai, 
The filter doesn't seem to work if the last interaction was this:
![Screen Shot 2020-10-06 at 12 13 11 PM](https://user-images.githubusercontent.com/53030705/95158123-69398700-07cd-11eb-8aef-902e9346c1b2.png)
