### ISSUE TITLE
Update files on Transifex

### ISSUE THREAD

**Issue by saikhangombo** [erxes/erxes#2319]
**Is your enhancement request related to a problem? Please describe.**
Some of the new improvements are not available as strings on Transifex.

**Comment by sparkingdark** [comment]
Is this still open want to work.
Please give me some more information.

**Comment by indraganzorig** [comment]
Please do @sparkingdark!
Context: We use [Transifex](https://www.transifex.com/erxes-inc/public/) to crowdsource our translations. Once a new feature is rolled out those texts are not added to it. 

So this task is to update the available strings of the resource file on Transifex.

@batamar can provide more technical info, if necessary.

**Comment by sparkingdark** [comment]
Thank you I will start the task within few days as already have some other issues to fix

**Comment by sparkingdark** [comment]
@batamar can you give some more context about it like from which part of the project I can start and any specific instructions to do this.

**Comment by daniel-shuy** [comment]
This task is too broad and vague. It would be great if someone could list down the features/improvements that are untranslated.
