### ISSUE TITLE
Broken links in README.md (Documentation section)

### ISSUE THREAD

**Issue by daniloff200** [erxes/erxes#2352]
**Describe the bug**
Looks like, some links in README.md, related to Documentation section are outdated.
**Install erxes** points to https://docs.erxes.io/installation/docker
**erxes documentation** points to https://docs.erxes.io/
**Contributing to erxes** points to https://docs.erxes.io/developer/contributing

But, all of them just redirect me to https://www.erxes.org/, because, looks like,  https://docs.erxes.io right now doesn't work

I think, that should be updated.
**Install erxes** should redirect to https://www.erxes.org/installation/docker
**erxes documentation** can point to https://www.erxes.org/overview/getting-started/ (maybe, somewhere else)
**Contributing to erxes**  should point to https://www.erxes.org/developer/developer or https://www.erxes.org/developer/contributing

**To Reproduce**
1. Go to Readme section of the repo
2. Click on links in Documentation section

**Expected behavior**
You should see a required links, not the main page of https://www.erxes.org/

**Comment by daniloff200** [comment]
I would like to work on that, as soon, as proper links will be described / discussed :)

**Comment by davidkartuzinski** [comment]
This is a good issue.  Some of these links have been fixed.  Let's review this after the next merge from Develop to Master next week. Thank you @daniloff200.

**Comment by simarpreetsingh-019** [comment]
I would like to work on this issue.

**Comment by daniloff200** [comment]
@simarpreetsingh-019  I don't think, that's possible, this one was already assigned to me

**Comment by CoderSaty** [comment]
@daniloff200 please assign this task to me as I am very new to open source and it will be a great acheivement for me to make my pull request merged in such a repository. Please sir, it's a kind request. Thanks

**Comment by daniloff200** [comment]
I saw that merge to master was 2 days ago
Is this task ready for check right now @davidkartuzinski  ?

**Comment by davidkartuzinski** [comment]
@daniloff200 @CoderSaty - The broken links seem to have been fixed by another Pull Request.  @CoderSaty - I am afraid I didn't fully understand your request. I expect you will have many more opportunities to contribute in a meaningful way to open source projects.  Good luck.

**Comment by daniloff200** [comment]
Which was made day after I opened this issue
https://github.com/erxes/erxes/pull/2354

Haha
As usual, it's better to run and create a PR, as fast, as you can, then ask, is it really a necessary change, or not?
Not surprised
