### ISSUE TITLE
Email attribute is not working. 

### ISSUE THREAD

**Issue by saikhangombo** [erxes/erxes#2367]
Email attribute is not working. Customer name missing. 
![bug  report](https://user-images.githubusercontent.com/71864142/95056779-c975ed80-0727-11eb-9b77-7e12c9ce819e.jpg)

**Comment by BhuwanChandra** [comment]
can I work on this issue?

**Comment by batamar** [comment]
HI @BhuwanChandra. Sure

**Comment by BhuwanChandra** [comment]
@batamar @saikhangombo can you please tell me how to reproduce the bug?

**Comment by indraganzorig** [comment]
> @batamar @saikhangombo can you please tell me how to reproduce the bug?

Hi @BhuwanChandra, to reproduce:

- Create a test contact with your email address by going to Contact and click "Add customer"
![Screen Shot 2020-10-07 at 12 41 35 PM](https://user-images.githubusercontent.com/53030705/95288348-a61f7f80-089a-11eb-8632-9fa82e2efdf0.png)
- Go to Settings / Email Template
- Click on "New Template"
- Click on "Attributes" to use it in the text editor
![Screen Shot 2020-10-07 at 12 34 17 PM](https://user-images.githubusercontent.com/53030705/95287842-88054f80-0899-11eb-8cfa-daf06635cef7.png)
- Save the template
- Go to your test contact profile and click on "Send email"
![Screen Shot 2020-10-07 at 12 36 20 PM](https://user-images.githubusercontent.com/53030705/95288013-f77b3f00-0899-11eb-9c85-d1117f803ce9.png)
- Select the email template you've created before
- Send the email
- Check your inbox

Hope this helps!
