### ISSUE TITLE
Link of contribute broken in Readme.md

### ISSUE THREAD

**Issue by code-of-kira** [erxes/erxes#2369]
The link of open collective for contribution which is readme docs is broken and lead to not found of github which need to be corrected.It lead to this link "https://github.com/erxes/erxes/blob/master/graphs/contributors". when clicked.
![Capture](https://user-images.githubusercontent.com/61110783/95101527-de667700-074f-11eb-9057-44c82eb254fa.PNG)

**Comment by Ameenrehman** [comment]
Hello  @code-of-kira  what link you want inplace of that mislead link.
can you please tell me more on this,I want to work on this issue.
thanks
