### ISSUE TITLE
Add send an email button

### ISSUE THREAD

**Issue by munkhorgil** [erxes/erxes#2374]
**Is your enhancement request related to a problem? Please describe.**
Users can only send an email to customers.

**Describe the solution you'd like**
Add send email button in settings

**Additional context**
<img width="1440" alt="Screen Shot 2020-10-07 at 11 48 32 am" src="https://user-images.githubusercontent.com/978987/95285317-15917100-0893-11eb-9219-c03e35261f75.png">

**Comment by lakshayb121** [comment]
Hey i would love to work on this. Please assign me this.

**Comment by satishkollu** [comment]
Hey I would love to work on this. can you please assign it
