### ISSUE TITLE
Grammar Errors in Docs

### ISSUE THREAD

**Issue by rutujak24** [erxes/erxes#2399]
**Is your enhancement request related to a problem? Please describe.**
There are grammatical errors in the document, which may make a wrong impression on the readers.

**Describe the solution you'd like**
I would like to correct them

**Comment by CoderSaty** [comment]
Will you please describe it? I would like to correct them.

**Comment by davidkartuzinski** [comment]
@rutujak24 - Please be specific. If you are going to correct one letter or add a capital letter (erxes, for example, has no capital letter), then don't bother. We can reopen this issue with more specific information.
