### ISSUE TITLE
Link to docs in README.md is broken

### ISSUE THREAD

**Issue by daniloff200** [erxes/erxes#2414]
**Describe the bug**
The link which should point to docs start page points to not existed page

Kind a related to https://github.com/erxes/erxes/issues/2352 update, which was made before

**To Reproduce**
1. Go to readme section
2. Click on erxes documentation link
3. You will be redirected to https://www.erxes.org/overview/getting-started/ and see this
![Selection_109](https://user-images.githubusercontent.com/13692220/96753960-4a481100-13d9-11eb-9dca-2c73d20bb2c8.png)

**Expected behavior**
You should able to start work with docs

**Comment by Vinamra2009** [comment]
I can fix this
