### ISSUE TITLE
Unable to Integrate

### ISSUE THREAD

**Issue by azharumar** [erxes/erxes#2434]
First I would like to appreciate the efforts in putting together a great tool like erxis.

I am trying to install erxis on AWS EC2. I ran all the steps as mentioned and went successful. When I click on Office365 by Nyla integration, it takes me to a different page that cannot be reached.

![image](https://user-images.githubusercontent.com/19702561/97565838-3f5e3380-1a0c-11eb-8792-31474bbcc1ae.png)

When I try to integrate Nyla through system config page, this error shows up
![image](https://user-images.githubusercontent.com/19702561/97572409-2f475380-1a0e-11eb-8142-2fff7f2a072b.png)

**Comment by davidkartuzinski** [comment]
@azharumar I have asked for back-up on this from @munkhorgil.

**Comment by munkhorgil** [comment]
Hey @azharumar, What is your domain? it looks like your erxes url is your_domain_com
