### ISSUE TITLE
Error installing erxes with docker-compose

### ISSUE THREAD

**Issue by inazkue** [erxes/erxes#2489]
Deploying the application as described in https://www.erxes.org/installation/docker/#install-erxes an error occurs in point 6:
(Up to that point everything is fine with the docker-compose.yml)

root@docker2:~/erxes# docker exec -it erxes-api yarn loadPermissionData
yarn run v1.22.4
error Command "loadPermissionData" not found.

**Context (please include the related information if applicable):**
 - OS: Ubuntu 20.04.1 LTS
 - installation type docker

**Comment by yashodhan-netserv** [comment]
Yes, even I cant able to get application running using docker-compose example
I think installation document using docker is broken

**Comment by ned-kelly** [comment]
Check here - this is a working compose example: https://github.com/erxes/erxes/issues/2449
