### ISSUE TITLE
Adding Punjabi language with attractive UI

### ISSUE THREAD

**Issue by Anshika66-Gupta** [erxes/erxes#2498]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by davidkartuzinski** [comment]
@Anshika66-Gupta - I understand adding Punjabi as a supported language. Maybe someone in the community can tackle this. Could you clarify what you mean with "with attractive UI"?  

It would be helpful to complete the template for this issue if you want this treated as a priority.

**Comment by Anshika66-Gupta** [comment]
Interface Animation and several interactive layers that make scrolling experience and interactions actually looks original.

**Comment by davidkartuzinski** [comment]
@Anshika66-Gupta Thanks for answering but your answer doesn't provide any details as to your issue. Erxes is a huge piece of software.
