### ISSUE TITLE
yarn initProject in erxes-api results in an unhandled error event

### ISSUE THREAD

**Issue by antrikshmisri** [erxes/erxes#2536]
**Describe the bug**
When trying to run the backend of erxes in development mode, the command yarn initProject errors out. The commands before this run just fine but once yarn initProject is run in erxes-api , the job freezes for 5-10 minutes , eventually throwing an unhandled error event. The whole error is :- 
`Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:637   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)`

**To Reproduce**
1. Go to 'erxes-api dir'
2. run yarn initProject
3. See error

**Expected behavior**
The yarn initProject should return a password , that is used to run erxes in development mode.

**Context (please include the related information if applicable):**
 - OS: [e.g. Windows 10 20H2]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [manual]

**Additional context**

**Comment by antrikshmisri** [comment]
@erdenezul @munkhorgil  Can you please confirm if this is an issue or am i doing something wrong

**Comment by munkhjin0223** [comment]
Hey Antrikshmisri

erxes-api repo is now archived. Instead you can go to api folder of erxes repo.

**Comment by antrikshmisri** [comment]
@munkhjin0223 I tried the command in api directory as well , yarn gives me the following error:-
 **error** _Command "initProject" not found_.
