### ISSUE TITLE
Conversation: Replies to emails disappear after page refresh

### ISSUE THREAD

**Issue by WaldemarOrobanche** [erxes/erxes#2549]
**Describe the bug**
Replies to emails disappear after page refresh.

**To Reproduce**
1. Go to Team Inbox;
2. Choose one email from Imap integration;
3. Reply to the email;
4. Refresh the page.

**Expected behavior**
Replies are displayed in the conversation messages.

**Screenshots**
Before refresh
![before-refresh](https://user-images.githubusercontent.com/61522964/102885334-19bd3b80-444b-11eb-8d0b-2d6497ded040.png)
After refresh
![after-refresh](https://user-images.githubusercontent.com/61522964/102885338-1cb82c00-444b-11eb-9e7b-665b00feae79.png)

**Comment by munkhorgil** [comment]
Hey @WaldemarOrobanche, this is not a bug, it's an optimistic UI for a better user experience when you send an email, unlike regular messages it needs some time to be synced to in the Erxes from the third party. Once it's synced it will be stored in db
