### ISSUE TITLE
Date custom propertie doesn't save

### ISSUE THREAD

**Issue by grupale** [erxes/erxes#2571]
**Describe the bug**
I created custom properties and set the type as an input and the validation as a date. Neither when editing its value in the contact edition nor when importing a contact with a certain value in this field, the date is saved. 

**To Reproduce**
1. Go to 'Properties'
2. Click on 'Add propertie'
3. Set the type as an input and the validation as a date
4. Go to 'Customers' 
5. Edit a Customer and set a date in the custom propertie.

**Expected behavior**
When selecting a Date in the Customer edition the "Save" and "Discard" should appear, and after clicking in "Save" the date should me saved. When importing Customers via .xlsx the Custom field have to be saved. With other validations the inputed info is correctly saved. 

**Screenshots**
![Propiedad fecha](https://user-images.githubusercontent.com/10934794/103535896-4d975880-4e70-11eb-938c-5b46009caa1a.JPG)
![no figura guardar](https://user-images.githubusercontent.com/10934794/103535893-4cfec200-4e70-11eb-8a46-e909e6528d21.JPG)
![siaparece](https://user-images.githubusercontent.com/10934794/103535897-4e2fef00-4e70-11eb-9e63-0015fa9a5b8d.JPG)

**Context**
 - OS: Ubuntu 18.04
 - erxes version [0.20.8]
 - installation type [manual]

**Comment by soyombo-baterdene** [comment]
@grupale Issue is fixed and merged with develop branch.
