### ISSUE TITLE
Working version?

### ISSUE THREAD

**Issue by iCyberon** [erxes/erxes#258]
I was trying to build and test erxes, but looks like `erxes` and `erxes-api` are not compatible. I tried several branches and got various erros.

Which branches/tags work together?

**Comment by mendorshikh** [comment]
@iCyberon Hello there, thanks for the interest. We are very close to make a release. Hopefully, before November 24. At that time, we will fix this issue and more. Thanks have a good day!

**Comment by mendorshikh** [comment]
@iCyberon Hello, our 0.9 is our. We fixed issues u had trouble. Check it out!
