### ISSUE TITLE
Erxes popup embed won't save:  Permission Required for admin

### ISSUE THREAD

**Issue by becciwatson** [erxes/erxes#2607]
**Describe the bug**
Erxes installed onpremise, Went to create first popup to embed and it won't allow Save.
<img width="157" alt="permission required" src="https://user-images.githubusercontent.com/53285855/105648236-87eb9700-5efe-11eb-9da7-6e4a8ddee47d.png">
I am an admin with all permissions granted in the settings.

**To Reproduce**
1. Go to popups > embed
2. add a title, form title and brand
3. click save
4. See error: Permissions

**Expected behavior**
Save creates a popup

**Screenshots**

**Context (please include the related information if applicable):**
 - OS: Linux
 - Browser version: Firefox 84.02
 - erxes version latest
 - installation type: manual

**Additional context**

**Comment by indraganzorig** [comment]
@soyombo-baterdene or @batamar can you take a look at this when you get a chance?

@becciwatson, in the meantime,
I understand that you're an admin with all permissions, but have you tried assigning the permissions again? https://cln.sh/nwq1iz

**Comment by becciwatson** [comment]
I tried assigning the persmission again, it says granted, but still no change.
