### ISSUE TITLE
"AWS credentials are not configured" error upon upload

### ISSUE THREAD

**Issue by clicksmartmedia** [erxes/erxes#2636]
When I go to upload a csv file I get an error that says "AWS credentials are not configured".

1. Go to domain.com/settings/importHistories?type=customer
2. Click on Import Customers
3. Select a csv and click Open

You get the error towards the end of this video => https://www.loom.com/share/eae4f7c148e940d0a25d32b5b2cb35c5

**Comment by munkhorgil** [comment]
Hello @clicksmartmedia, Did you config your file upload type? If you don't want to use AWS set file upload type to **local** in Settings-> System Configs also here is the [link](https://www.erxes.org/administrator/system-config#file-upload) for doc.

**Comment by clicksmartmedia** [comment]
Awesome. Thanks! @munkhorgil
