### ISSUE TITLE
Upload Max File Size

### ISSUE THREAD

**Issue by clicksmartmedia** [erxes/erxes#2637]
Id like to upload more than 3k records at a time. Is there a way to increase the max size? It seems to fail if I go over 3k records at once.

**Comment by munkhorgil** [comment]
Hey @clicksmartmedia, can you share the error you got? and what is the size of records?

**Comment by clicksmartmedia** [comment]
3k seems to work. Anything more and you get the error seen in the video. Im guessing there is a limit somewhere in PHP or the app. 

https://www.loom.com/share/54dc709ad44247b4b4e1dfc72b1f7fdb

**Comment by munkhorgil** [comment]
Could you make sure that your csv file content's format is right? For example columns that match like other csv file's that imported successfully. The error you got is not related to records size.

**Comment by clicksmartmedia** [comment]
@munkhorgil I used the same file when I uploaded so all of the headers are exactly the same. the only thing that was different was the number of records. ive tried it on many different file and different sizes. 3,200 seems to be the max it will allow before throwing that error. thanks for the assistance!

**Comment by munkhorgil** [comment]
Could you share the screenshot of your server log when importing that file?
