### ISSUE TITLE
nginx: [emerg] invalid number of arguments in "server_name" directive in /etc/nginx/conf.d/default.conf:3

### ISSUE THREAD

**Issue by APPX-Studio** [erxes/erxes#2660]
nginx: [emerg] invalid number of arguments in "server_name" directive in /etc/nginx/conf.d/default.conf:3

![image](https://user-images.githubusercontent.com/49307767/109129887-15cfd180-778c-11eb-9753-c11d800671a0.png)

What should I do?

**Comment by degewo** [comment]
Hey,

check your entries under Services > Nginx > Configuration > Upstreams > Upstream. There should be an empty Upstream config without or invalid Servers.

Best
