### ISSUE TITLE
Docker install instructions broken - Missing initProject command

### ISSUE THREAD

**Issue by MatthewScholefield** [erxes/erxes#2711]
**Describe the bug**
When following the [docker installation instructions](https://www.erxes.org/installation/docker/#install-erxes), we can't create the initial user:
```console
$ docker exec -it erxes-api yarn initProject
yarn run v1.22.5
error Command "initProject" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
 - Follow the docker guide
 - Try to create the initial user

**Expected behavior**
An initial user is created and we can start using our local deployment.

**Additional context**
This command (along with others) were removed in bcf72d31. @batamar Would you be able to provide some context?

Related: [Comment](https://github.com/erxes/erxes/issues/2449#issuecomment-816949786), [Comment](https://github.com/erxes/erxes/issues/2536#issuecomment-751191848)

**Comment by codihaus** [comment]
I'm having the same issue also, this one is not available on the latest version, but the older version has. Not sure what to do.

**Comment by MatthewScholefield** [comment]
Also, I tried downgrading to 0.20.5, deleting elasticsearch and mongo data, and running `initProject` and `loadPermissions` but whenever I went to `localhost:3000` it just said "Hang in there" or something and the web request to `erxes-api` (`localhost:3300`) fails with connection reset. Not sure where to find logs for `erxes-api`.

If someone else could try these steps and downgrade to 0.20.5 it'd be helpful to know if the issue I faced affects multiple people or if perhaps for most people 0.20.5 works.

**Comment by codihaus** [comment]
It seems that on the latest version, the installation has been replaced with new package, called https://www.npmjs.com/package/create-erxes-app

And from that, the installation process has been replaced, like we will install NodeJs, pull that package, create the app.

And then, set the environment, run the commands like initiate and migration. So, I suppose "migration" would be the new command that alternate initProject stuff.

You can checkout develop branch to see.

**Comment by bt** [comment]
Is there an update on this issue? I just finished installing everything and noticed I have no way to `initProject` nor `loadInitialData`. It'd be great if the installation guide was more clear on how to proceed.
