### ISSUE TITLE
🚨 Potential Security Vulnerability - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [erxes/erxes#2732]
#### ⚠️ Potential Vulnerability in erxes

👋 Hello, @batamar, @ganzorig, @Anu-Ujin - @ranjit-git has disclosed a potential vulnerability in your repository. To validate or invalidate this potential vulnerability, please visit https://huntr.dev/bounties/1-other-erxes/erxes and join our community in helping secure open-source code.

---

#### ☎️ Need further support?

Come and join us on our [Discord](https://huntr.dev/discord) and a member of our team will be happy to help! 🤗

cc - @JamieSlome

**Comment by ranjit-git** [comment]
@batamar can you plz look into this report?
