### ISSUE TITLE
404 (Not Found) on the login screen

### ISSUE THREAD

**Issue by mninawa** [erxes/erxes#2740]
Hi Guys,
when i load the app in my localhost environment, i get this error
http://localhost:3300/set-frontend-cookies?envs={%22REACT_APP_API_URL%22:%22http://localhost:3300%22,%22REACT_APP_API_SUBSCRIPTION_URL%22:%22ws://localhost:3300/subscriptions%22,%22REACT_APP_CDN_HOST%22:%22http://localhost:3200%22,%22REACT_APP_DASHBOARD_URL%22:%22http://localhost:4200%22} 404 (Not Found)

What might be the issue?
I have loaded everything in a docker container
Paige

**Comment by indraganzorig** [comment]
@Myagmarsuren-a can you take a look at this when you get a chance?

**Comment by Myagmarsuren-a** [comment]
@mninawa Can you share your docker-compose file to us please?

**Comment by mninawa** [comment]
> @mninawa Can you share your docker-compose file to us please?
I have build all the images they reside on my local docker registry! 

version: "2.1"
services:
  erxes:
    image: erxes/erxes:0.17.6
    container_name: erxes
    restart: unless-stopped
    environment:
      # erxes
      REACT_APP_CDN_HOST: http://localhost:3200
      REACT_APP_API_URL: http://localhost:3300
      REACT_APP_API_SUBSCRIPTION_URL: ws://localhost:3300/subscriptions
      REACT_APP_DASHBOARD_URL: http://localhost:4200
      NGINX_HOST: localhost
    ports:
      - "3000:80"
    networks:
      - erxes-net

  erxes-api:
    image: mninawa/bundle-api:rose
    container_name: bundle-api
    restart: unless-stopped
    environment:
      # erxes-api
      PORT: "3300"
      NODE_ENV: production
      DEBUG: "erxes-api:*"
      JWT_TOKEN_SECRET: token
      # public urls
      MAIN_APP_DOMAIN: http://localhost:3000
      WIDGETS_DOMAIN: http://localhost:3200
      INTEGRATIONS_API_DOMAIN: http://localhost:3400
      # non public urls
      CRONS_API_DOMAIN: http://erxes-crons:3600
      WORKERS_API_DOMAIN: http://erxes-workers:3700
      LOGS_API_DOMAIN: http://erxes-logger:3800
      ENGAGES_API_DOMAIN: http://erxes-engages:3900
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes
      RABBITMQ_HOST: amqp://rabbitmq
      RABBITMQ_USERNAME: administrator
      RABBITMQ_PASSWORD: C0nsult@987
      # Elasticsearch
      ELASTICSEARCH_URL: http://elasticsearch
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 12345
    ports:
      - "3300:3300"
    depends_on:
      mongo:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - erxes-net

  erxes-crons:
    image: bundle-api:rose
    container_name: erxes-crons
    entrypoint: ["node", "--max_old_space_size=8192", "dist/cronJobs"]
    restart: unless-stopped
    environment:
      # erxes-crons
      PORT_CRONS: "3600"
      NODE_ENV: production
      PROCESS_NAME: crons
      DEBUG: "erxes-crons:*"
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - erxes-net

  erxes-workers:
    image: bundle-api:rose
    container_name: erxes-workers
    entrypoint:
      [
        "node",
        "--max_old_space_size=8192",
        "--experimental-worker",
        "dist/workers",
      ]
    restart: unless-stopped
    environment:
      # erxes-workers
      PORT_WORKERS: "3700"
      NODE_ENV: production
      DEBUG: "erxes-workers:*"
      JWT_TOKEN_SECRET: token
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - erxes-net

  erxes-widgets:
    image: mninawa/bundle-widgets:rose
    container_name: erxes-widgets
    restart: unless-stopped
    environment:
      # erxes-widgets
      PORT: "3200"
      ROOT_URL: http://localhost:3200
      API_URL: http://localhost:3300
      API_SUBSCRIPTIONS_URL: ws://localhost:3300/subscriptions
    ports:
      - "3200:3200"
    networks:
      - erxes-net

  erxes-engages:
    image: mninawa/bundle-engages-email-sender:rose
    container_name: erxes-engages
    restart: unless-stopped
    environment:
      PORT: "3900"
      NODE_ENV: production
      DEBUG: "erxes-engages:*"
      # public urls
      MAIN_API_DOMAIN: http://localhost:3300
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes_engages
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - erxes-net

  erxes-logger:
    image: bundle-logger:rose
    container_name: erxes-logger
    restart: unless-stopped
    environment:
      PORT: "3800"
      DEBUG: "erxes-logs:*"
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes_logs
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - erxes-net

  erxes-integrations:
    image: bundle-integrations:rose
    container_name: erxes-integrations
    restart: unless-stopped
    environment:
      PORT: "3400"
      NODE_ENV: production
      DEBUG: "erxes-integrations:*"
      # public urls
      DOMAIN: http://localhost:3400
      MAIN_APP_DOMAIN: http://localhost:3000
      MAIN_API_DOMAIN: http://localhost:3300
      # non public urls
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes_integrations
    ports:
      - "3400:3400"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - erxes-net

  mongo:
    image: mongo:3.6.13
    container_name: mongo
    restart: unless-stopped
    healthcheck:
      test: echo 'rs.initiate().ok' | mongo localhost:27017/test?replicaSet=rs0 --quiet
      interval: 2s
      timeout: 2s
      retries: 200
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    networks:
      - erxes-net
    # MongoDB data will be saved into ./mongo-data folder.
    volumes:
      - ./mongo-data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - erxes-net
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: 'bitnami/kibana:latest'
    container_name: kibana
    networks:
      - erxes-net

  redis-master:
    image: 'bitnami/redis:latest'
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=12345
    volumes:
      - './redis:/usr/share/redis/data'
    networks:
      - erxes-net
      
  rabbitmq:
    image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
     - './rabbitmq_data:/usr/share/rabbitmq_data/data'
    networks:
      - erxes-net

networks:
  erxes-net:
    driver: bridge
