### ISSUE TITLE
No send button in live chat widget and random input asking for email and sms

### ISSUE THREAD

**Issue by hexclann** [erxes/erxes#2752]
**Describe the bug**
I have a live chat widget on my test site, I have disabled the authentication while setting up the live chat, but there's a card asking user for email and sms. How can I disable that? 
Also there's no send button in mobile view

**To Reproduce**
1. Create a live widget
2. Copy and paste the script in the test website
3. Initiate chat
4. You can see the email and SMS card

**Expected behavior**
It should not ask for email and SMS when the live chat is initiated

**Screenshots**

![Screenshot_20210430-203328996](https://user-images.githubusercontent.com/59732888/116714855-cad47380-a9f3-11eb-9b6b-cd89ca3285b6.jpg)

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser version [e.g. chrome 90.0 windows and Android]
 - erxes version 0.20
 - installation type [manual with quick installation script]

**Comment by mendorshikh** [comment]
@hexclann 

1. About the authentication, there are two options. If you enable, email and SMS number ask beforehand. If you disable, email and SMS number ask afterward which you show above. 
2. About the send button on the mobile browser, the "return" button on the keyboard is the send button. I will show you via screenshot.

**Comment by mendorshikh** [comment]
![image](https://user-images.githubusercontent.com/1748857/116813811-4f57fb00-ab88-11eb-9dd7-7913a1f013b4.jpeg)
