### ISSUE TITLE
Error 400 on Android app and notifications not working

### ISSUE THREAD

**Issue by hexclann** [erxes/erxes#2753]
**Describe the bug**
I have a live chat on my test site. The installation is selfhosted including elasticsearch. I can connect the android app to my server. But whenever there's a new conversation it doesn't send any notification. Also when I go to sales pipeline I get error 400 and the pipeline will be empty.

**To Reproduce**
1. Download the android app
2. Login with the credentials
3. Initiate a conversation
4. You don't see any notification in app and when you go to sales pipeline you get error 400

**Expected behavior**
App should display notifications whenever a new event occurs

**Screenshots**

![Screenshot_20210430-204336492](https://user-images.githubusercontent.com/59732888/116716538-80ec8d00-a9f5-11eb-8cff-473d7f4efb3c.jpg)

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 18.04]
 - Android version [Android 10.0 with battery optimization disabled]
 - erxes version [0.20]
 - installation type [manual with quick installation script]

**Comment by mendorshikh** [comment]
@iwalker7 Plz followup here.

**Comment by iwalker7** [comment]
Hello @hexclann thanks for your feedback.
1) PushNotification 
Due to some libraries and developments, it is not possible to configure multiple environment for push notification and it is currently configured to on the Saas version only. I apologize for this, we are working on it and will try to include as soon as possible.
2) 400 Error
That alert is related to the difference between the version of the server and the Android application. There are breaking-changes in mobile application and erxes. So you need to update your erxes and mobile application to the latest version.

Let us know if issues are resolved. Thanks for using erxes.

**Comment by hexclann** [comment]
@iwalker7 thanks for the reply, we are looking to get the SaaS version of erxes. I created a free account and logged into the mobile app and initiated a conversation on the live chat, I did not get any notification.The app version is 1.0.9. And I still have #2752 issue, these are the two things that are holding us back from buying SaaS version

**Comment by iwalker7** [comment]
@hexclann Sounds good. 
1) Currently the mobile app is developed only meant to show incoming notification. I will meet with the developers to discuss why the notification is not coming. Also i think we will develop it in next spirint.
2) I will tell to web developers about # 2752 issue. The solution on the your mobile browser, you can double-click the done button in the right-bottom corner of your keyboard to send a message.

**Comment by hexclann** [comment]
> 1\.Currently the mobile app is developed only meant to show incoming notification. I will meet with the developers to discuss why the notification is not coming. Also i think we will develop it in next spirint.

Thanks for the info 

> 2\. I will tell to web developers about #2752 issue. The solution on the your mobile browser about send button, you can double-click the done button in the right-bottom corner of your keyboard to send a message.

Is it better to have a send button or an icon for better UX?
