### ISSUE TITLE
Cannot embed more than one form 

### ISSUE THREAD

**Issue by hexclann** [erxes/erxes#2768]
**Describe the bug**
Cannot display more than one form in the same page

**To Reproduce**
1. Go to 'Forms' and create 2 or more forms
2. Copy the form code and paste it in a page
3. Only one form will be displayed
4. See error in the browser console

**Expected behavior**
Multiple forms can be embedded without causing an issue

**Screenshots**

![chrome_GjBXe9Zrs8](https://user-images.githubusercontent.com/59732888/117243044-0c31ac80-ae54-11eb-922f-693b85056703.png)

![chrome_u9wMXljoBA](https://user-images.githubusercontent.com/59732888/117243050-0f2c9d00-ae54-11eb-9ebe-9fc308b1094d.png)

**Context (please include the related information if applicable):**
Erxes SaaS

**Comment by mendorshikh** [comment]
@hexclann How are you? Please check out https://bit.ly/3buY8tY this docs for various types of installing erxes Forms, Messenger, etc with combinations. Especially this section will help: https://bit.ly/3h4NjmJ
