### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by wissem1210** [erxes/erxes#2813]
**Got CORS issues when deploying erxes on VPS using Docker Swarm**

**Stack file**
I added the  new environment variables, tries multiple versions of erxes, tried to add Access-Control-Allow-Origin with traefik but the problem persisted
![exers](https://user-images.githubusercontent.com/52504385/119679670-74165a00-be38-11eb-9b54-7b3c4688977f.png)

**This is what i get**
![Screenshot from 2021-05-26 15-36-37](https://user-images.githubusercontent.com/52504385/119679555-5d700300-be38-11eb-9fc7-6218a3a27423.png)

**Comment by mendorshikh** [comment]
@wissem1210 well received. @Myagmarsuren-a plz take a look.

**Comment by Myagmarsuren-a** [comment]
@wissem1210 Please can you share your nginx configuration?

**Comment by wissem1210** [comment]
@Myagmarsuren-a I don't have an nginx configuration file, is there a way to get it work with traefik?

**Comment by Myagmarsuren-a** [comment]
@wissem1210 Please try following change ``` MAIN_APP_DOMAIN: http://erxes.vomba.rocks to MAIN_APP_DOMAIN: http://erxes-api.vomba.rocks in erxes-api container```

**Comment by wissem1210** [comment]
I changed it but it didn t resolve the problem 
![Screenshot from 2021-05-27 10-32-09](https://user-images.githubusercontent.com/52504385/119802992-f48b9800-bed6-11eb-90f6-3067fd8bd734.png)

**Comment by hjgrace** [comment]
I tried to change all "localhost" to ip address in docker file. 
it works.
