### ISSUE TITLE
Add support for whatsapp-web.js 

### ISSUE THREAD

**Issue by dagors** [erxes/erxes#2844]
**Is your enhancement request related to a problem? Please describe.**

The current WhatsApp integration is not affordable for everyone, so considering using https://github.com/pedroslopez/whatsapp-web.js may be an option for small businesses. 

**Describe the solution you'd like**
Integrate WhatsApp using https://github.com/pedroslopez/whatsapp-web.js
Let Erxes handle all the code necessary for integration with the whatsapp-web.js solution and be simple to add and manage for the end user. 

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by KhongorzulD** [comment]
Hi @dagors, Sorry for the late response. However thank you for your suggestion.
