### ISSUE TITLE
Old Password (Leave empty if you haven't set it up yet)

### ISSUE THREAD

**Issue by samyakOO7** [erxes/erxes#2857]
**Describe the bug**
1.When I join through magic link I dont update my password at first. When I go to global dashboard and update my password
it says leave blank if you didn't assign any password but even if I give some random password it takes and updates with my new password.
2. It says atleast 1 special character 1 letter and can't be same as previous password in rules. I am assigning same password multiple times its taking and without any special characters too.

**To Reproduce**
1. Create a erxes account using magic link
2. Go to erxes dashboard and try to set a password. It shows leave the field blank if password not set.
3. As you signed in through magic link password has not been set so instead of leaving that field blank I typed a random password and still it takes that as old password and updates password as per my new password.
4. Give same password again and again
5. Give password without special character

**Expected behavior**
1.I expect that it should show some error the password has not been updated as you joined through magic link. Update your password. 
2. You did not use special character or same password repeated try another one.

**Screenshots**
![Capture123](https://user-images.githubusercontent.com/53942554/124045996-951d2c80-da2e-11eb-8856-ac86e972c5ff.PNG)

**Comment by KhongorzulD** [comment]
Hi @samyakOO7, I am apologizing for the late response. However, do you still have a same issue when it comes to updating your password. And if so, I would like to ask that you can contribute to this issue. If you agreed, I will assign it to you. Thank you.
