### ISSUE TITLE
navbar and button and search bar

### ISSUE THREAD

**Issue by SanjeevKumar22** [erxes/erxes#2860]
**Is your feature request related to a problem? Please describe.**
add new style to navbar when scroll the page changes the color of navbar and remove outline when hover on search bar and add neon button style
 
**Describe the solution you'd like**

**Additional context**

**Comment by KhongorzulD** [comment]
Hi @SanjeevKumar22 Sorry for the late response. However, it would be great if you describe this issue in more detail with the solution.
