### ISSUE TITLE
worker does not work properly

### ISSUE THREAD

**Issue by soyombo-baterdene** [erxes/erxes#2919]
Error occurs when insert multiple customers or contacts via webhook. Also if property has number validation and data is empty string worker can not insert data. And worker can't find existing company by email or phone number.

**Comment by KhongorzulD** [comment]
@soyombo-baterdene Hi, is this issue also solved? Can I close it?

**Comment by soyombo-baterdene** [comment]
> @soyombo-baterdene Hi, is this issue also solved? Can I close it?

Hey @KhongorzulD, yes you can close it.
