### ISSUE TITLE
Official ARM64 docker images support?

### ISSUE THREAD

**Issue by DouglasMartins1999** [erxes/erxes#2925]
**Is your enhancement request related to a problem? Please describe.**
I realized that most of the project is written in TS/JS, therefore a cross-platform language. However, officially available docker images only support amd64 architecture. With the increasing popularity of arm64, included in Apple's new M1 processors, and many cloud services offering lower-cost instances based on the architecture (Oracle even offers some for free), wouldn't it be possible to use erxes on it? 

**Describe the solution you'd like**
I have very little knowledge on the subject, but I imagine there are ways to generate multi-architecture images in the docker through docker buildx, even when we haven't access to the platform. However, I haven't found instructions on how to do this on my own... 

I appreciate all help. Thanks in advance.

**Comment by KhongorzulD** [comment]
@DouglasMartins1999  Hey! I am apologizing for the late response. However, thank you for your suggestion and we will do some research on it and get back to you again. Also if you would like to work on this, let me know to assign it to you and we will happy to welcome you on it.
