### ISSUE TITLE
Clarify "Fair use" in the documentation and readme with use cases.

### ISSUE THREAD

**Issue by sergioisidoro** [erxes/erxes#2930]
## Problem
Right now this is the current text:

> Can I use erxes to manage my clients and make revenue?

> Yes, you can offer consulting and support services without prior permission as long as it is less than 30,000 USD ($30k) per year. If your revenue from services based on erxes is more than this threshold, we invite you to become a partner agency and apply for a license. If you have any questions about this, feel free to reach out to us at info@erxes.io.

It mixes using the product it in commercial setting and re-distribution / consulting. I think this results in some confusion and issues like https://github.com/erxes/erxes/issues/2908

## What I would like to see
Clearly answer the question of commercial use with a bit more drilled down questions, by separating consulting and commercial use:

* Can I use erxes in my for profit company?
   * Is there any revenue threshold of my company where I would be expected to support exres development?

* Can I install (ie distribute) or provide erxes support to my customers? and in what conditions? 
   * In case I'm a marketing / growth consultant 
   * In case I'm a devops engineer consultant 
   * in case I'm a specialist / erexs support provider 
   * Is there a revenue threshold when I'm expected to support exres dev (I guess this is answered in the current text)

**Additional context**
PS: I think your licenses is very nicely done, and I hope it prevents issues like what happened with Elastic search :) Especially tying contributions to revenue is great for small business 👏

**Comment by indraganzorig** [comment]
Hi @sergioisidoro this is really helpful.
We'll update our docs accordingly.
