### ISSUE TITLE
Adding a top/bottom scroll button

### ISSUE THREAD

**Issue by srijanishere** [erxes/erxes#2949]
**Issue**
Sometimes users don't like to scroll all the way to the bottom to find the company social handles, contacts, etc and again scroll back to the top to the navigation bar

**Solution**
A small "arrow-head" shaped button could be added on the bottom right side which would help in scrolling all the way to the bottom and vice-versa. The direction of the arrow-head would point downwards/upwards on scrolling to bottom/top.

**Comment by Kampani** [comment]
Hey @indraganzorig I would like to take this issue can you please assign it to me?

**Comment by srijanishere** [comment]
If possible, I would like to work on it as well.

**Comment by indraganzorig** [comment]
> Hey @indraganzorig I would like to take this issue can you please assign it to me?

Hi there, thanks for your interest. Perhaps it's best to assign to the author of the issue in this case. 

We'll be creating issues for OS contributors to work on this week. I'll let you know once they're posted.

**Comment by srijanishere** [comment]
Thanks for the assigning it to me.

**Comment by srijanishere** [comment]
Hey @indraganzorig I'm new to open-source contributing it would be really helpful if you could kindly guide to where the file which contains the source code of the landing page of the website(https://erxes.io/) is because the folder structure has made me a little confused. I would really appreciate the help.

**Comment by KhongorzulD** [comment]
> Hey @indraganzorig I'm new to open-source contributing it would be really helpful if you could kindly guide to where the file which contains the source code(frontend part) of the landing page of the website(https://erxes.io/) is because the folder structure has made me a little confused. I would really appreciate the help.

@indraganzorig Hello, Could you please take a look at it
