### ISSUE TITLE
Ability to edit, update, drag and drop Custom Property options

### ISSUE THREAD

**Issue by indraganzorig** [erxes/erxes#2954]
**Is your enhancement request related to a problem? Please describe.**
Users can create custom properties in erxes by:
1. Go to Settings -> Properties
2. Choose the Property category from the left-hand side column
3. Click on 'Add Group & Field'
4. Create a group by clicking on 'Add Group' 
5. And then create a property by Clicking on 'Add Property'

The current version of a custom property creation flow has the following challenges:

- Once you create a custom property with one type (i.e. radio button), you can not update the type. Updating the type removes all the options for that property:

![CleanShot 2021-09-09 at 17 00 08](https://user-images.githubusercontent.com/53030705/132656336-ef323dcb-0fb4-4be6-8116-a5df1a3eea4c.gif)

- Once you type in your options, you can not just edit it. You have to delete the option and retype again:

![CleanShot 2021-09-09 at 17 03 22](https://user-images.githubusercontent.com/53030705/132656728-1ff1c59d-c201-42b7-8bb9-e938fbc7d80c.gif)

- Once you type in all your options for a property, you can not move the order of the options. You need to delete the options and rewrite them in the correct order again:

![CleanShot 2021-09-09 at 17 07 28](https://user-images.githubusercontent.com/53030705/132657365-1d988aa7-9a2c-4199-9846-d952dec33af2.gif)

**Describe the solution you'd like**

- [x] Add ability to edit the option text for Select, Multiselect, Checkbox, Radio button types
- [x] Add ability to drag and drop and change the order of the options for Select, Multiselect, Checkbox, Radio button types

**Comment by oyunerdene-m** [comment]
I am starting to work on it. Please assign it to me @indraganzorig
