### ISSUE TITLE
Archived items need to have filter options 

### ISSUE THREAD

**Issue by KhongorzulD** [erxes/erxes#2971]
**Is your enhancement request related to a problem? Please describe.**
The show menu displays filter and archived items for tasks. Filter option offers filtering by created members, by priority, by team members, by labels, by companies, by customers, by segments and by due dates. But when members want to filter their archived tasks by those options, current feature can not allow to do it. 

**Describe the solution you'd like**
Want to filter my archived items by above mentioned filter options. 

**Additional context**
Current filter and archived items are seen as follows: 
![filter hesguud](https://user-images.githubusercontent.com/90193655/133392716-2ca91e51-d908-4148-a5b4-219216c43d74.PNG)
![filter hesguud 2](https://user-images.githubusercontent.com/90193655/133392736-e92a4b91-3b41-4499-9785-36549d981290.PNG)
![archived items](https://user-images.githubusercontent.com/90193655/133392747-a4e6521c-5f11-4bcb-a9d8-6b1387e4030d.PNG)

Erxes team can see task card using this link: https://office.erxes.io/task/board?id=wKbpQmWs3Aj7WXjc2&itemId=H8b8PtGv2jFMz8v8E&key=&pipelineId=wfnMyXbvRaFcFqJfv

**Comment by oyunerdene-m** [comment]
Hi. I want to work on this. Please assign it to me.

**Comment by KhongorzulD** [comment]
> Hi. I want to work on this. Please assign it to me.

Hi, I assigned it to you. Thank you !
