### ISSUE TITLE
Add sort option in the Sales/Task/Ticket/Growth Hacking pipelines list in the Settings

### ISSUE THREAD

**Issue by KhongorzulD** [erxes/erxes#2974]
**Is your enhancement request related to a problem? Please describe.**
It is hard to find the pipeline that the consumer is looking for to edit. 
To reproduce:
1. Go to > Settings
2. You will find the feature settings including Sales/Task/Ticket/Growth hacking pipelines
![feature settings](https://user-images.githubusercontent.com/90193655/133598123-e987486b-4cca-4fe8-b9e3-332c7dfb5d04.PNG)
3. Click one of the above and you will see it is better to sort those pipeline list. 
![task pipeline](https://user-images.githubusercontent.com/90193655/133598627-6fb3bb39-0c39-42f6-89c9-919625882f31.PNG)

**Describe the solution you'd like**

-  Add sort option that alphabetically sorts the Sales/Task/Ticket/Growth hacking pipelines list.
-  It would be great if search bar will be added to the pipeline lists and search from the lists only.

**Additional context**
Sort option can be similar to erxes Form's way of sorting as displayed below: 

![form](https://user-images.githubusercontent.com/90193655/133600104-bee9e70e-7df0-48ad-99aa-a5d9012312f9.PNG)

**Comment by oyunerdene-m** [comment]
Hi. Can I work on this. Please assign it to me.

**Comment by KhongorzulD** [comment]
> Hi. Can I work on this. Please assign it to me.

Hi, of course. I will assign it to you.
Thank you for your contribution !
