### ISSUE TITLE
Unable to locate the password

### ISSUE THREAD

**Issue by saurabhnsonar** [erxes/erxes#299]
@mendorshikh I tried installing all your push earlier too. Its great to hear the new release is out 0.9.0. I truly congratulate you and your team for this! I have tried installing that but unable to locate the credentials as per mentioned in .env.development file. Could you please check once again on it. If I am doing something wrong please guide me.

**Comment by munkhbold** [comment]
@saurabhnsonar  We are implementing [docker](https://www.docker.com/) into our project, so please wait until we finish it.

**Comment by saurabhnsonar** [comment]
Sure, thanks for updating 👍

**Comment by saurabhnsonar** [comment]
Thanks for the update but it is not working on my server. It shows following:

   Local:            http://localhost:3000/
erxes_1          |   On Your Network:  http://172.18.0.6:3000/

The IP mentioned does not match with my server IP. And also the connection to graphql is configured at localhost within the script. It should be towards IP (OPTIONS http://localhost:3300/graphql net::ERR_CONNECTION_REFUSED).

Same is for ws://localhost:3300/subscriptions it should pointing to IP.

**Comment by munkhbold** [comment]
@saurabhnsonar did you wait until docker-compose.yml complete?
it should work without changing `localhost:3300` to `erxes-app-api:3300`.  If you run apps on 3000, 3100, 3200, 3300 ports it'll show `port is already allocated`
Please show me your full error log.

**Comment by saurabhnsonar** [comment]
erxes-widgets_1  | Widget scripts are now running on port 3200
erxes-app-api_1  | ws://localhost:3300/subscriptions
erxes-app-api_1  | GraphQL Server is now running on 3300
mongo_1          | 2018-01-18T10:11:51.860+0000 I NETWORK  [listener] connection accepted from 172.18.0.5:43648 #11 (6 connections now open)
mongo_1          | 2018-01-18T10:11:51.877+0000 I NETWORK  [conn11] received client metadata from 172.18.0.5:43648 conn: { driver: { name: "nodejs", version: "2.2.31" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "3.10.0-693.11.6.el7.x86_64" }, platform: "Node.js v6.12.2, LE, mongodb-core: 2.1.15" }
erxes-app-api_1  | Connected to the database: mongodb://mongo/erxes
mongo_1          | 2018-01-18T10:11:51.933+0000 I NETWORK  [listener] connection accepted from 172.18.0.5:43654 #12 (7 connections now open)
mongo_1          | 2018-01-18T10:11:51.942+0000 I NETWORK  [listener] connection accepted from 172.18.0.5:43656 #13 (8 connections now open)
mongo_1          | 2018-01-18T10:11:51.945+0000 I NETWORK  [listener] connection accepted from 172.18.0.5:43658 #14 (9 connections now open)
mongo_1          | 2018-01-18T10:11:51.950+0000 I NETWORK  [listener] connection accepted from 172.18.0.5:43660 #15 (10 connections now open)

erxes_1          | Compiled successfully!
erxes_1          |
erxes_1          | You can now view erxes in the browser.
erxes_1          |
erxes_1          |   Local:            http://localhost:3000/
erxes_1          |   On Your Network:  http://172.18.0.7:3000/
erxes_1          |
erxes_1          | Note that the development build is not optimized.
erxes_1          | To create a production build, use yarn build.
erxes_1          |


Why browser shows error in console log:

WebSocket connection to 'ws://localhost:3300/subscriptions' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
OPTIONS http://localhost:3300/graphql net::ERR_CONNECTION_REFUSED


As I am running all this on my server and not on my local machine.

**Comment by jubel02** [comment]
@saurabhnsonar , please take a look at our [wiki](https://github.com/erxes/erxes/wiki). I'm closing this one. If you have any questions feel free to open new issue, I'll gladly help you.
