### ISSUE TITLE
Couldn't signIn on PC by entering email.  

### ISSUE THREAD

**Issue by aditya-gaikwad** [erxes/erxes#2994]
Unable to view the profile by signing in. After clicking on SignIn and entering email it always shows "A mail has been sent on your respective email".

1. Go to erxes website and click on signIn [(link to erxes website)](https://erxes.io/)
2.  Enter your Email
3.  You will get an email on your device
4.  After clicking there you should enter on your profile. But in PC it is again repeating the same process.

![issue1](https://user-images.githubusercontent.com/63276445/134804037-6a9bc745-b4b6-4b60-adc3-719a29e7ff09.PNG)

Expected process should be:
Once you enter your email, you should be redirected to your profile page.

**Comment by KhongorzulD** [comment]
@indraganzorig Hi, Would you please take a look at it?

**Comment by indraganzorig** [comment]
@aditya-gaikwad it seems to be working from my device with a Gmail-supported email address.

Could you please share these with us?

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [e.g docker, manual]
