### ISSUE TITLE
Bug in Try Live Demo page

### ISSUE THREAD

**Issue by aditya-gaikwad** [erxes/erxes#2995]
If a new user not having an account on erxes try to use live demo, would get a space for entering password, and if user enter password it says password is wrong. This is a bug as the user is new so user is not having any password.

1. Go to erxes website 
2. Clink on Try llive demo
3. Enter Email and password

![issue2](https://user-images.githubusercontent.com/63276445/134804547-dd20b378-96af-479f-ad68-2381ae9e55d0.PNG)

**Comment by KhongorzulD** [comment]
@indraganzorig Would you please take a look at it?

**Comment by indraganzorig** [comment]
@aditya-gaikwad thanks for this.
We're in the midst of updating the demo page and no longer developing the live demo instance.
Sorry, we should've hidden the buttons sooner.

@nandirb could you please hide the 'try the live demo' button until I get the updated page for you?
