### ISSUE TITLE
Chat Section needed to be improved

### ISSUE THREAD

**Issue by aditya-gaikwad** [erxes/erxes#2996]
After clicking on chat icon. A pop up window is opened and after scrolling there is a small bug of non-sticky Support and FAQ Button.

The Support and FAQ button should appear on top of chat section or the alternate way to fix this is to make the support and FAQ button sticky.

![issue3](https://user-images.githubusercontent.com/63276445/134804672-6b867242-ec35-465b-a782-f581cd74672a.PNG)

**Comment by KhongorzulD** [comment]
@indraganzorig Can you take a look at it please?

**Comment by indraganzorig** [comment]
We could definitely improve the vertical scrolling and leaving the Support/FAQ tabs fixed. 

Would you be interested in working on this issue @aditya-gaikwad ?
If so, @Anu-Ujin can provide some guidelines
