### ISSUE TITLE
Ability to upload a photo in the Thank you section

### ISSUE THREAD

**Issue by KhongorzulD** [erxes/erxes#2998]
**Describe the solution you'd like**
Want to have an ability to upload a picture in the thank you section. So that, the customers who completed the form can see 'thank you' in more expressive way and It can be illustrated with more beautiful pictures than just words.

**Additional context**
Current thank you section is seen as follows:
![thank  you heseg](https://user-images.githubusercontent.com/90193655/134840356-ebd84c0a-67b5-446a-b3ac-97bd14268e1c.PNG)

Erxes team can access to the task card using [the link](https://office.erxes.io/task/board?id=wKbpQmWs3Aj7WXjc2&itemId=X5WcoTjLsh2Qm8fZ4&key=&labelIds=TZdWCKkviNkJP2ucP&pipelineId=xYYjieTMKAwKm8K9S)

**Comment by Siddharth1002** [comment]
Can i Try working on this issue?

**Comment by KhongorzulD** [comment]
Hi @Siddharth1002, Of course, I assigned it to you. Thank you for your contribution !

**Comment by indraganzorig** [comment]
Reassigning this task, as there were no updates in about a month.

**Comment by UjjwalMahar** [comment]
hey can I work?
