### ISSUE TITLE
Put a length limit on the fields

### ISSUE THREAD

**Issue by KhongorzulD** [erxes/erxes#2999]
**Is your enhancement request related to a problem? Please describe.**
Would like to include a length limit between the number and letters that can be written. So that, e.g customers can see that only 7 numbers must be entered as organization's registration number.

1. Go to 'Settings',
2. Click on 'Properties',
3. Click on 'Add property',
![validation](https://user-images.githubusercontent.com/90193655/134843104-2bbcb4b5-16c0-427d-a4fe-44abfeb493f4.PNG)

**Describe the solution you'd like**
In VALIDATION, when Custom Regex is selected, an additional Input opens immediately.
- [ ] Add an option 'custom regex' to the validation. 
- [ ] Add an input section after choosing custom regex where customers can write any regex.

**Additional context**
Регистрийн дугаар: (кирилээр бичих) УУ90090900

((?:А|Б|В|Г|Д|Е|Ё|Ж|З|И|Й|К|Л|М|Н|О|Ө|П|Р|С|Т|У|Ү|Ф|Х|Ц|Ч|Ш|Щ|Ъ|Ы|Ь|Э|Ю|Я){2}[0-9]{2}(?:(?:0|2)[0-9]|(?:1|3)(?:0|1|2))(?:(?:0|1|2)[0-9]|3(?:0|1))[0-9]{2})

Байгууллагын РД: 7 оронтой тоо     

(^[0-9]{7}$)

Бусад текст утга: 
(.*)

Erxes team can access to the task card using [the link](https://office.erxes.io/task/board?id=wKbpQmWs3Aj7WXjc2&itemId=qRAxanfcWvAtGubkz&key=&labelIds=TZdWCKkviNkJP2ucP&pipelineId=xYYjieTMKAwKm8K9S)

**Comment by dddqwerty** [comment]
can you assign it to me?

**Comment by KhongorzulD** [comment]
Hi @dddqwerty, I assigned it to you. Thank you for your contribution !
