### ISSUE TITLE
Phone number validation

### ISSUE THREAD

**Issue by KhongorzulD** [erxes/erxes#3010]
**Describe the bug**
Current phone number validation is not working properly in both form field and contact details. When clicking the save button, validation directly allows any number characters without specific standard. But allowing the any numbers in phone causes wrong sms or call. Therefore, phone numbers need to have a standard input.

**To Reproduce**
Steps to reproduce the behavior in FORM field:
1. Go to 'Forms'
2. Click on 'Create pop up'
3. Click on  'Content'
4. Scroll down to 'Phone number'
5. You will see the Validation with dropdown including phone. 

![form](https://user-images.githubusercontent.com/90193655/135199245-4f000589-5cc1-41ff-bc4f-389d05ee7c82.PNG)

Steps to reproduce the behavior in CONTACT details:
1. Go to 'Contacts'
2. Click any of your customer
3. Click on  'Editing icon next to customer avatar'
4. Scroll down to 'Phone and verification status'

![contact](https://user-images.githubusercontent.com/90193655/135199256-c656696c-77d3-4ed1-a0d5-5ee29d87b130.PNG)

**Expected behavior**
The input standard goes to phone should be "plus sign, country code, then phone number" e.g "+976 89997887". Validation then allows this input character, and if not, decides that the save button will not work until the phone input is written as standard.

Erxes team can access to the task card using [the link](https://office.erxes.io/task/board?id=wKbpQmWs3Aj7WXjc2&itemId=m88KW3kQzxehJ7rfj&key=&labelIds=TZdWCKkviNkJP2ucP&pipelineId=xYYjieTMKAwKm8K9S)

**Comment by TechTarun** [comment]
I can fix this using regex or some other relevant approach. Please assign it to me!

**Comment by nomio19** [comment]
@TechTarun assigned to you. Good luck!
