### ISSUE TITLE
Bad Gateway error during Quick Step installation

### ISSUE THREAD

**Issue by grupale** [erxes/erxes#3027]
Im trying to build a fresh installation in a Ubuntu server with the Quick Step installation and Im getting this errors during the installation
after setting the domain:

![image](https://user-images.githubusercontent.com/10934794/135683217-b8869d6f-d64b-430b-9c8e-51d3cffd4031.png)

and after choosing y to install RabbitMQ
![image](https://user-images.githubusercontent.com/10934794/135683240-05df6978-b97c-421e-ae42-71407c683ff5.png)

After this, the setup script stops and doesnt install the Erxes app.

Please any hint?

**Comment by KhongorzulD** [comment]
@batamar Hi, Could you please take a look at it?

**Comment by avping** [comment]
thats because of ubuntu 18.04 and libc6=2.27, if u dont choose rabbitmq during install it should work fine. otherwise update libc6 to >=2.29.
