### ISSUE TITLE
Can not close the card when its size is small 

### ISSUE THREAD

**Issue by KhongorzulD** [erxes/erxes#3030]
**Describe the bug**

"x" character or closing button of a card is not working properly when the size of a card is small. 

**To Reproduce**
1. Go to 'Any section which has a card'
2. Click on 'Any card'
3. Zoom in 'That card'
4. See error when trying to close that card.

**Expected behavior**
Regardless of the size of a card, the card will close when you click at the "x" button.

Erxes team can access to the task card using [the link](https://office.erxes.io/task/board?id=wKbpQmWs3Aj7WXjc2&itemId=f5ZNGacY43Zk9sm7J&key=&labelIds=TZdWCKkviNkJP2ucP&pipelineId=xYYjieTMKAwKm8K9S)

**Comment by benardcharumbira** [comment]
@KhongorzulD may you please assign this to me

**Comment by KhongorzulD** [comment]
Hi @benardcharumbira, I assigned it to you. Good luck !

**Comment by KhongorzulD** [comment]
Hello @benardcharumbira, Can I ask what status or processes are u going on right now with this issues, and please provide me some updates solving this issue. Because it seems like you are not working on this over the month. If you stopped working on it, I need to consider to reassign this issue to someone else. Please provide me a response on it. Thank u !

**Comment by charchit95** [comment]
Hi @KhongorzulD, can you assign this issue to me?
