### ISSUE TITLE
Open a new tab when clicking to the link in the cards of task, tickets and sales.

### ISSUE THREAD

**Issue by KhongorzulD** [erxes/erxes#3032]
**Is your enhancement request related to a problem? Please describe.**
When clicking to the link located in the card description, it automatically opens in the existing tab. It causes an issue when need to go back to the card tab. 

**Describe the solution you'd like**
Want to open a new tab to the link clicked in the description of the card. 

To reproduce the behavior:
1. Go to the 'Card'
2. Put a link in the description of the card.
3. Then click the link and see the result.

Erxes team can access to the task card using [the link](https://office.erxes.io/task/board?id=wKbpQmWs3Aj7WXjc2&itemId=DjKSPTAEnkMLjQJcD&key=&labelIds=TZdWCKkviNkJP2ucP&pipelineId=xYYjieTMKAwKm8K9S)

**Comment by KhongorzulD** [comment]
Hi @wweverma1 I assigned it to you. Thank you for your contribution !

**Comment by wweverma1** [comment]
@KhongorzulD can you please help me in setting up the project in my local environment?
I cloned this repository https://github.com/erxes/erxes and ran "npm install" but I'm unable to proceed further.
