### ISSUE TITLE
Ability to see a card created date and user

### ISSUE THREAD

**Issue by KhongorzulD** [erxes/erxes#3033]
**Is your enhancement request related to a problem? Please describe.**
In the current card detail, It is not possible to see the card's created date and user. 

**Describe the solution you'd like**
Want to see the card created date and card created user(indicating user's avatar)next to the card name /top right of the card/ as described below:

![card](https://user-images.githubusercontent.com/90193655/135849154-e21f5dac-80ab-4cd7-9fe7-f3552a5497ca.PNG)

Erxes team can access to the task using [the link](https://office.erxes.io/task/board?id=wKbpQmWs3Aj7WXjc2&itemId=6iTrJZfE3twYPAQGj&key=&labelIds=TZdWCKkviNkJP2ucP&pipelineId=xYYjieTMKAwKm8K9S)

**Comment by aspiringananya** [comment]
@KhongorzulD  Please assign this to me

**Comment by KhongorzulD** [comment]
Hey @aspiringananya How are u, how's the work of solving the issue?. Can u please provide me some updates regarding with this issue. Because it seems like u are no longer working on it almost a month. Hence it would be better for me to reassign this issue to someone else if u stopped working on it. So please let me know or give me a response on it. Thank u !

**Comment by aspiringananya** [comment]
Hi ,

I am on vacation at the present moment you can have it reassigned !

**Comment by charchit95** [comment]
Hi @KhongorzulD, I was looking into this issue but we are not capturing the card created date instead we have the Last Modified Date. If we can add the Last Modified Date instead of the Created Date then I can add this enhancement.
