### ISSUE TITLE
Getting 404 error for one of the pricing links

### ISSUE THREAD

**Issue by ashutoshanand13** [erxes/erxes#3055]
**Describe the bug**
Whenever clicking on the pricing menu after going to the [Erxes Installation](https://erxes.io/install/) link, it gives a 404 error. 
**To Reproduce**
1. Go to [Erxes Installation](https://erxes.io/install/)
2. Click on Pricing Menu (https://erxes.io/install/pricing)
3. See error

**Expected behavior**
Should display the pricing page

**Screenshots**
![image](https://user-images.githubusercontent.com/7820888/137633692-9554221e-0071-4d87-95f8-a1215e4bed79.png)

**Context (please include the related information if applicable):**

**Additional context**

**Comment by KhongorzulD** [comment]
Hey @ashutoshanand13 can you give me some update on this issue, thank you

**Comment by aaryahjolia** [comment]
Hello @KhongorzulD  , I noticed that this issue has not been resolved.
I would love to work actively on this issue. Can you assign this task to me ?
Thank you.
