### ISSUE TITLE
Support for multitenancy for multiple teams

### ISSUE THREAD

**Issue by Praggie** [erxes/erxes#307]
Hi, 

       This product seems interesting. I was going through the application and could not find the way this application can support multiple user from different teams. Is there any plans to support multiple teams (multi-tenancy)? if yes, how you plan to do the isolation between teams? create separate containers and databases? what is the architecture of application? we would love to contribute if there is some clarity on this.

Regards,

**Comment by mendorshikh** [comment]
Hello @Praggie and Happy New Year!

We do support multiple teams via separate brands and channels. Each team member who belongs to certain brand or channel receives only that certain brand or channel's information. However, we are not separating through containers and databases. There will be one container and database even though they are separate.

We will soon make a release having a docker and fixing our demo. Let me know if u have more questions.

**Comment by Praggie** [comment]
@mendorshikh Wish you a very happy New Year. Thanks for clarifying my queries. 

So it seems product is designed for marketing agencies and each marketing team require separate installation. While it is possible that inside marketing agency multiple team members are working on different brands, but they all have to be given proper access by admin users. 

So If I have understood it correctly then an admin user can create a brand and assign the brands to a user. Thus, in this scenario, users can not probably register themselves and create their own brands and integrations. They will need admin's help for same. It means this product can not be used as SaaS platform, where multiple marketing customers can come and register themselves, create brands and use the product.

**Comment by mendorshikh** [comment]
@Praggie 

Yes. erxes can not be used as SaaS platform. I think it is better for u to see our DEMO once it is up. We haven't updated our demo recently. But very soon we will fix it. At that time i will let u know.

**Comment by Praggie** [comment]
@mendorshikh Thanks for clarification. Looking forward for updated demo.

**Comment by jubel02** [comment]
Hello, @Praggie.
Thanks for interest in our project. You've got a good understanding about our project. I believe you've already seen our demo.  If you haven't take a look at demo, you can check it out [here](https://demohome.erxes.io). (Login using username: demo@erxes.io , password: demo)

Project is under heavy active development, our new demo website is outdated by few commits. (Mostly performance improvements changes). But i believe you can check out major features of erxes project. I'm closing this issue now, if you've any questions feel free to open a new issue. We'll gladly help you and we'll always appreciate any kind of [contribution](https://github.com/erxes/erxes/blob/master/CONTRIBUTING.md).
