### ISSUE TITLE
Little margin should be there 

### ISSUE THREAD

**Issue by Palaksharma23** [erxes/erxes#3077]
**Is your enhancement request related to a problem? Please describe.**
I guess there should be a little margin in between these two lines it will look more great 

![erxes](https://user-images.githubusercontent.com/87171452/138923951-f5ea8b0d-946a-4acb-a8ff-05292d57bcf6.png)

**Comment by Palaksharma23** [comment]
could you provide me some reference to the front page html

**Comment by KhongorzulD** [comment]
Hey @nandirb, I hope you're doing well. Can u please provide what @Palaksharma23 requested please. Thank you.

**Comment by KhongorzulD** [comment]
Hey @Palaksharma23, due to the internal access we decided to work on this by ourselves. Anyways, thank u for your suggestion and goodluck for your other issues that u working on so far !

**Comment by nandirb** [comment]
<img width="1284" alt="Screen Shot 2021-11-06 at 11 31 52" src="https://user-images.githubusercontent.com/58172661/140596613-28b36111-efeb-434b-a007-d693e1c5d587.png">
Thank you for your suggestion @Palaksharma23 It looks better now
