### ISSUE TITLE
PLEASE GIVE SOME PYTHON RELATED PROJECT

### ISSUE THREAD

**Issue by OMGUPTA21** [erxes/erxes#3105]
**Is your enhancement request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by KhongorzulD** [comment]
Hi @OMGUPTA21, please give more description on that

**Comment by OMGUPTA21** [comment]
image recgnization

**Comment by TechnoMage21** [comment]
> Hi @OMGUPTA21, please give more description on that

please update my username.
