### ISSUE TITLE
MAKE A DJANGO RESPONSIVE SITE

### ISSUE THREAD

**Issue by OMGUPTA21** [erxes/erxes#3106]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by KhongorzulD** [comment]
@OMGUPTA21 please give more explanation on that. What is the actual issue ?

**Comment by TechnoMage21** [comment]
please update my username.

**Comment by TechnoMage21** [comment]
> @OMGUPTA21 please give more explanation on that. What is the actual issue ?
please update my username.
