### ISSUE TITLE
MAKE A TIC TAK TOE GAME

### ISSUE THREAD

**Issue by OMGUPTA21** [erxes/erxes#3107]
**Is your enhancement request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by KhongorzulD** [comment]
@OMGUPTA21 please give more description on that issue, otherwise we will close the issue for the inconvenience

**Comment by TechnoMage21** [comment]
> @OMGUPTA21 please give more description on that issue, otherwise we will close the issue for the inconvenience

please update my username.
