### ISSUE TITLE
Erxes Instagram link not updated!

### ISSUE THREAD

**Issue by aaryahjolia** [erxes/erxes#3203]
On the erxes website, at bottom of footer, links of erxes social media profiles are there.
But erxes instagram account - [instagram.com/erxeshq](https://www.instagram.com/erxeshq/) is not there in the logos of social media websites.

![image](https://user-images.githubusercontent.com/82600388/152130510-5c848685-a0ee-4ebc-beca-5d3c55a72e3e.png)

The Instagram logo needs to be added in the footer of erxes website with it's instagram profile link.

I would love to work on this issue.

**Comment by prakhar-198** [comment]
Please assign me this issue I would like to work on it.

**Comment by sohailg** [comment]
Hello @erxes , I would love to work on this issue. Can you please assign this issue to me?

**Comment by ThunderBolt-OS** [comment]
Could you please assign me this issue, i would like to work on it, i am beginner in open source

**Comment by hussnainjav3d** [comment]
i would love to work on this issue please it to me

**Comment by bnomio19** [comment]
@enkhzule assigned to you. Goodluck!

**Comment by bnomio19** [comment]
This issue completed. @hussnainjav3d @sohailg @prakhar-198 @aaryahjolia
