### ISSUE TITLE
AWS deployment

### ISSUE THREAD

**Issue by mninawa** [erxes/erxes#3271]
Hi Guys,
im trying to deploy the app in AWS fargate, has anyone manange to do this before. I need some point of reference, please assist if you can

Kind Regards
Paige

**Comment by mendorshikh** [comment]
@mninawa How are you? Please wait 2 weeks. Our new version is coming soon.

**Comment by mninawa** [comment]
Will wait sir.. thanx

**Comment by magick93** [comment]
Hi @mendorshikh - any updates on this? I'm also interested to know how we can deploy, ideally, to k8s, but aws in the meantime would be great.

**Comment by mninawa** [comment]
we still quiet here

**Comment by marcelinhov2** [comment]
long time no see
