### ISSUE TITLE
Color is not changing on hover

### ISSUE THREAD

**Issue by subham-04** [erxes/erxes#3295]
- **Button color is not changing on hover**

When I came to Erxes's website its UI looks clean and easy to use but whenever we go for  **sign up**, here I've seen some issues -
Whenever I hover on the **sign up** button its background goes white and the text becomes black. But in the code it's written that when we hover on the button it will change its background color to  **background-color: #f09802;** but its not apply the background color.

- **Described Solution**

To solve this problem we just need to change the code from this-

**nav .nav-wrapper ul .btn:hover {
    background-color: #f09802;
}**

to this-

**nav .nav-wrapper ul .btn:hover {
    background-color: #f09802 !important;
}**

We've to add **!important** after putting the color.

- **Being a user of Erxes, I can assure you that it would bring a better user experience to the website**

**Comment by SwarupKMondal** [comment]
please assign this issue to me I want to work on it

**Comment by Harsh3363** [comment]
I would like to fix this

**Comment by sankalp123-w** [comment]
I would like to do this please assign me

**Comment by bnomio19** [comment]
@sankalp123-w  sorry for the late reply. This issue is assigned to you, Good Luck!

**Comment by SK-ILLish-GIT** [comment]
@subham-04 i would like to contribute in this part.If it is still available

**Comment by ShreyoPaul** [comment]
I would like to contribute in this issue to solve it, can i get assigned?

**Comment by Nazir-Rizwan** [comment]
I want to contribute this issue please assign me

**Comment by lagan-dev** [comment]
I would like to contribute to this issue . Please assign me if the issue is still available.

**Comment by nomio19** [comment]
@lagan-dev @Nazir-Rizwan @ShreyoPaul  are you guys, still interested in this issue?

**Comment by lagan-dev** [comment]
Yes , I am. I will be very happy to contribute.
I want to confirm the issue -> 
change the background color of "SIGN IN" button to `#f09802 ` on hover.

**Comment by HimanshuNarware** [comment]
I would like to contribute to this issue . Please assign me if the issue is still available.

**Comment by Nazir-Rizwan** [comment]
@nomio19  yes i still interested

**Comment by Omsoni06** [comment]
I am taking initiative to solve this issue
