### ISSUE TITLE
Fix broken link in  CONTRIBUTING.md

### ISSUE THREAD

**Issue by ZouvikPan** [erxes/erxes#3314]
**Is your enhancement request related to a problem? Please describe.**
Yes. The link to **How to Contribute to an Open Source Project on GitHub** in the CONTRIBUTING.md file is broken. Also, the text in the CONTIRBUTNG.md can be rephrased to make it even more beginner-friendly and welcoming for anyone who visits the project.

**Describe the solution you'd like**
The hyperlink associated with **How to Contribute to an Open Source Project on GitHub** in the CONTRIBUTING.md file should be fixed with a working hyperlink. Also, the text can be rephrased to make the project more welcoming for anyone who visits it.

**Additional context**
Below is the screenshot of where the current hyperlink associated with **How to Contribute to an Open Source Project on GitHub** in the CONTRIBUTING.md file lands.
![Screenshot from 2022-05-22 12-15-33](https://user-images.githubusercontent.com/42470856/169682792-a531b88e-7932-4135-8c84-8e505963767f.png)

**Comment by TechTarun** [comment]
I want to pick this up, please make me assignee!

**Comment by ZouvikPan** [comment]
Hi Tarun, the issue has been resolved already.
