### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Jarrodsz** [erxes/erxes#3339]
Is there a new release planned?
7 months latest one

**Comment by mendorshikh** [comment]
There will be one soon

**Comment by tjsims1** [comment]
is there a chance that the new release will bring the install up to 20.04?

**Comment by mendorshikh** [comment]
@batamar Can you give us an idea & ETA?

**Comment by mendorshikh** [comment]
@tjsims1 Our Co-Founder & CTO BJ told me a second ago that he will make the new release by June 30.

**Comment by Jarrodsz** [comment]
Any updates on this?
Can we say the opensource version is not a priority? Its shame since the systym is unqique
And great but we cannot disclose our data on cloud server of legal reasons.

Hoe about paying a license fee and be able to install the opensource version on own server and you use the funds to keep the opensource
Version more up2date

**Comment by tjsims1** [comment]
This was pulled from this discussion : [https://github.com/erxes/erxes/discussions/3382](url) " You know what, there will be a newer version. It will be launched by the end of July. I suggest you wait. https://xosdemo.erxes.io/ here you can check out our demo." so hopefully it comes out then

**Comment by Jarrodsz** [comment]
> This was pulled from this discussion : [https://github.com/erxes/erxes/discussions/3382](url) " You know what, there will be a newer version. It will be launched by the end of July. I suggest you wait. https://xosdemo.erxes.io/ here you can check out our demo." so hopefully it comes out then

invalid link..
I guess we look for another project.

**Comment by mendorshikh** [comment]
@Jarrodsz Hello there, lots of things happening ofc. I can send you a docker installation guide which will be updated soon. Does this help? About the release, we are working on it. ETA I think mid August for sure. Promise.

**Comment by tjsims1** [comment]
@Jarrodsz https://github.com/erxes/erxes/discussions/3382#discussioncomment-3097603
