### ISSUE TITLE
erxes developer experience map

### ISSUE THREAD

**Issue by naurenbatjargal** [erxes/erxes#3410]

**Comment by uchral** [comment]
Please assign me

**Comment by dulzorigo** [comment]
please assign me

**Comment by teddytei** [comment]
please assign me

**Comment by dulzorigo** [comment]
[Developer experience map](https://www.figma.com/file/U7powEsEiUPvjlJ0qiqn4n/Erxes-DX-Journey-map?node-id=0%3A1)
