### ISSUE TITLE
Provide a working path to migrate from selfhosted to SaaS and vice versa

### ISSUE THREAD

**Issue by alexanderadam** [erxes/erxes#3464]
**Is your feature request related to a problem? Please describe.**

I guess that it takes some pressure from customers if they'd know that they can switch easily.

**Describe the solution you'd like**

A solution to migrate from/to selfhosted to SaaS and vice versa.

**Comment by mendorshikh** [comment]
@alexanderadam Well received. I will let the team know. Currently, we are planning to migrate one of our customers manually. It makes sense that in the future we should provide a working path on the docs to migrate from self-hosted to SaaS and vice versa.
