### ISSUE TITLE
Facebook reaction should be show real in the inbox

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#35]
![How_the_new_instagram_logo_was_made__-_The_New_Media_Group](http://static.gitscout.com/6aa1c2b8368b760aead2c1d7313ea40afae2ec3a09bf376a05d35103da9c27f5.png)

![https___www_erxes_org_inbox_details_i5BbZAun2EPcFC3tu_and_Franz](http://static.gitscout.com/b5c9961da2b2b268bccea1721ebfbb39e7f72b78e7a586ecd66a453318ed943a.png)

**Comment by batamar** [comment]
Now, new fields are available in message schema. Use those in conversation box.

message.facebookData.item, choices = comment, reaction

when reaction is available, there will be value in message.facebookData.reactionType(choices, haha, wow, like, etc ...) show these as emoji
