### ISSUE TITLE
Add each of split amount by product & service

### ISSUE THREAD

**Issue by Ariunboldburentsogt** [erxes/erxes#3545]
**Is your enhancement request related to a problem? Please describe.**
There is only one result, Total. I want to see how much the product costs and how ,uch the service costs.

**Describe the solution you'd like**
Before the **Total** amount, 
- service: ...., 
- product: .... 
- then **Total**.  Structure like this format.

**Additional context**

![Image](https://user-images.githubusercontent.com/105905631/187376121-619e680d-8e6f-43c2-bd61-36d2a0ccd05f.png)

**Comment by bnomio19** [comment]
Backlog

**Comment by nomio19** [comment]
Anyone interested in this issue? Please mention me. :)
