### ISSUE TITLE
Fixing links for documentation in README

### ISSUE THREAD

**Issue by useraid** [erxes/erxes#3614]
**404 Links**
The contributing and documentation link does not work in the main README file.

**Expected behavior**
The links should redirect to the documentation but they just go to 404.

**Comment by ThunderBolt-OS** [comment]
hello there, i would like to take up this issue and resolve it. Please assign this is issue.

**Comment by Pragya2056** [comment]
Please assign this issue to me.

**Comment by nomio19** [comment]
@ThunderBolt-OS @Pragya2056  assigned to you guys. Good Luck.

**Comment by Pragya2056** [comment]
@nomio19 
I have created a PR for this - #3793 .
Please review it.

**Comment by Pragya2056** [comment]
There were two links that led to 404 error and I have fixed both.

**Comment by Pragya2056** [comment]
If it is valid, this issue can be closed.

**Comment by Pragya2056** [comment]
This issue can be closed now.
