### ISSUE TITLE
sent attachment is not working in inbox

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#3621]
![Image](https://user-images.githubusercontent.com/111424957/189837858-fb9bfcd9-0234-486c-93a6-06ac088268d5.png)

![Image](https://user-images.githubusercontent.com/111424957/189837932-402505d1-999c-4458-a3ca-e3f55234a374.png)

**Comment by bnomio19** [comment]
What about this issue's priority? @Amura07

**Comment by Amura07** [comment]
This issue fixed
