### ISSUE TITLE
Imrovements of web builder template's design

### ISSUE THREAD

**Issue by bnomio19** [erxes/erxes#3631]
- [ ] Restaurant
- [ ] Auto-service
- [ ] Online-shop

**Comment by lneez12** [comment]
Online Shop Template 1th 

- [ ] Home Page
- [ ] Product  Page
- [ ] Payment Page

**Comment by lneez12** [comment]
Loading Page UI Design

**Comment by lneez12** [comment]
Online Shop UI Design (1)
-[ ] Online Shop (1)

**Comment by lneez12** [comment]
Erxes.io Web builder Template UI design Currently total (3)

**Comment by lneez12** [comment]
Coming soon Page (1)
