### ISSUE TITLE
Segment's code refactor

### ISSUE THREAD

**Issue by Mambatukaa** [erxes/erxes#3632]
convert segments static association types and segment types to dynamic.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/56122037/191902320-afb87f81-911a-4195-a2b0-850a21332ac4.png">
<img width="413" alt="image" src="https://user-images.githubusercontent.com/56122037/191902380-99300f2e-5b87-4c94-ae55-1fd0cec32a0b.png">

- [x] refactor content types
- [x] refactor association types
- [x] refactor indexesTypeContentType

**Comment by Enkhtuvshin0513** [comment]
[close ](https://github.com/erxes/erxes/commit/d0d48fe178aba095ff7ed98e7328a2eeb6568c6f)
