### ISSUE TITLE
Allow taking value from Conversation/Form to do automation

### ISSUE THREAD

**Issue by toaitrancodihaus** [erxes/erxes#3663]
**Is your enhancement request related to a problem? Please describe.**
Scenerio:
Given: We already have a "Request call back form", using Form feature
AND:
Given: We already have automation task, "Create a ticket when user submit"
When: User submit the form
Then: The automation task should create a ticket, with values from form data

**Additional context**
- Usually, other solutions would allow us to take field_id as reference to take value from form submission.
- In our "Acton > Create ticket", we should allow to use variable {field_xxxx} to get data from submitted form.
- It would clearer, like, Create a ticket with "Visitor with phone {form_123_field_xxx} need a callback", would be clearer.

**Comment by bnomio19** [comment]
How long does it take to make this enhancement? Is it possible to do? @batamar
