### ISSUE TITLE
Should allow hooks to render additional components/context on several pages

### ISSUE THREAD

**Issue by toaitrancodihaus** [erxes/erxes#3664]
**Is your feature request related to a problem? Please describe.**
Scenario: Developer want to create additional plugin
GIVEN: Developer want to show a custom button on Header/Conversation detail
WHEN: Developing the plugin
THEN: He should be able to register a custom button, with specific action (click on button will do something)
AND: Erxes core UI will understand and render that button as registered via hooks.

**Describe the solution you'd like**
- Erxes provide a list of hooks, where the developer and hook into it and do his desired actions
- Can follow this https://developer.wordpress.org/plugins/hooks/actions/, https://reactjs.org/docs/hooks-custom.html

**Comment by bnomio19** [comment]
Do you guys this this request is possible? Or can we solve it in an easier way? @Anu-Ujin @batamar

**Comment by toaitrancodihaus** [comment]
Basically, we need a way to render a button at specific location, without modifying your core.
We just need to register where to render the button (base on your allowed places), and what should it do.

Hook in WordPress is a way to help developer extend the feature without modifying the core, we can learn from them for more idea @bnomio19 @batamar

**Comment by bnomio19** [comment]
Well, this is possible. Our senior FE developer @Anu-Ujin will guide you on where to do it. And you guys need to clarify your requirements.

**Comment by toaitrancodihaus** [comment]
For whichever you need me to clarify, please let me know.

**Comment by bnomio19** [comment]
Where and how your button will be located, what action it is intended to perform, etc. Prefferedly, mockup&wireframe would be even great. @toaitrancodihaus
