### ISSUE TITLE
Allow link click tracking in Campaigns

### ISSUE THREAD

**Issue by toaitrancodihaus** [erxes/erxes#3666]
Scenario: User send email marketing campaigns
GIVEN: User composed an automated email marketing campaign, in the email has a link
AND
GIVEN: User sent the campaign
WHEN: Receiver open or click the links
THEN: We should log this into campaign property, so we can do other actions in autmation marketing campaign.

========
Possibilities:

- If user opened email, wait X day to send another email
- If user click email, increase the score.

Something like this, for automated email marketing campaign.

**Comment by bnomio19** [comment]
At the moment, we know how many clicks out of the total number of people who have sent an email, but we cannot know exactly which user is clicking. Our Senior BE developer @Buyantogtokh will respond on whether the user can be recognized and whether it is possible to add score etc.

**Comment by Buyantogtokh** [comment]
@bnomio19 @toaitrancodihaus we already know which customer has opened or clicked on the email of a campaign. The automation might require additional coding.
