### ISSUE TITLE
Clarification on license & usage of "Open Source"

### ISSUE THREAD

**Issue by ssddanbrown** [erxes/erxes#3667]
Hi :wave:,

I originally [posted this in the discussions](https://web.archive.org/web/20220830185114/https://github.com/erxes/erxes/discussions/3552) but looks like they've since been removed, so am just opening an issue to raise the same query.

I saw in your license you have the following lines:

> Content outside of the above mentioned directories or restrictions above is available under the "AGPLv3" license as defined below.
> erxes is not permitted to be hosted as a SaaS version to compete with erxes Inc.

Does that last line represent an extra license condition, upon the rights given by the AGPLv3, or does it represent your understanding of the AGPLv3?

Just asking since the last line goes against the [Open Source Definition](https://web.archive.org/web/20220830185114/https://opensource.org/osd) and would make this license, and therefore project, be generally considered as not Open Source by many. Although, looking back, you [used to use](https://github.com/erxes/erxes/blob/8d578e9fdb093c2f6155a139b445ca1fa81c060a/LICENSE.md) the common clause which would also not be considered Open Source.

**Comment by ssddanbrown** [comment]
Just found #2538, which appears to be related albeit not specific to the queried lines.

**Comment by marclaporte** [comment]
@ssddanbrown is correct. As of now, Erxes is not Open Source. So every time the term is indicated on the site, it is false advertising. So you have to stop using the term Open Source or change the license to one of the approved OSD licenses.

Instead of Open Source, you can use the term "source available".
