### ISSUE TITLE
link not found error

### ISSUE THREAD

**Issue by ADITYADAS1999** [erxes/erxes#3701]
at the documentation section both three links throw error or the linked page can not be found here

![7845](https://user-images.githubusercontent.com/58718316/193408546-2ac409d9-3327-4208-8e12-4c82acd7ae38.PNG)

**Comment by nomio19** [comment]
Hello @ADITYADAS1999, our Sr.FE developer @Anu-Ujin will update and correct these links.

**Comment by ADITYADAS1999** [comment]
Thanks for the information [nomio19](https://github.com/nomio19)

**Comment by Anu-Ujin** [comment]
Hello @ADITYADAS1999, Where did you take this screenshot from? Maybe you found this in our old develop branch's readme? We updated our readme in master branch but not yet in the develop branch. I apologize for bothering you with misguide. 

Our documentation link has changed to https://docs.erxes.io/docs/intro
You can find installation documentation from here https://docs.erxes.io/docs/category/installation

And our latest update is in master branch.

Thanks!

**Comment by ADITYADAS1999** [comment]
> Hello @ADITYADAS1999, Where did you take this screenshot from? Maybe you found this in our old develop branch's readme? We updated our readme in master branch but not yet in the develop branch. I apologize for bothering you with misguide.
> 
> Our documentation link has changed to https://docs.erxes.io/docs/intro You can find installation documentation from here https://docs.erxes.io/docs/category/installation
> 
> And our latest update is in master branch.
> 
> Thanks!

Thanks for guide and provide the links [Anu-Ujin](https://github.com/Anu-Ujin)
