### ISSUE TITLE
Error loading config file: /root/.docker/config.json

### ISSUE THREAD

**Issue by novastream** [erxes/erxes#3702]
I'm trying to install erxes but I'm stuck on step 16.
_sudo npm run erxes deploy-dbs_

I get the following error:
[erxes_error.txt](https://github.com/erxes/erxes/files/9692358/erxes_error.txt)

It do work if I run the command without sudo but then elasticsearch gets permissions errors. Don't know if it's related?

Checklist:
- I've created a new user named erxes
- I've added user erxes to both sudo and docker groups
- I can run docker hello-world with and without sudo
- I've tried everything a couple of times and on newly installed OS:es
- /root/.docker/config.json does not exist

System:
OS: Ubuntu 22.04 LTS
Docker: 20.10.18
Docker-compose: 2.10.2

**Comment by nomio19** [comment]
Hello, @novastream. Our BE developer @Enkhtuvshin0513 will guide you to finish this installation.

**Comment by novastream** [comment]
Thanks @nomio19 

I got passed the issues above, the user running erxes needs to have id 1000 (first added user).

Now I'm stuck that nothing seems to be able to connect to the Redis server.

**Comment by nomio19** [comment]
Afternoon @novastream, we are updating our installation process document. So, will you wait for a new update?

**Comment by novastream** [comment]
@nomio19 yes of course, do you have an approximately timeframe? Like is it this week, month?

**Comment by nomio19** [comment]
@novastream I think, it will take 2 weeks at most.
