### ISSUE TITLE
Email integration is not working

### ISSUE THREAD

**Issue by SUCHITRAGIRI** [erxes/erxes#3718]
**Describe the bug**
I can't able do email integration for my channel. It is showing something unexpected.

**To Reproduce**
1. Go to 'integration'
2. Click on 'gmail'
3.  Then it shows the linked account option but the button for signin with google is not working
4. See error below!

**Screenshots**
![Screenshot (1092)](https://user-images.githubusercontent.com/60110218/194750378-be57315b-7661-4339-a9d1-f77b187e55b6.png)

**Context (please include the related information if applicable):**
 - OS: [Windows 10]
 - Browser version [chrome Version 106.0.5249.103 (Official Build) (64-bit)]
 - erxes using from web

Please help me out!

**Comment by SUCHITRAGIRI** [comment]
@erdenezul @maxnowack @munkhorgil @batnasan 
Please look into it..

**Comment by nomio19** [comment]
Hello @SUCHITRAGIRI, email integration is currently not working and we are making improvements. Our CTO @batamar will notify you as soon as the update is available.
