### ISSUE TITLE
Some links are not Working

### ISSUE THREAD

**Issue by VanshajPoonia** [erxes/erxes#3719]
![image](https://user-images.githubusercontent.com/74147463/194767073-bb5d9320-6390-4750-ae45-fe8b0003fbf2.png)
These link on the URL https://erxes.io/resource-center are NOT working

**To Reproduce**
1. Go to https://erxes.io/resource-center'
2. Click on any of the links that were there in the pic attached above on the left-hand side
3. See NGINX error

**Expected behavior**
The link should have taken the user to the destination

**Screenshots**
![image](https://user-images.githubusercontent.com/74147463/194767163-551f2dc3-4921-4c29-948a-c70ddb073194.png)

**Comment by nomio19** [comment]
Hello @VanshajPoonia, thanks for letting us know.

**Comment by nomio19** [comment]
@enkhzule, please correct these links.

**Comment by nomio19** [comment]
@enkhzule  any update on this issue?

**Comment by enkhzule** [comment]
@VanshajPoonia @nomio19  fixed

**Comment by nomio19** [comment]
Thank you @enkhzule 🥳.
