### ISSUE TITLE
Document/editor/ plugin

### ISSUE THREAD

**Issue by ghost** [erxes/erxes#3722]

**Comment by nomio19** [comment]
Hello @lightii , please split your issue into a detail.

**Comment by lightii** [comment]
Sprint 6 -2
Contract plugin
- [ ] contract add, edit, delete/api && ui/
- [ ] contract-template add edit delete/api && ui/

**Comment by lightii** [comment]
1. You can add contract and contract category
2. It could add contract template, get attribute from customer
3. You can choose contract templates on contract form. Get query from queryParams

- [ ] contract form, choose contract templates depends on contract category

**Comment by nomio19** [comment]
Sprint #9
