### ISSUE TITLE
Cards plugin -  Default assignee should be assignee who created card/task, ticket, deal/.

### ISSUE THREAD

**Issue by ghost** [erxes/erxes#3734]
**Is your enhancement request related to a problem? Please describe.**
Yes, new created task has no info. I have to click on the task to know which team member created that task.

**Describe the solution you'd like**
When create a new task, the default assignee should be the assignee who created it.

**Comment by KACHIDA** [comment]
Hi @nomio19 , I'm interested in looking on to this issue, can you please assign me this task.

**Comment by nomio19** [comment]
Sure! Assigned to you @KACHIDA, good luck :D
