### ISSUE TITLE
When i click on "Choose User", the first option should be "me". 

### ISSUE THREAD

**Issue by ghost** [erxes/erxes#3735]
**Is your enhancement request related to a problem? Please describe.**
To assign myself on task, i have to write my name and search. 

**Describe the solution you'd like**
When i click on "Choose User", the first option should be "me". 

**Additional context**

<img width="1004" alt="Screen Shot 2022-10-12 at 15 04 57" src="https://user-images.githubusercontent.com/44166880/195273195-8c3f9434-30f9-4948-b2b3-d44e340889df.png">

**Comment by jsvigneshkanna** [comment]
Assign me this issue

**Comment by nomio19** [comment]
@jsvigneshkanna assigned to you, GoodLuck!

**Comment by jsvigneshkanna** [comment]
@nomio19 , As there is no docs to install erxes locally and start working, I couldnt take this issue fix.

**Comment by nomio19** [comment]
@jsvigneshkanna  https://docs.erxes.io/ here is the install documentation of erxes.

**Comment by nomio19** [comment]
@jsvigneshkanna hello?

**Comment by TechTarun** [comment]
Can you please assign this issue to me?

**Comment by nomio19** [comment]
@TechTarun assigned to you. Good luck!

**Comment by RishivikramN** [comment]
Is this issue still open?
