### ISSUE TITLE
Ticket improvement on client portal

### ISSUE THREAD

**Issue by UnaBat** [erxes/erxes#3750]

**Comment by nomio19** [comment]
@UnaBat Please fulfill your issue by **Enhancement request** format.

**Comment by UnaBat** [comment]
Improvements need to be done. 
Private ticket status should named as stage name. And date should be seen on client portal after client logged in. 
Also LOG OUT button need to be seen, now Account icon has been pressed as log out button, guess its UI bug. 

So ticket fields that have to be filled by client are -Created date, -Status, -Note from assigned one.



![Image](https://user-images.githubusercontent.com/104477660/196410606-15f08133-615d-4056-becc-42fdbb0f067b.png)
