### ISSUE TITLE
Improvements of plugin's document

### ISSUE THREAD

**Issue by nomio19** [erxes/erxes#3763]

**Comment by Mambatukaa** [comment]
Create plugin command improvement:

- [ ] Convert ui template to OS like structure. (Default, Empty)
- [ ] Convert api template to OS like structure. (Default, Empty)

Create integration plugin command development:

- [ ] Add integration api template
- [ ] Add integration ui template


Create plugin documentation improvement:

- [ ] Describe plugn files
