### ISSUE TITLE
Correct the logic of property group config

### ISSUE THREAD

**Issue by ghost** [erxes/erxes#3783]
**Describe the bug**

The properties are displayed incorrectly on the pipeline specified in config. For example: properties selected as **visible to create** are visible only on the **configured pipeline**, on other pipelines there is only the **name**.

**To Reproduce**
1. Go to 'properties'
2. Click on 'Tickets'
3. Click on  'basic info'
4. Set the config to the 'property group'
5. Go to 'ticket'
6. Click on 'Add a ticket'
7. See error

**Expected behavior**
Those fields should be visible only on the configured pipeline. 

**Screenshots**

<img width="505" alt="Screen Shot 2022-10-31 at 13 11 25" src="https://user-images.githubusercontent.com/44166880/198935850-03a325d3-2df4-4b07-89a5-8a892181005c.png">

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [e.g docker, manual]

**Additional context**
**Visible to create**

**Comment by nomio19** [comment]
Sprint #8

**Comment by nomio19** [comment]
Sprint #10
