### ISSUE TITLE
becomes empty when converting to ticket

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#3790]
**Describe the bug**
becomes empty when converting to ticket

**To Reproduce**
1. Go to 'inbox'
2. Click on 'convert to ticket'
3. Fill in the some fields 
4. If customer write something when i fill in the fields, it start again all fields become empty

**Expected behavior**
I don't wanna anymore be empty again while I have filled it

**Screenshots**
It's impossible

**Context (please include the related information if applicable):**
 - OS: [e.g. Ubuntu 16.04]
 - Browser version [e.g. chrome 75.0.3770.142 safari  12.1.1]
 - erxes version [e.g. 0.9.17, 0.9.16]
 - installation type [e.g docker, manual]

**Additional context**
https://www.loom.com/share/744433af99ed49049adc8b33bfb2acba

**Comment by nomio19** [comment]
Sprint #9
