### ISSUE TITLE
Client portal - improvements

### ISSUE THREAD

**Issue by ghost** [erxes/erxes#3798]
@Ariunboldburentsogt please add details of this issue

**Comment by Ariunboldburentsogt** [comment]
1.  Add ticket fields

- Ticket Name
- Ticket Number (Configuration Number)
- Ticket Priority
- Ticket Attachments
- Ticket Custom Fields
- Ticket Status (Stage Name)
- Customer messages (for every cards plugin)
- Client Portal overall UI

2. Track tickets with number
