### ISSUE TITLE
Find and replace all the dead links in the system

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#3834]
**Is your enhancement request related to a problem? Please describe.**

**Describe the solution you'd like**

Audio explanation: https://www.loom.com/share/a6a289d319394b4781cd73589fde72e1

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by nomio19** [comment]
First of all, we need to find exactly where the dead link is. @mendorshikh

**Comment by Amura07** [comment]
**OPEN SOURCE*

System config

1. File upload
2. Google Cloud Storage
3. AWS S3
4. AWS SES
5. Common mail config
6. Custom mail service

Integrations config

1. Facebook
2. Twitter
3. Nylas
4. Video call
5. Sunshine Conversations API
6. WhatsApp Chat-API

Campaign config

1. General settings

**SAAS**
General system config

1. File upload

Integrations config

1. Facebook
2. Twitter
3. Nylas
4. Video call
5. Sunshine Conversations API
6. WhatsApp Chat-API

Campaign config

1. General settings

**Comment by nomio19** [comment]
Sprint #10
