### ISSUE TITLE
add properties basic info in cards plugin

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#3841]
<img width="1036" alt="Screenshot 2022-11-18 145749" src="https://user-images.githubusercontent.com/111424957/202640719-9e4cad56-f3e2-4ba0-825c-34556a4e18e0.png">
<img width="1051" alt="Screenshot 2022-11-18 145730" src="https://user-images.githubusercontent.com/111424957/202640727-722543bb-9b4b-448d-9788-2beec46adc6b.png">

**Comment by nomio19** [comment]
Sprint #10
