### ISSUE TITLE
Typo within current erxes onboarding welcome page

### ISSUE THREAD

**Issue by luunamjil** [erxes/erxes#3879]
Should be:

"User Guide"
"Feature guides for the core erxes platform and native plugins."

![Screenshot 2022-11-30 151648](https://user-images.githubusercontent.com/56472207/204732475-a27617f4-6137-4f57-bb63-65783f9ae12b.png)

**Comment by MohamedMafaz** [comment]
Please assign me this issue I'll fix it

**Comment by nomio19** [comment]
Hi @MohamedMafaz , assigned to you. Good luck :D

**Comment by bakhtiarcr7** [comment]
@nomio19 please review

**Comment by MohamedMafaz** [comment]
Can I start working in this issue

**Comment by MohamedMafaz** [comment]
I need to fix it because this issue was assigned to me

**Comment by surajdubey08** [comment]
Hi,

I see the issue was opened and no progress was shown since last few months. Hence I did the required fix and linked a pull request following the contributing guidelines. Please check the linked PR.

Thank You.
