### ISSUE TITLE
Integration with instagram

### ISSUE THREAD

**Issue by nomio19** [erxes/erxes#3902]
Getting Started: https://docs.erxes.io/docs/developer/developing-integration-plugins
Sample IMAP or Facebook messenger integration plugins can be found: https://github.com/erxes/erxes-community/tree/dev/packages
Instagram Messaging API: https://developers.facebook.com/docs/messenger-platform/instagram/

**Comment by MohamedMafaz** [comment]
Hey @mendorshikh 
I can't get what are you saying? Can you please provide me some more info about it?
