### ISSUE TITLE
Campaign not working with an attached file.

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#3915]
Error occurred while sending email to info@erxes.io: ENOENT: no such file or directory, open '0.8339429158913052Deal_TEst_-_Sheet1_5.csv'

<img width="1043" alt="Screenshot 2022-12-08 140445" src="https://user-images.githubusercontent.com/111424957/206370020-3f1afdaa-cbc4-447e-bfbc-112f558483aa.png">

**Comment by Mambatukaa** [comment]
The campaign cannot read files when uploading files with local and private configurations. 

The readFileUrl function is needed to fix this issue.

- [ ] Add readFileUrl function
- [ ] Test on local
- [ ] Test on server
