### ISSUE TITLE
Teammember & Premissions are empty /always refresh/

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#3934]
teammember invite hiij hadgalahaar zaaval refresh hiihgui bol ingeed haragdahgui bolood bgaa. mon edit hiichiheed hadgalahaar bas haragdahgui bolchihdog. bainga refresh hiij baij garch ireed bgaa

![image](https://user-images.githubusercontent.com/111424957/207486723-1a76ae7d-7b69-4d53-98b1-e6ed886ed706.png)
https://www.loom.com/share/7e2c0afa6ace4dea83978319aa291fbe

**Comment by Mambatukaa** [comment]
- [ ] Fix
- [ ] Test on local
- [ ] Test on the server

**Need to update core, and other plugins.**
