### ISSUE TITLE
integrate with Linkedin Sales Navigator 

### ISSUE THREAD

**Issue by batmunkh2022** [erxes/erxes#3937]
I want to integrate Erxes CRM with Linkedin Sales Navigator to collect and nurture our leads.

**Comment by nomio19** [comment]
Hello @batmunkh2022 , for sure you can develop this. Here's the https://docs.erxes.io/docs/developer/developing-integration-plugins/ creating integration plugin's guide. If you have any question, feel free. Good luck :)

**Comment by nomio19** [comment]
https://discord.com/invite/aaGzy3gQK5 Join our discord server.

**Comment by nomio19** [comment]
Hi @batmunkh2022, i hope you are doing well, any update on this issue?
