### ISSUE TITLE
Assigned user is not showing on card item - Saas

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#3973]
<img width="220" alt="image" src="https://user-images.githubusercontent.com/111424957/209507900-d0402fc0-d064-48c0-b884-7c232fd17bc5.png">
<img width="772" alt="image" src="https://user-images.githubusercontent.com/111424957/209507936-53bfdedd-82c0-4c42-bd23-bcc8d5b87a14.png">

**Comment by Mambatukaa** [comment]
- [ ] Fix
- [ ] Test on local
- [ ] Test on server
