### ISSUE TITLE
Error in newsletter

### ISSUE THREAD

**Issue by MohamedMafaz** [erxes/erxes#3984]
I saw the home screen and noted that insert your email is not the right word. It need to be something like Enter your Email.

**Comment by MohamedMafaz** [comment]
Please assign me this issue I'll work on this

**Comment by Ariunboldburentsogt** [comment]
Changed the word

**Comment by MohamedMafaz** [comment]
I found this mistake to make contribution. but you did it. why

**Comment by nomio19** [comment]
Noted, thank you @MohamedMafaz  :)

**Comment by nomio19** [comment]
Hello @MohamedMafaz , sorry for this. You can contribute our "Erxes Inc" project's Quick Win, Help Wanted labelled issues.

**Comment by nomio19** [comment]
Hi @Ariunboldburentsogt , next time please let me know if you notice any issues.
