### ISSUE TITLE
It seems Please select a public task board first when i create client portal 

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#3996]
![image](https://user-images.githubusercontent.com/111424957/210297033-3196f6a4-c9f5-4643-b273-f7bc14313e70.png)

**Comment by Mambatukaa** [comment]
This improvement was added by this [commit](https://github.com/erxes/erxes/commit/fe72436567ef7ef51956237062a1cc4ac5abb038).

- [ ] Fix
- [ ] Test on local
- [ ] Test on the server

**Need to update client portal ui to make it possible to save without a public task.**
