### ISSUE TITLE
Tasks stage order is not showing right in client portal

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#3998]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/111424957/210298407-98f36af5-cab6-46a0-8765-50b7c0328a01.png">
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/111424957/210298537-83d10277-f71a-490f-baa8-29c538e0e94e.png">

**Comment by Mambatukaa** [comment]
- [ ] Fix an issue
- [ ] Test on local
- [ ] Test on server
