### ISSUE TITLE
Company segment too haragdahgui bga

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#3999]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/111424957/210303095-cc9aaa00-ea17-4358-a8b6-6fcdc9bacdcf.png">

**Comment by Mambatukaa** [comment]
**Fixed by this [commit](https://github.com/erxes/erxes/commit/217f4064e4f1d63cd4f8a500654608c27308d98a).**

- [ ] Fix
- [ ] Test on local
- [ ] Test on the server

**Need to update contacts ui to fix that issue**
