### ISSUE TITLE
Erxes XOS App bugs & Improvements

### ISSUE THREAD

**Issue by Munkhorgilb** [erxes/erxes#4000]

**Comment by Munkhorgilb** [comment]
1/3 

- [ ] Pin not working
- [ ] App crashes when click on customer

**Comment by mendorshikh** [comment]
1. Enhancement: Alerts should fade away: https://share.cleanshot.com/wDtdHNq1. Now it is sticking there. Making ppl click first, and then it fades away.
2. Bug: Error message when choosing options on the custom properties fields: https://share.cleanshot.com/6Bx3Zjkd video of the bug: https://www.loom.com/share/32383a78aee945cea2507c43d2ec8736
3. Bug: https://www.loom.com/share/f637d2a254654ffe9b46f0eb060b524a 3.1) Not showing tasks that I can relate 3.2) Crashing.
4. Questionable: https://www.loom.com/share/800aac1d770d4f92895a826100c430de. Not sure where to fix it. On knowledgebase?
5. Bugs: https://www.loom.com/share/54debb39b1d6483eaa1d64b6009a2226 Explained on video.
6. Bugs: https://www.loom.com/share/6c92999a16324bb187c198fb44e22723 In this video, there are lots of bugs. Please pause and see every single bug. 

@Munkhorgilb Please take a look above findings.

**Comment by Munkhorgilb** [comment]
- [ ] Related Task,Ticket bug
- [ ] Assign bug
- [ ] Profile edit bug
- [ ] Note delete
- [ ] UOM Default

**Comment by Munkhorgilb** [comment]
- [ ] Product is used not working

**Comment by Munkhorgilb** [comment]
Contacts refactor

**Comment by Munkhorgilb** [comment]
- [ ] Inbox, Cards filter new UI redesign

**Comment by Munkhorgilb** [comment]
- [ ] First login white screen bug(Permission)

**Comment by Munkhorgilb** [comment]
- [ ] UI, UX Improvement
