### ISSUE TITLE
Client Portal improvement

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#4014]
1. I must do refresh when i create ticket
2. Description
3. Show Probability /inprogress, resolve/

**Comment by Mambatukaa** [comment]
Need to add a comment section.

**Comment by Mambatukaa** [comment]
**Checklists:**
- [x] Add database model of comment in client portal plugin.
- [x] Add a comment section on the client portal.
- [x] Add a comment section on the ticket feature.
- [x] Remove unnecessary codes and refactor.
- [x] test on local computer
- [ ] test on server
- [ ] publish
