### ISSUE TITLE
Cards related customer isn't show email icon

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#4023]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/111424957/211232058-cd034b62-2be9-4b3a-a879-405966f6a4da.png">
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/111424957/211232102-2b1c0c5d-7591-4b48-a885-29df77653535.png">

**Comment by Mambatukaa** [comment]
Fixed by this [commit](https://github.com/erxes/erxes/commit/632788f9cd3ab07de9140094dd45bfd065af80bd).

- [ ] Fix
- [ ] Test on local
- [ ] Test on the server

**Need to update cards-ui, contacts-ui, and emailtemplates-ui to fix this issue.**
