### ISSUE TITLE
Card improvement

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#4026]
I wanna show archive card in contact
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/111424957/211282356-c8386ece-7bf7-4a89-9618-45466420fc6e.png">

**Comment by Mambatukaa** [comment]
Added by this [commit](https://github.com/erxes/erxes/commit/26d562bedfe558d66ef47ffce419e9cc9371d236).

- [ ] Possible to show archived items in contacts detail
- [ ] Test on local
- [ ] Test on the server

**Need to update cards ui and api on the server.**
