### ISSUE TITLE
Reports-Enhancement

### ISSUE THREAD

**Issue by Ariunboldburentsogt** [erxes/erxes#4029]
**Is your enhancement request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by Ariunboldburentsogt** [comment]
-Product Quantity
-Team inbox-Response time
-Cards time tracking
-Deal total amount
-Company reports

**Comment by Enkhtuvshin0513** [comment]
https://github.com/erxes/erxes/pull/4111
