### ISSUE TITLE
Fix & improve "Response Templates" -> Search section

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#4050]
Fix & improve "Response Templates" -> Search section

Watch the screen recording here: https://jam.dev/c/464ef302-fec1-4168-bece-4233aba48816

**Website URL:**
[https://office.erxes.io/inbox/index?_id=2aQkEXdbATbGxbLpt](https://office.erxes.io/inbox/index?_id=2aQkEXdbATbGxbLpt)

**Device and browser info:**
Chrome 108.0.0.0 (1920x976) | Mac OS 10.15.7

**Date and time:**
January 12th 2023 | 2:58am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/464ef302-fec1-4168-bece-4233aba48816](https://jam.dev/c/464ef302-fec1-4168-bece-4233aba48816)

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by Mambatukaa** [comment]
Checked, but working with no problem.

![response template searching](https://user-images.githubusercontent.com/56122037/217701959-71878747-2a46-4c5f-b341-b4e386b202ee.gif)
