### ISSUE TITLE
Reports improvement in conversation

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#4058]
- add first response time
- add resolve time
- time uudin haragdatsig saijruulah
- Amount uudin haragdatsig saijruulah
- Viewing time by hour and minute is currently showing only numbers
<img width="218" alt="image" src="https://user-images.githubusercontent.com/111424957/212015787-f3ebade1-6939-4e82-a1d5-3516193d7d67.png">
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/111424957/214041987-ceaff9bb-8d1f-4838-88c1-a10d3f9dafd7.png">

**Comment by Enkhtuvshin0513** [comment]
closed by https://github.com/erxes/erxes/pull/4111
