### ISSUE TITLE
contact link bug

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#4065]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/111424957/212640456-f2e60357-e463-47dd-9ba1-30881ca3e460.png">

**Comment by Mambatukaa** [comment]
Fixed by this [commit](https://github.com/erxes/erxes/commit/247c27e30490f9b27fc19573e1ab56cd44c4e898).

- [ ] Fix
- [ ] Test on local
- [ ] Test on the server

**Need to update contacts ui to fix this issue.**
