### ISSUE TITLE
Cards confic

### ISSUE THREAD

**Issue by Aanaamaanaa** [erxes/erxes#4107]

**Comment by Aanaamaanaa** [comment]
![Image](https://user-images.githubusercontent.com/111912525/214810163-1805b6cb-af20-4dfb-9e75-14c22e6e9752.png)


![Image](https://user-images.githubusercontent.com/111912525/214810812-6e34c081-d555-4ae9-b7a0-996c77b1fcad.png)


Pipeline confic -> Visibility -> Choose department geed department songohoor tuhain department-d baigaa team members-d pipeline haragdaj baigaa bolovch cardruu oroh geheer permission required geed baigaa.
Pipeline confic -> Visibility -> Choose team member ued bol zugeer ajillaad baigaa.

**Comment by Mambatukaa** [comment]
**The issue fixed by this [commit](https://github.com/erxes/erxes/commit/bc7214f14d1384223452c0ed1cf016733469d33b).**

- [x] Fix
- [x] Test on local.
- [x] Test on the server.

**Need to update cards api to fix this issue.**
