### ISSUE TITLE
Unsubscribe is not working

### ISSUE THREAD

**Issue by Ariunboldburentsogt** [erxes/erxes#4109]
![Image](https://user-images.githubusercontent.com/105905631/214835271-23729529-65ca-431b-a351-85df466c815d.png)

**Comment by Mambatukaa** [comment]
**Fixed by this [commit](https://github.com/erxes/erxes/commit/39db01dc5f0667984732f08100447cf1393a5f21).**

- [ ] Fix
- [ ] Test on the server

**Need to update engages-api and core-api to fix this issue.**
