### ISSUE TITLE
Brand name is not showing on Responses

### ISSUE THREAD

**Issue by Ariunboldburentsogt** [erxes/erxes#4119]
![Image](https://user-images.githubusercontent.com/105905631/215275860-580ab0ab-d3b8-417a-9035-f998f156a68c.png)

**Comment by Mambatukaa** [comment]
**Fixed by this [commit](https://github.com/erxes/erxes/commit/560ad520c7f676e917c31c68884c7603c4778f31).**

- [ ] Fix.
- [ ] Test on local computer.
- [ ] Test on the server.

**Need to update inbox-api to fix this issue.**
