### ISSUE TITLE
Add required icon in code field

### ISSUE THREAD

**Issue by Ariunboldburentsogt** [erxes/erxes#4121]
![Image](https://user-images.githubusercontent.com/105905631/215276053-7bacc570-2641-44a6-83cd-d17a3a735b95.png)

**Comment by Mambatukaa** [comment]
**Fixed by this [commit](https://github.com/erxes/erxes/commit/40384d2946b9065ab4e05e44a3c4387f0f714fcb).**

- [ ] Fix.
- [ ] Test on local.
- [ ] Test on the server.

**Need to update core-ui to fix this issue.**
