### ISSUE TITLE
Add product price

### ISSUE THREAD

**Issue by Ariunboldburentsogt** [erxes/erxes#4127]
![Image](https://user-images.githubusercontent.com/105905631/215383466-c0937563-b67b-4b05-80c9-937a50b8fb26.png)

**Comment by Mambatukaa** [comment]
**Updated by this [commit](https://github.com/erxes/erxes/commit/4a61a4dd408b9c7d675bf761a2a8feff2be6ab36).**

- [ ] Update.
- [ ] Test on local.
- [ ] Test on the server.

**Need to update cards-ui to fix this issue.**
