### ISSUE TITLE
INBOX > FILTER by DATE / NOT WORKING / UNfiltered conversations

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#4144]

**Comment by mendorshikh** [comment]
@Amura07 Please retest it on office. It works for me. Or record it using https://chrome.google.com/webstore/detail/jam/iohjgamcilhbgmhbnllfolmkmmekfmci

**Comment by Mambatukaa** [comment]
@mendorshikh @Amura07 this issue is the duplicate of #4160.
