### ISSUE TITLE
Tag counts empty in form

### ISSUE THREAD

**Issue by Amura07** [erxes/erxes#4170]
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/111424957/218270624-6bcbd683-c816-4da3-b46f-c85ef3bb3b75.png">

**Comment by Mambatukaa** [comment]
**This issue was fixed by this [commit](https://github.com/erxes/erxes/commit/eaf6bd3960196ac370fd8787e1c073d131c7567e).**

- [ ] Fix.
- [ ] Test on local computer.
- [ ] Test on the server.

**Need to update inbox-api to fix this issue.**
