### ISSUE TITLE
[DEV-47] Do you know if IMAP does not currently work?

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#4202]
I tried to set it up, and I keep receiving the following in the IMAP docker container: 

**on imap.once ============= Error: connect ECONNREFUSED 127.0.0.1:993 at TCPConnectWrap.afterConnect \[as oncomplete\] (net.js:1159:16) { errno: -111, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1',  port: 993, source: 'socket'**

<sub>From [SyncLinear.com](https://synclinear.com) | [DEV-47](https://linear.app/erxes/issue/DEV-47/do-you-know-if-imap-does-not-currently-work)</sub>

**Comment by mendorshikh** [comment]
Testing if the comment goes to github

**Comment by mendorshikh** [comment]
Testing if the GitHub comment goes to the Linear

**Comment by mendorshikh** [comment]
Both syncs

**Comment by NorkzYT** [comment]
Any update on this issue? I need to be able to use IMAP as soon as possible.
