### ISSUE TITLE
FB post -> Convert to deal -> "Conversation not found" error

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#4241]
**Describe the bug**
Please watch the video: https://jam.dev/c/68372906-e346-4d3e-8efb-a4f9dfd0eb69

**To Reproduce**
1. Go to 'FB post'
2. Click on 'Conver'
3. Click on 'Deal'
4. Fill out the form
5. Hit "Save"
6. You will see the "Conversation not found error"

**Comment by Enkhtuvshin0513** [comment]
@Ariukasq1
