### ISSUE TITLE
[DEV-51] Show FB post picture full & make it clickable

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#4242]
**Describe the bug**
Please see the screenshot: https://jam.dev/c/fea96b45-6eac-4ef7-94a2-b1f75914ffaf

There are two bugs:

1. FB Post picture should be seen in full.
2. FB Post pictures should be at least clickable to view.

<sub>[DEV-51](https://linear.app/erxes/issue/DEV-51/show-fb-post-picture-full-and-make-it-clickable)</sub>

**Comment by Enkhtuvshin0513** [comment]
@Ariukasq1
