### ISSUE TITLE
Integration with Slack

### ISSUE THREAD

**Issue by ghost** [erxes/erxes#4253]

**Comment by vludrani** [comment]
Is there an update for the slack integration?

After referring to [this comment](https://github.com/erxes/erxes/issues/1795#issuecomment-665584091), I tried visiting the [public roadmap](https://roadmap.erxes.io/). And it seems the link is not publicly accessible.

So, is the slack integration complete?
If so, is there a resource with relevant documentation?
If not, what could be the ETA?

Thanks.
