### ISSUE TITLE
Integration with Linkedin Messaging

### ISSUE THREAD

**Issue by ghost** [erxes/erxes#4254]
Getting Started: https://docs.erxes.io/docs/developer/developing-integration-plugins
Sample IMAP integration plugins can be found: https://github.com/erxes/erxes-community/tree/dev/packages
Linkedin Messages API: https://learn.microsoft.com/en-us/linkedin/shared/integrations/communications/messages?context=linkedin%2Fcompliance%2Fcontext&view=li-lms-unversioned&preserve-view=true

**Comment by titanventura** [comment]
I can work on this. Please assign !

**Comment by mendorshikh** [comment]
@titanventura Sure. I will assign you. Please join our discord: https://discord.gg/zx8u2m4f5W

**Comment by dev-cyprium** [comment]
@titanventura is this issue still open? I'd like to work on it if it still is

**Comment by dropdevrahul** [comment]
@titanventura  is this stil actvie?

**Comment by rishi-raj-jain** [comment]
Can I work on this?

**Comment by mendorshikh** [comment]
@titanventura Are you still working on this issue? If not @dev-cyprium Do you still wanna do it? (First come first serve) If not @rishi-raj-jain I will assign this to you.

**Comment by titanventura** [comment]
Hi, I'm still up for this ! Will look into this and revert back soon !

**Comment by mendorshikh** [comment]
@titanventura Well received.

**Comment by iSatVeerSingh** [comment]
I want to work on this. Can I?

**Comment by mendorshikh** [comment]
@titanventura How are you? How are you doing? Are you still want to develop this plugin?

**Comment by Ahtritus** [comment]
Hey @mendorshikh, is this still open?
