### ISSUE TITLE
Integration with Viber

### ISSUE THREAD

**Issue by nomio19** [erxes/erxes#4302]
Getting Started: https://docs.erxes.io/docs/developer/developing-integration-plugins
Sample IMAP or Facebook messenger integration plugins can be found: https://github.com/erxes/erxes-community/tree/dev/packages
Viber API Documentation: https://developers.viber.com/docs/api/rest-bot-api/

**Comment by mendorshikh** [comment]
@tobihans How are you? Can you work on https://shrtm.nu/bNC on this issue? Viber integration is assigned to someone. Please let me know.

**Comment by mendorshikh** [comment]
This issue is assigned to @epicbold @soyombo-baterdene

**Comment by tobihans** [comment]
> @tobihans How are you? Can you work on https://shrtm.nu/bNC on this issue? Viber integration is assigned to someone. Please let me know.

Yes, that's fine. You can assign it to me. Thanks.

**Comment by Rajashekarksreddy** [comment]
can i take this isuue, is still open?

**Comment by soyombo-baterdene** [comment]
> can i take this isuue, is still open?

sorry @Rajashekarksreddy we're about to closing this one

**Comment by iSatVeerSingh** [comment]
Is this still unresolved? Please someone tell me.

**Comment by mendorshikh** [comment]
@iSatVeerSingh This feature is done.

**Comment by iSatVeerSingh** [comment]
@mendorshikh Then close this.

**Comment by AngelGzS** [comment]
Hello! Still open,  please close it, ty.

**Comment by mendorshikh** [comment]
@AngelGzS It is already implemented. I will close it now.
