### ISSUE TITLE
Add personal channel on inbox plugin

### ISSUE THREAD

**Issue by ghost** [erxes/erxes#4337]
My inbox 20
- info@email.com 4 (Personal email)
- info@email.com 5 (Personal second email)
- @twitter handle 5 (Personal twitter)
- My Facebook 3 (Personal Facebook)
- Assigned to me 1
- Shared with me 2
- Starred
- Drafts
- Sent
- Folders name
-- My folder name
-- My second folder name
- Tags

**Comment by DueDashTech** [comment]
Our thoughts for a private inbox (rather contact-based privacy settings):

- When a new contact gets created via IMAP, what will be the default visibility (all / private) - should be adjustable for each IMAP / user
- Contact-based privacy settings. Contacts could be assigned to channels and everyone with access to this channel, will see the activity behind. Alternatively to groups / individuals like under permission settings. 
- Properties can still be handled individually (from properties side)
- Differentiation between Notes / Emails
- Simple permission: View by group / channel / user
- Advanced permissions: All emails, only mine
- BCC case? E.g. prior conversation that I want to answer as reply from my gmail / Thunderbird (who gets saved, To, CC, BCC?)
