### ISSUE TITLE
[DEV-53] Integration with iMessage

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#4341]
Getting Started: https://docs.erxes.io/docs/developer/developing-integration-plugins
Sample IMAP or Facebook messenger integration plugins can be found: https://github.com/erxes/erxes-community/tree/dev/packages
Apple Messages for Business REST API: https://register.apple.com/resources/messages/msp-rest-api/

**Comment by aar2dee2** [comment]
Hey @mendorshikh,
I'd love to work on this!
Here's a similar [PR](https://github.com/calcom/cal.com/pull/7651) I worked on for cal.com

Could you assign this to me?

**Comment by aar2dee2** [comment]
I'm following the [local installation guide for mac](https://docs.erxes.io/docs/deployment/installation/installation-mac) from the docs and ran into this:
<img width="1289" alt="Screenshot 2023-05-11 at 4 34 58 PM" src="https://github.com/erxes/erxes/assets/85004512/583b5a53-99b3-4686-b73a-02cb63b20127">

**Comment by mendorshikh** [comment]
@aar2dee2 Super! I've just assigned it to you. I saw you on Discord. I will assign a person who can help with the installation.

**Comment by aar2dee2** [comment]
thank you so much!

**Comment by vickywane** [comment]
@mendorshikh 

Is there any work been done on this issue? -- I would love to work on it!

**Comment by aar2dee2** [comment]
> @aar2dee2 How are you? Are you working on this issue? if not I wanna assign this issue to @vickywane

@mendorshikh please feel free to re-assign this.

I had trouble getting erxes to run on macOS.

**Comment by mendorshikh** [comment]
@aar2dee2 Well received. It will be appreciated improvements we would make to improve the dev experience. Thanks!
@vickywane I've just re-assigned this issue to you.

**Comment by haruncurak** [comment]
Hi @mendorshikh -- in case this is still an issue, I'd love to work on it!

**Comment by mendorshikh** [comment]
@vickywane How are you? Are you working on this issue? if not I wanna assign this issue to @haruncurak

**Comment by AayushMohan** [comment]
Hey @mendorshikh, since no one is currently working on this issue, may I take on the task? Could you please assign it to me?

**Comment by mendorshikh** [comment]
@AayushMohan Sure. I assigned this task to you. Please join our discord and let us know if there is anything we need to assist.

**Comment by AayushMohan** [comment]
@mendorshikh, Thank you for assigning me the task. I have already joined the Discord channel and will let you know if I need any assistance or clarification.

> @AayushMohan Sure. I assigned this task to you. Please join our discord and let us know if there is anything we need to assist.

**Comment by Pradumn27** [comment]
any updates here @AayushMohan, I'd like to pick this up if you're facing issues :)

**Comment by lakshyachitranshs** [comment]
hi @AayushMohan  are you working on this? I would like to try

**Comment by mrkirthi-24** [comment]
Hi @mendorshikh, can I work in this issue?

**Comment by polooner** [comment]
anyone working on this? lets collab

**Comment by oliverqx** [comment]
@polooner I've been working on this for the last couple of days. I'd love to collab by I'm almost done, was about to open a pr
