### ISSUE TITLE
[DEV-54] Integration with Telegram

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#4342]
Getting Started: https://docs.erxes.io/docs/developer/developing-integration-plugins
Sample IMAP or Facebook messenger integration plugins can be found: https://github.com/erxes/erxes-community/tree/dev/packages
Telegram APIs: https://core.telegram.org/#tdlib--build-your-own-telegram

**Comment by thecalcc** [comment]
@mendorshikh I started looking through the docs on how I can develop this pluggin and I got to the point where I created the template with `yarn create-plugin` and then I restarted my instance, but the `Integrations` section isn't present in Settings. Can you point me in the right direction here as I can't find docs on how I can enable integrations if there's such a thing. P.S. I have enabled the plugin itself by adding it in `configs.json`

**Comment by Myagmarsuren-a** [comment]
@thecalcc did you added "ui": "local" in configs json under plugins?

**Comment by thecalcc** [comment]
@Myagmarsuren-a I have and nothing changes

**Comment by mendorshikh** [comment]
@Myagmarsuren-a Can you followup here.

**Comment by Myagmarsuren-a** [comment]
@mendorshikh its been taken care @thecalcc goodluck.

**Comment by Kagabe** [comment]
Hey @bpedersen, I'll let you finish this one.

**Comment by kesh-007** [comment]
Hey @mendorshikh
I'm interested in working on this!
