### ISSUE TITLE
[DEV-55] Integration with Discord DMs

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#4343]
Getting Started: https://docs.erxes.io/docs/developer/developing-integration-plugins
Sample IMAP or Facebook messenger integration plugins can be found: https://github.com/erxes/erxes-community/tree/dev/packages
Represents a guild or DM channel within Discord: https://discord.com/developers/docs/resources/channel

**Comment by Alcadeus0** [comment]
Hello can I work on this issue :)

**Comment by mendorshikh** [comment]
@Alcadeus0 Sure! Please let us know if there is anything we can help with @Myagmarsuren-a. Please help here.

**Comment by Alcadeus0** [comment]
Thanks, I'm going through the docs for now, will let you know if I encounter any obstacles

**Comment by mendorshikh** [comment]
@Alcadeus0 Please join our discord via https://discord.gg/zx8u2m4f5W

**Comment by Alcadeus0** [comment]
@mendorshikh Done, I'll ask my doubts there.

**Comment by Bhardwaj-Himanshu** [comment]
Hi @mendorshikh, so I wanted to start working on the issue, so I went through the resources provided by you and I must say they are very helpful, well enough for a person who wants to start creating plugins.

I read the documentation, but before setting up the project locally, I set it up on my cloud machine and the local installation on that VM works perfectly fine. Had some queries regarding the selection of ports while launching erxes using command-
```bash
./bin/erxes.js dev
```
Cause I need to RDP(remote desktop connect) into the GUI of my VM using a ssh client or RDP client.
I wanted to ask for the ports I need to select as I won't be redirected normally as would be on a local machine.

I have also joined the discord server and looking forward to solve other begineer friendly issues as well, weather maybe from documentation correction or a bug fix.

Also could I DM you @Myagmarsuren-a?
Thanks

**Comment by Bhardwaj-Himanshu** [comment]
Sorry for the retag @mendorshikh but I need little help on this issue!
If someone could provide me a little guidance on why is the above error happening and how to resolve it?
Thanks, would love to work on this issue as well as other open third party integration issues!

**Comment by Myagmarsuren-a** [comment]
@Bhardwaj-Himanshu sorry for missed out your comments. What is your gateway log ?
