### ISSUE TITLE
502 Gateway Error as the gateway container fails to build

### ISSUE THREAD

**Issue by nitish2507** [erxes/erxes#4399]
After following the docker based build instructions as provided here

https://docs.erxes.io/docs/deployment/deployment/deploymentDocker

I am unable to launch the app because the 'gateway' container is failing

**Log from the 'gateway' container gives the below**

Clearing enabled services cache ........
(node:1) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:1) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:1) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
Plugin contacts joined service discovery.
Plugin notifications joined service discovery.
Plugin workers joined service discovery.
Plugin forms joined service discovery.
Plugin integrations joined service discovery.
Plugin emailtemplates joined service discovery.
Plugin logs joined service discovery.
Plugin cards joined service discovery.
Plugin inbox joined service discovery.
Plugin webbuilder joined service discovery.
Plugin internalnotes joined service discovery.
Plugin core joined service discovery.
Plugin segments joined service discovery.
Plugin products joined service discovery.
Plugin tags joined service discovery.
Plugin engages joined service discovery.
Plugin knowledgebase joined service discovery.
Plugin contacts's graphql endpoint http://plugin_contacts_api/graphql is up.
Plugin notifications's graphql endpoint http://plugin_notifications_api/graphql is up.
Plugin workers's graphql endpoint http://plugin_workers_api/graphql is up.
Plugin forms's graphql endpoint http://plugin_forms_api/graphql is up.
Plugin integrations's graphql endpoint http://plugin_integrations_api/graphql is up.
Plugin emailtemplates's graphql endpoint http://plugin_emailtemplates_api/graphql is up.
Plugin logs's graphql endpoint http://plugin_logs_api/graphql is up.
Plugin webbuilder's graphql endpoint http://plugin_webbuilder_api/graphql is up.
Plugin core's graphql endpoint http://plugin_core_api/graphql is up.
Plugin cards's graphql endpoint http://plugin_cards_api/graphql is up.
Plugin inbox's graphql endpoint http://plugin_inbox_api/graphql is up.
Plugin internalnotes's graphql endpoint http://plugin_internalnotes_api/graphql is up.
Plugin engages's graphql endpoint http://plugin_engages_api/graphql is up.
Plugin segments's graphql endpoint http://plugin_segments_api/graphql is up.
Plugin tags's graphql endpoint http://plugin_tags_api/graphql is up.
Plugin products's graphql endpoint http://plugin_products_api/graphql is up.
Plugin knowledgebase's graphql endpoint http://plugin_knowledgebase_api/graphql is up.
There is a newer version of Rover available: v0.14.1 (currently running v0.14.0)

For instructions on how to install, run `rover docs open start`
resolving SDL for subgraphs defined in /erxes-gateway/dist/gateway/src/apollo-router/temp/supergraph.yaml
error[E038]: Encountered 17 build errors while trying to build a supergraph.

Caused by:
    E028: error sending request for url (http://plugin_cards_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'cards' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_contacts_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'contacts' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_core_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'core' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_emailtemplates_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'emailtemplates' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_engages_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'engages' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_forms_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'forms' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_inbox_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'inbox' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_integrations_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'integrations' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_internalnotes_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'internalnotes' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_knowledgebase_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'knowledgebase' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_logs_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'logs' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_notifications_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'notifications' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_products_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'products' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_segments_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'segments' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_tags_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'tags' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_webbuilder_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'webbuilder' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    E028: error sending request for url (http://plugin_workers_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'workers' subgraph
            Make sure the endpoint is accepting connections and is spelled correctly
    
        See https://www.apollographql.com/docs/rover/commands/supergraphs#yaml-configuration-file for information on the config format.
(node:1) UnhandledPromiseRejectionWarning: Error: Command failed: rover supergraph compose --config /erxes-gateway/dist/gateway/src/apollo-router/temp/supergraph.yaml --output /erxes-gateway/dist/gateway/src/apollo-router/temp/supergraph.graphql --elv2-license=accept --log=error
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at /erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:59:38
    at Generator.next (<anonymous>)
    at /erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:4:12)
    at supergraphComposeOnce (/erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:53:37)
    at /erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:82:15
    at Generator.next (<anonymous>)
    at fulfilled (/erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nitish2507** [comment]
#4085 seems to have asked a similar question but is closed without any satisfactory resolution.
Can someone help here?

@Myagmarsuren-a 

Could you explain your comment on #4085

_Its known issue we are working on it. Fix is just simply create folder named in erxes directory. Then start erxes._

**Comment by nitish2507** [comment]
Thanks for helping close @Myagmarsuren-a

**Comment by ivlukyanov** [comment]
I have the same problem:

> ...
> 2023-06-12T12:17:00.858151032Z Plugin contacts's graphql endpoint http://plugin_contacts_api/graphql is up.
> 2023-06-12T12:17:00.859100174Z Plugin integrations's graphql endpoint http://plugin_integrations_api/graphql is up.
> 2023-06-12T12:17:01.139517735Z There is a newer version of Rover available: v0.15.0 (currently running v0.14.2)
> 2023-06-12T12:17:01.139541350Z
> 2023-06-12T12:17:01.139548684Z For instructions on how to install, run `rover docs open start`
> 2023-06-12T12:17:01.139735166Z resolving SDL for subgraphs defined in /erxes-gateway/dist/gateway/src/apollo-router/temp/supergraph.yaml
> **2023-06-12T12:17:01.196565737Z error[E038]: Encountered 10 build errors while trying to build a supergraph.**
> 2023-06-12T12:17:01.196590644Z
> 2023-06-12T12:17:01.196596005Z Caused by:
> **2023-06-12T12:17:01.196600373Z     E028: error sending request for url (http://plugin_contacts_api/graphql): error trying to connect: dns error: proto error: Label contains inval**
> id characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'contacts' subgraph
> 2023-06-12T12:17:01.196605282Z             Make sure the endpoint is accepting connections and is spelled correctly
> **2023-06-12T12:17:01.196609590Z     E028: error sending request for url (http://plugin_core_api/graphql): error trying to connect: dns error: proto error: Label contains invalid c**
> haracters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'core' subgraph
> 2023-06-12T12:17:01.196614500Z             Make sure the endpoint is accepting connections and is spelled correctly
> ...

Could someone help me please to undestand how to fix it?
@nitish2507 @Myagmarsuren-a

**Comment by mendorshikh** [comment]
@ivlukyanov Please join our discord to get a support via https://discord.gg/zx8u2m4f5W

**Comment by vinyll** [comment]
Just for the follow up, here's the status on Discord in Oct 2023:

<img width="720" alt="Screenshot 2023-10-28 at 12 25 35" src="https://github.com/erxes/erxes/assets/145172/54fd01a1-ef6b-412d-a502-7646830ffe85">

I'm supposing something is happening on Oct 30th that will be published and solve? 🤔
