### ISSUE TITLE
Resolve graphql queries duplication

### ISSUE THREAD

**Issue by batamar** [erxes/erxes#447]

**Comment by batamar** [comment]
https://www.apollographql.com/docs/react/recipes/webpack.html

**Comment by shinebayar-g** [comment]
@batamar @Anu-Ujin Do we have any updates here?

**Comment by Mambatukaa** [comment]
Hey there,

This issue is outdated or there is a more recent duplicate.
Closing this issue to keep the Issues less cluttered.

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
Please use this link in the future to submit your features.

Thank you.
