### ISSUE TITLE
Licensing of erxes unclear because of mentions of previous license.

### ISSUE THREAD

**Issue by willtop43** [erxes/erxes#4609]
**Describe the bug**
Several files still mention the licensing to be GPLv3 with the Commons Clause. It is unclear if these notices apply to any files or not:
package.json
/cli/README.md
/docs/spectaql.yml
/packages/core/README.md
/packages/plugin-integrations-api/README.md 

**To Reproduce**
1. From the main directory `grep -R Commons ./` 
2. See all the files with the older license reference.

**Expected behavior**
Can these be cleaned up so we can confidently used erxes under the AGPLv3?

**Comment by mendorshikh** [comment]
@willtop43 

I apologize for the confusion regarding the licensing of certain files in our repository.

Our official license for erxes is available at https://shrtm.nu/ilC, and I'd like to clarify the licensing of different portions of our software:

Enterprise Edition (EE): All plugins named with "-ee" at the end, residing under https://github.com/erxes/erxes/tree/master/ee directory of this repository, are licensed under the terms specified in the "ee/LICENSE" file.

Third-Party Components: Any third-party components incorporated into erxes are licensed under the original licenses provided by the respective owners of those components. These licenses are distinct from erxes' main license.

Remaining Content: Content outside of the directories or restrictions mentioned above is available under the "AGPLv3" license as defined in our main license document.

Please be assured that erxes is not permitted to be hosted as a SaaS version that competes with erxes Inc., in accordance with our licensing terms.

We appreciate your diligence in identifying the discrepancies in our documentation, and we will take steps to address the inconsistencies and update the relevant files accordingly. This will ensure that you can confidently use erxes under the AGPLv3 license. If you have any further questions or concerns, please don't hesitate to reach out. Thank you for your understanding.
