### ISSUE TITLE
gateway container restarts after error

### ISSUE THREAD

**Issue by triemer49** [erxes/erxes#4615]
**Describe the bug**
gateway container restarts 

**To Reproduce**
install via instructions to deploy

**Expected behavior**
gateway container should not restart...

**Screenshots**

**Context (please include the related information if applicable):**
ubuntu
This is the same error seen in issue 4533

This is the error that shows up in the gateway service:
It means the gateway service does not start.

resolving SDL for subgraphs defined in /erxes-gateway/dist/gateway/src/apollo-router/temp/supergraph.yaml
erxes_gateway.2.8dme9t2uvgtd@topnet.net | error[E038]: Encountered 10 build errors while trying to build a supergraph.
erxes_gateway.2.8dme9t2uvgtd@topnet.net |
erxes_gateway.2.8dme9t2uvgtd@topnet.net | Caused by:
erxes_gateway.2.8dme9t2uvgtd@topnet.net | E028: error sending request for url (http://plugin_contacts_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'contacts' subgraph
erxes_gateway.2.8dme9t2uvgtd@topnet.net | Make sure the endpoint is accepting connections and is spelled correctly
erxes_gateway.2.8dme9t2uvgtd@topnet.net | E028: error sending request for url (http://plugin_core_api/graphql): error trying to connect: dns error: proto error: Label contains invalid characters: Err(Errors { invalid_mapping, disallowed_by_std3_ascii_rules }) while resolving the schema for the 'core' subgraph

**Comment by kcalliauw** [comment]
Same issue here. As I understand it has to do with the fact that underscores in the URL aren't allowed.

**Comment by dulguun0225** [comment]
@triemer49 Please upgrade your `erxes cli` to the latest version and run `npm run erxes up` again. Which version of it are you using currently?

**Comment by kcalliauw** [comment]
Just pitching in, for me this is a fresh install done today, comeoletely new Ubuntu 22.04 instance with node LTS (18.18.something)

**Comment by dulguun0225** [comment]
> Just pitching in, for me this is a fresh install done today, completely new Ubuntu 22.04 instance with node LTS (18.18.something)

Change the version of erxes to `0.4.27` inside the `package.json` and run `npm install` to install the version `0.4.27`.
Then run `npm run erxes up` again.
