### ISSUE TITLE
[Bug] The "full width" becomes "half width" field "CALLOUT IMAGE SIZE" in the "CallOut" section after saving the form

### ISSUE THREAD

**Issue by Denys-Myronov** [erxes/erxes#4619]
**To Reproduce**
1. Open the "Form create" page '... /forms/create'
2. Fill in all required fields
3. Add an image in the "CallOut" section
4. Choose the "full width" from the "CALLOUT IMAGE SIZE" drop-down list
5. Click the 'Save' button
6. Open a form or run a form simulation
7. Notice that the value in the "CALLOUT IMAGE SIZE" field has changed to "half width"

**Actual behavior**
The "full width" **becomes** the "half width" field "CALLOUT IMAGE SIZE" in the "CallOut" section after saving the form

**Expected behavior**
The "full width" **remains** the "full width" field "CALLOUT IMAGE SIZE" in the "CallOut" section after saving the form

**Screenshots**

https://github.com/erxes/erxes/assets/144341591/16c09a77-6e0c-489f-93bc-a1c347566947

**Context (please include the related information if applicable):**

- OS: [MacOS]
- Browser version [ Chromium: 116.0.5845.114 (Official Build) (x86_64)]
- erxes env. Prod
- erxes Plan Free

**Comment by orgilshdeee** [comment]
fixed
