### ISSUE TITLE
[Bug] A form with more than 1 NUMBER OF PAGES in the "Content" section is not displayed when simulating the code or installing it on the page

### ISSUE THREAD

**Issue by Denys-Myronov** [erxes/erxes#4626]
**To Reproduce**
1. Open the "Form create" page '... /forms/create'
2. Fill in all required fields
3. Set a value greater than 1 in the NUMBER OF PAGES field in the "Content" section
4. Save the form
5. Simulate the code or install it on the web page
6. Pay attention: The form is not displayed

**Actual behavior**
A form with more than 1 NUMBER OF PAGES in the "Content" section **is not displayed** when simulating the code or installing it on the page

**Expected behavior**
A form with more than 1 NUMBER OF PAGES in the "Content" section **is displayed** when simulating the code or installing it on the page

**Screenshots**

https://github.com/erxes/erxes/assets/144341591/ce6352cc-c02b-490e-ad66-074398b1af53

![Image](https://github.com/erxes/erxes/assets/144341591/bd93a365-7f76-4008-ac7b-4bf725d229b4)

**Context (please include the related information if applicable):**

- OS: [MacOS]
- Browser version [ Chromium: 116.0.5845.114 (Official Build) (x86_64)]
- erxes env. Prod
- erxes Plan Free

**Test data**
Login: [denys.myronov@devit.group](mailto:denys.myronov@devit.group)
Pass: Test13579

**Comment by Denys-Myronov** [comment]
Please note: The same behavior when adding additional fields from the "Content" section, for example, "Text input" or "text area"



https://github.com/erxes/erxes/assets/144341591/d771fba0-6cc5-4709-9023-4ad942526d88

**Comment by orgilshdeee** [comment]
> Please note: The same behavior when adding additional fields from the "Content" section, for example, "Text input" or "text area"
> 
>  2023-09-19_17-49-11.mp4

When callout is Skipped it doesn't appear right away. It does seem appearing when right bottom icon is clicked.
<img width="525" alt="Screenshot 2023-09-27 at 16 12 36" src="https://github.com/erxes/erxes/assets/67452021/99bf7a5f-7c1d-4968-b3e7-dea39eb91402">
