### ISSUE TITLE
Documentation for docker install, behind nginx

### ISSUE THREAD

**Issue by peterdalydickson** [erxes/erxes#495]
I'm looking forward to trying out erxes (how do you pronounce that btw?!).

You have installation instructions for docker. And for deploying behind nginx.

Do you have any guidance for a docker install of erxes behind nginx?

**Comment by shinebayar-g** [comment]
Hello @peterdalydickson 
It's pronounced as _erhes_ in Mongolian.
We're going to refactor our application to implement full docker support. Hence our docker image isn't updated for a while. 

I suggest you to check out our [installation](https://github.com/erxes/erxes/wiki/Installation) page.
If you have any questions feel free to ask here. I will gladly help you.

**Comment by shinebayar-g** [comment]
I know it's super late, but I didn't abandon this task.

https://github.com/erxes/erxes/wiki/Running-behind-Nginx
