### ISSUE TITLE
Need to show person full name who wrote to page (+ View Profile URL) not the page name

### ISSUE THREAD

**Issue by mendorshikh** [erxes/erxes#50]
![Messages detail 2](http://static.gitscout.com/eb73a20e6a04131848f3bd8e859c066a00ec777ebfdc8b83377da9c6a533d7aa.png)

**Comment by batamar** [comment]
@ganzorig 

conversation.facebookData.senderId use this as facebook.com/senderId to show got to profile link
conversation.facebookData.postId to show go to post link
