### ISSUE TITLE
email integration feature

### ISSUE THREAD

**Issue by alekseyp** [erxes/erxes#507]
Hi there,

I'm curious if you are planning on adding an email integration?
Or it's already exists and I've missed how to configure it?

I'm thinking of very basic ticket system, where erxes will monitor email addresses via IMAP and create chat's from those emails.

PS: Great software!

**Comment by shinebayar-g** [comment]
Hello Aleksey,

I dug our repos' issues and only found this #13 I'm pretty sure there was issue named Gmail integration but couldn't find it.

I believe the email integration is planned, but didn't get an update since then.

@batamar
