### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by heromiyo** [erxes/erxes#514]
![image](https://user-images.githubusercontent.com/39757927/43035816-419f730c-8d28-11e8-99d6-577749e64707.png)

**Comment by shinebayar-g** [comment]
Hello @heromiyo ,
erxes project's 2 of 4 repositories are renamed.
erxes-api -> erxes-widgets-api
erxes-app-api -> erxes-api

Our docker images aren't updated yet. I will push updates to our docker images very soon.

**Comment by shinebayar-g** [comment]
Docker images are updated. Check our docker [wiki page](https://github.com/erxes/erxes/wiki/Use-erxes-with-Docker) again for more information.
