### ISSUE TITLE
Inbox: Participating numbers is not changed reactively.

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes#570]

**Comment by Mambatukaa** [comment]
Hey there,

This issue is outdated or there is a more recent duplicate.
Closing this issue to keep the Issues less cluttered.

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
Please use this link in the future to submit your features.

Thank you.

**Comment by davidkartuzinski** [comment]
@batchimeg-a - Could you please provide a better description of the bug?

**Comment by KhongorzulD** [comment]
Hi @Batchimegb, I would like to know about the issue's current status. If it is already solved, I will close the issue.
