### ISSUE TITLE
Cant login  User

### ISSUE THREAD

**Issue by amka94amka** [erxes/erxes#580]
Browser Console дээрээ ийм алдаа заагаад байгна 
*****************************************************************

client.js:421 WebSocket connection to 'ws://localhost:3300/subscriptions' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.connect @ client.js:421
2localhost:3300/graphql:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
client.js:421 WebSocket connection to 'ws://localhost:3300/subscriptions' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.connect @ client.js:421
2localhost:3300/graphql:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
Observable.js:59 Uncaught TypeError: Failed to fetch
sign-in:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
4client.js:421 WebSocket connection to 'ws://localhost:3300/subscriptions' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.connect @ client.js:421
14client.js:421 WebSocket connection to 'ws://localhost:3300/subscriptions' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.connect @ client.js:421
(anonymous) @ client.js:391
client.js:77 WebSocket connection to 'ws://localhost:3300/subscriptions' failed: WebSocket is closed before the connection is established.
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.close @ client.js:77
(anonymous) @ client.js:415
setTimeout (async)
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.checkMaxConnectTimeout @ client.js:413
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.connect @ client.js:422
(anonymous) @ client.js:391
setTimeout (async)
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.tryReconnect @ client.js:390
./node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.close @ client.js:81
client.onclose @ client.js:433

**Comment by shinebayar-g** [comment]
Redis сервер чинь ажиллаж байгаа биздээ? Дараагийн удаа code snippet оруулахдаа markdown syntax ашиглаж байна уу. erxes-api, erxes-widgets-api, erxes-widgets серверүүд чинь асахдаа console дээрээ ямар нэгэн алдаа өгөөгүй биздээ?
Хэрвээ ажилуулсан эрхэсээ localhost-оос өөр компьютероор оруулж ашиглах гэж байгаа бол erxes-ээ сүлжээнд ажиллуулах тохиргоог `.env` файлдаа тохируулж өгнө. localhost гэдгийг IP-гаараа сольж ажиллуулж байж дотоод сүлжээнд ажиллана. Домэйн хаягаар тохируулж байж интернэтэд ажиллана гэх мэт.

**Comment by amka94amka** [comment]
За erxes-api болон erxes-widget-api erxes-widget энэ 3 ийг ажлуулахад ямар нэгэн алдаа өгөөгүй байгаа
192.168.xxx.xxx:300 өөр хүмүүс ингээд хандахад бол login page харагдаж байган 
Browser дээр дээх алдаа харин site дээрээ ийм алдаа гарч байган screen shot url явууллаа
Reddis бол ажиллаж байгаа 
Би өөрийн computer дээрээс бол login дож орчоод Incognito browser-өөр орхоор алдаа гарч байна 
https://prnt.sc/kwyosl

**Comment by shinebayar-g** [comment]
Бүх project-ийн харгалзах тохиргоог .env бүрт хийж өгнө. Сүлжээнд мөн firewall чинь блоклоогүй эсэхийг шалгана.

**Comment by amka94amka** [comment]
.env дээрээ ямарч нэмэлтээр зүйл нэмж өгөөгүй байхад бол згр ажиллана биз дээ ?

**Comment by shinebayar-g** [comment]
Зөвхөн өөрийн чинь компьютер дээр бол тийм.
