### ISSUE TITLE
user message

### ISSUE THREAD

**Issue by amka94amka** [erxes/erxes#581]
Хэрэглэгчээс ирж байгаа мэссэж шууд орж ирэхгүй заавал дахин refresh юм уу өөр цэс рүү орсны дараагаар ирээд байхын ?

**Comment by shinebayar-g** [comment]
`.env`-гээ зөв тааруулаарай. Бас redis-server ажиллаж байгаа эсэхийг шалга. Бусдаар ийм алдаа гардаггүй.
