### ISSUE TITLE
Add new language files

### ISSUE THREAD

**Issue by batamar** [erxes/erxes#610]
- Add language files to src/locales folder
- Split new branch from ts branch

**Comment by lucchmielowski** [comment]
Hi ! Can I add the french language file ?

**Comment by mendorshikh** [comment]
@lucchmielowski yes please! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by batamar** [comment]
There are language files located in src/locales folder. You should add fr.json file and add translations into it like en.json and mn.json

**Comment by muelletr** [comment]
Hello, I do the german translation.

**Comment by shinebayar-g** [comment]
@muelletr make sure you mention this issue #623

**Comment by tribakzero** [comment]
one third of the spanish translation is done.

**Comment by mendorshikh** [comment]
@leschlogl That would be awesome! Thank you.
