### ISSUE TITLE
Fix knowledge base loader

### ISSUE THREAD

**Issue by batamar** [erxes/erxes#611]
- When click on knowledge base menu on sidebar, loader is appearing in wrong position
- Split new branch from ts branch

**Comment by masquel** [comment]
i'll try this one

**Comment by batamar** [comment]
> i'll try this one

👍

**Comment by mendorshikh** [comment]
@masquel thank you! GL

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
