### ISSUE TITLE
Fix disabled member-access tslint rule

### ISSUE THREAD

**Issue by batamar** [erxes/erxes#612]
- Split new branch from ts branch

**Comment by sasalx** [comment]
So let me get it straight. You just want to make this rule enabled right?

**Comment by batamar** [comment]
when you remove this disabled rule in tslint.json, it will cause some ts compiler errors and you have to fix those

**Comment by sasalx** [comment]
Hmm. I see. So I don't know if you are familiar with other languages that use "public" "private" and "protected" but basically, this rule ensures that all functions wrote in this manner. Thus we have to decide which will be what. I can also make them public but it defeats the purpose of the rule.
