### ISSUE TITLE
Fix disabled object-literal-sort-keys ts rule

### ISSUE THREAD

**Issue by batamar** [erxes/erxes#617]
- Split new branch from ts branch

**Comment by ItsMeWithTheFace** [comment]
Hi @batamar, could I take on this issue if it hasn't been worked on yet?

**Comment by Mambatukaa** [comment]
Hey there,

This issue is outdated or there is a more recent duplicate.
Closing this issue to keep the Issues less cluttered.

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
Please use this link in the future to submit your features.

Thank you.

**Comment by KhongorzulD** [comment]
It seems like the issue is already found its solution so I will close the issue if there's not anything that contradicts to it.
