### ISSUE TITLE
is there any active community room like slack? gitter is sleep,  i also looking up technically document i cant find them,

### ISSUE THREAD

**Issue by rmros** [erxes/erxes#679]

**Comment by shinebayar-g** [comment]
Hello @rmros Thanks for your interest in erxes application. Currently there isn't any community room. Yea we are not definitely maintaining gitter anymore. About technical document we're working on it right now, hopefully publish soon enough.

I just created **erxes users** slack workspace for community questions and support!
Please feel free to join using: https://join.slack.com/t/erxes-users/shared_invite/enQtNDU2MTkyNzM2NDY0LWU5MDFjNWM3OWNmNGU2ZDFmY2EwMDMyYzRmYzBlYWJlODNiY2IwMjk5NTRkMGYyMzljMjU4Y2JhNjE4ZjNjMjU
