### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by newmetashit** [erxes/erxes#709]
erxes-api.site.mn/graphql:1 Failed to load resource: the server responded with a status of 400 (Bad Request)

Энэ тохиолдолд яах бэ ?

**Comment by shinebayar-g** [comment]
Ямар request явуулсан бэ?

**Comment by newmetashit** [comment]
Бүх тохиргоог хийгээд ажлуулахаар real time chat болохгүй юмаа
Хэрэглэгчийн бичсэн чат надаа шууд real time  ирэхгүй Миний бичсэн чат хэрэглэгчид шууд очоод Би өөрөө заавал хуудсаа refresh хийж байж гарч ирээд байхын

**Comment by newmetashit** [comment]
messengerWidget.bundle.js:1 Mixed Content: The page at 'https://mysite.mn/' was loaded over HTTPS, but requested an insecure resource 'http://geoips.nekudo.com/api/%7Bip%7D/%7Blanguage%7D/%7Btype%7D'. This request has been blocked; the content must be served over HTTPS.


Бас энэ site ийг block хийгээд байхын энэ code дундаа https гүй дуудаад байна

**Comment by shinebayar-g** [comment]
Тохиргоо л болохгүй байна даа. Бас develop branch дээр уг алдаа засагдсан байгаа.
