### ISSUE TITLE
ERR_CONNECTION_REFUSED 

### ISSUE THREAD

**Issue by lalitnandandiwakar** [erxes/erxes#741]
after installation  

in login page   we are facing" ERR_CONNECTION_REFUSED" 
![screenshot 2018-10-26 15 54 49](https://user-images.githubusercontent.com/11966970/47698114-1398ef00-dc34-11e8-83e6-1dff4ef602bb.png)
![screenshot 2018-10-30 11 06 36](https://user-images.githubusercontent.com/11966970/47698157-40e59d00-dc34-11e8-8bb5-bfe60674a869.png)

in server side Port 3300 are active 

![image](https://user-images.githubusercontent.com/11966970/47698277-b81b3100-dc34-11e8-9a5c-1cc7b21ff113.png)

any one Help Me 

thanks 

And In Server Side

**Comment by shinebayar-g** [comment]
Hello,
First of all thanks for trying out erxes!

you should update your .env config files of 4 erxes' projects.
For example: In **erxes** folder's `.env` file would like something like this:
```
PORT=3000 - This doesn't matter if you're using nginx instead of yarn start command which invokes nodejs process on port 3000.
NODE_PATH=src
NODE_ENV=development
REACT_APP_CDN_HOST=http://localhost:3200 (erxes-widget's address: in your case it should be your public and port or domain address. Example: http://35.190.149.31:3200
REACT_APP_API_URL=http://localhost:3300 (erxes-api's address: in your case it should be your public and port or domain address. Example: http://35.190.149.31:3300
REACT_APP_API_SUBSCRIPTION_URL=ws://localhost:3300/subscriptions (this one too, should be replaced with ws://35.190.149.31:3300/subscriptions
```

**Comment by RileySeaburg** [comment]
> Hello,
> First of all thanks for trying out erxes!
> 
> you should update your .env config files of 4 erxes' projects.
> For example: In **erxes** folder's `.env` file would like something like this:
> 
> ```
> PORT=3000 - This doesn't matter if you're using nginx instead of yarn start command which invokes nodejs process on port 3000.
> NODE_PATH=src
> NODE_ENV=development
> REACT_APP_CDN_HOST=http://localhost:3200 (erxes-widget's address: in your case it should be your public and port or domain address. Example: http://35.190.149.31:3200
> REACT_APP_API_URL=http://localhost:3300 (erxes-api's address: in your case it should be your public and port or domain address. Example: http://35.190.149.31:3300
> REACT_APP_API_SUBSCRIPTION_URL=ws://localhost:3300/subscriptions (this one too, should be replaced with ws://35.190.149.31:3300/subscriptions
> ```
> 
> If you're just trying out without domain, make sure your ports are accessible by public. Or use reverse proxy like nginx. Our config file example here https://github.com/erxes/erxes/wiki/Running-behind-Nginx
> 
> After updating your .env files, all process required to restart to pick up new configs.

What happened to the example file?
