### ISSUE TITLE
Resolve uploadHandler duplications

### ISSUE THREAD

**Issue by batamar** [erxes/erxes#754]
https://app.leanboard.io/board/ff04f4fc-e9d1-436f-8d25-5948f53e7fe9
![LeanBoard](https://app.leanboard.io/api/board/ff04f4fc-e9d1-436f-8d25-5948f53e7fe9/image.png)

**Comment by batamar** [comment]
AttachmentPreview logic is duplicated in many places

**Comment by Mambatukaa** [comment]
Hey there,

This issue is outdated or there is a more recent duplicate.
Closing this issue to keep the Issues less cluttered.

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
Please use this link in the future to submit your features.

Thank you.

**Comment by davidkartuzinski** [comment]
@batamar @Mambatukaa - If this is a duplicate issue, can we link to the duplicate issue and close this one?
