### ISSUE TITLE
error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"

### ISSUE THREAD

**Issue by lalitnandandiwakar** [erxes/erxes#766]
root@testing:~# curl https://raw.githubusercontent.com/erxes/erxes/master/scripts/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   792  100   792    0     0   5739      0 --:--:-- --:--:-- --:--:--  5739
Clone erxes repository and install its dependencies:
Cloning into 'erxes'...
remote: Enumerating objects: 113, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 59305 (delta 41), reused 55 (delta 19), pack-reused 59192
Receiving objects: 100% (59305/59305), 35.87 MiB | 17.21 MiB/s, done.
Resolving deltas: 100% (40815/40815), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
yarn install v1.12.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning snyk > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @nivo/line@0.35.0" has unmet peer dependency "prop-types@^15.5.10".
warning "@nivo/line > @nivo/core@0.35.0" has unmet peer dependency "prop-types@^15.5.10".
warning "@nivo/line > @nivo/legends@0.35.0" has unmet peer dependency "prop-types@^15.5.10".
warning " > @nivo/pie@0.35.0" has unmet peer dependency "prop-types@^15.5.10".
warning " > apollo-link-ws@1.0.9" has incorrect peer dependency "subscriptions-transport-ws@^0.9.0".
warning " > draft-js-export-html@1.2.0" has unmet peer dependency "immutable@3.x.x".
warning "draft-js-export-html > draft-js-utils@1.2.0" has unmet peer dependency "immutable@3.x.x".
warning " > react-toggle@4.0.2" has unmet peer dependency "prop-types@^15.3.0".
warning "subscriptions-transport-ws > graphql-subscriptions@0.4.4" has incorrect peer dependency "graphql@^0.7.0 || ^0.8.0 || ^0.9.0 || ^0.10.1".
warning "react-scripts-ts > ts-jest@22.0.1" has incorrect peer dependency "typescript@2.x".
[4/4] Building fresh packages...
success Saved lockfile.
$ opencollective postinstall

     *** Thank you for using erxes! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/erxes/donate

                    ***

Done in 66.33s.
Create `.env.sample` from default settings file and configure it on your own:
Create `.ecosystem.json` from sample file:
Install erxes-api
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   485  100   485    0     0   1796      0 --:--:-- --:--:-- --:--:--  1802
Clone erxes-api repository and install its dependencies:
Cloning into 'erxes-api'...
remote: Enumerating objects: 90, done.
remote: Counting objects: 100% (90/90), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 16440 (delta 42), reused 50 (delta 22), pack-reused 16350
Receiving objects: 100% (16440/16440), 3.44 MiB | 23.96 MiB/s, done.
Resolving deltas: 100% (12553/12553), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Create `.env.sample` from default settings file and configure it on your own:
Install erxes-widgets-api
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   509  100   509    0     0   2693      0 --:--:-- --:--:-- --:--:--  2678
Clone erxes-widgets-api repository and install its dependencies:
Cloning into 'erxes-widgets-api'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 3735 (delta 16), reused 24 (delta 8), pack-reused 3690
Receiving objects: 100% (3735/3735), 878.28 KiB | 13.51 MiB/s, done.
Resolving deltas: 100% (2550/2550), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Create `.env.sample` from default settings file and configure it on your own:
Install erxes-widgets
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   490  100   490    0     0   3983      0 --:--:-- --:--:-- --:--:--  3983
Clone erxes-widgets repository and install its dependencies:
Cloning into 'erxes-widgets'...
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (134/134), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 6705 (delta 84), reused 98 (delta 69), pack-reused 6571
Receiving objects: 100% (6705/6705), 2.37 MiB | 16.38 MiB/s, done.
Resolving deltas: 100% (4579/4579), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
yarn install v1.12.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Create `.env.sample` from default settings file and configure it on your own:
Default login credentials

**Comment by erdenezul** [comment]
@batamar @shinebayar-g

**Comment by shinebayar-g** [comment]
Hi, issue is resolved on develop branch. event-stream package had malicious code and prior packages are removed from registry. ([Source](https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream))

I suggest you to try our docker images or clone manually for now.
