### ISSUE TITLE
SendGrid  not working any doc 

### ISSUE THREAD

**Issue by lalitnandandiwakar** [erxes/erxes#773]
SendGrid  not working any doc

**Comment by Mambatukaa** [comment]
Hey there,

This issue is outdated or there is a more recent duplicate.
Closing this issue to keep the Issues less cluttered.

We've moved our enhancement/feature requests to https://roadmap.erxes.io.
Please use this link in the future to submit your features.

Thank you.

**Comment by KhongorzulD** [comment]
Hi @Mambatukaa I would like to know the current status of this issue. If it is already found its solution I will close the issue.
