### ISSUE TITLE
Can't add Google Meet Integration - 400 redirect_uri requires native oauth client

### ISSUE THREAD

**Issue by gobengo** [erxes/erxes#786]
When I hit 'add' for the Google Meet Integration, I end up seeing a google error page:
```
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type. You can create a Client ID for native application at https://console.developers.google.com/apis/credentials/oaut
```

I have GMAIL_REDIRECT_URL set, and the gmail integration used it. 
Do I need to configure something more for the Google Meet integration?

**Comment by gobengo** [comment]
I needed to set GOOGLE_REDIRECT_URI to erxes/service/oauth/google_calendar_callback ([because this](https://github.com/erxes/erxes-api/blob/master/src/trackers/googleTracker.ts#L14))
and enable google calendar APIs.

**Comment by shinebayar-g** [comment]
Glad you sorted it out.
