### ISSUE TITLE
How to use script manager's install code?

### ISSUE THREAD

**Issue by shinebayar-g** [erxes/erxes#797]
Need to provide information how to use the script manager's install code. Ex: Put these code inside your body tag of html etc..
![image](https://user-images.githubusercontent.com/3091558/50767984-d1d29780-12b9-11e9-9cb9-4a5bedafeab8.png)

**Comment by batamar** [comment]
<img width="1094" alt="s1" src="https://user-images.githubusercontent.com/1748899/61356076-2a59a180-a8a8-11e9-9d8a-b567fcce3f87.png">
