### ISSUE TITLE
widgets not showing up on landing page after installing with docker 

### ISSUE THREAD

**Issue by andrew-oko-odion** [erxes/erxes#813]
The chat widget is not showing up on landing page all attempt to access it have 
proven abortive. please help....

**Comment by shinebayar-g** [comment]
Hello @andrew-oko-odion . Chat widget is not shown by default. You have to manually place it on your html code. Unfortunately these instructions are not documented anywhere, which is sucks I know..

I'll try to give you brief instruction.

First of all, you do clean install of erxes. Then you create admin account for yourself. Once you logged in, you'll see this screen.
![image](https://user-images.githubusercontent.com/3091558/52769369-0da40e00-306b-11e9-9f71-30ea19a92078.png)

Then you create your first brand (example: yourwebsite.com)
![image](https://user-images.githubusercontent.com/3091558/52769439-42b06080-306b-11e9-8529-4b88d5a8d605.png)

Then invite users (skip this for now)

Create your first messenger script (widget install code that you put on your website)
![image](https://user-images.githubusercontent.com/3091558/52769554-902ccd80-306b-11e9-9dbd-445e0aea7982.png)

Create your first channel (let's name it support for now). Select users who should've access to this channel, Select messenger etc.
![image](https://user-images.githubusercontent.com/3091558/52769600-b5b9d700-306b-11e9-8530-182fdc0395aa.png)

Once above steps are done. Go to **Settings** -> **App store** -> Click on **Messenger** (1) -> Dropdown list will show messengers. Click on **install code** button and copy code from pop up menu which looks like this

![image](https://user-images.githubusercontent.com/3091558/52769900-ac7d3a00-306c-11e9-903d-2c799ab5e0f4.png)

Copy this code in your website's html code's body. If that's not possible for you save this code somewhere as `example.html` file and open with browser. You'll see erxes widget.

```HTML
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>erxes widget test</title>
</head>

<body>
  <script>
    window.erxesSettings = {
      messenger: {
        brand_id: "Zldiw0",
      },
    };

    (function () {
      var script = document.createElement('script');
      script.src = "https://erxes.example.com/widgets/build/messengerWidget.bundle.js";
      script.async = true;
      var entry = document.getElementsByTagName('script')[0];
      entry.parentNode.insertBefore(script, entry);
    })();
  </script>
</body>

</html>
```

![image](https://user-images.githubusercontent.com/3091558/52770137-4644e700-306d-11e9-80d3-53c3eaacbb13.png)

![image](https://user-images.githubusercontent.com/3091558/52770147-4e9d2200-306d-11e9-8675-e3661e9dc7d2.png)

**Comment by andrew-oko-odion** [comment]
Big Thanks @shinebayar-g you just saved  me a whole lot. 
I own you a beer

**Comment by shinebayar-g** [comment]
Glad to hear that @andrew-oko-odion . But did it solve your issue?

**Comment by andrew-oko-odion** [comment]
> Glad to hear that @andrew-oko-odion . But did it solve your issue?

Yes it did
Thanks!
