### ISSUE TITLE
Add preview url on engage visitor auto message

### ISSUE THREAD

**Issue by khangaridb** [erxes/erxes#827]

**Comment by Mambatukaa** [comment]
Hey there, This is already done.
We've moved our enhancement/feature requests to https://roadmap.erxes.io
Please use this link in the future to submit your features.

Thank you.

**Comment by KhongorzulD** [comment]
As I see, there is no description on this issue so if possible @Mambatukaa please share with me the current status of this issue. If it is already found its solution back then i will close the issue.
