### ISSUE TITLE
iOS Safari login page scroll issue

### ISSUE THREAD

**Issue by alekseyp** [erxes/erxes#858]
Branch: latest develop
Browser: latest iOS Safari
Issue: Scroll doesn't work on login page

https://www.dropbox.com/s/2i2dc96oxum4bnk/RPReplay_Final1553790754.MP4?dl=0

**Comment by ganzorig** [comment]
@alekseyp thanks for opening an issue here. It's now fixed

**Comment by alekseyp** [comment]
@ganzorig thanks, i can confirm it's fixed.
I'll close it.
