### ISSUE TITLE
Add attachments to Contact/Company records

### ISSUE THREAD

**Issue by ruggerid** [erxes/erxes#879]
How can I add an attachment to a contact/company record?  For example, I want to add a proposal to a company record or a signed document to a contact.  I don't see that anywhere in your product.  So what I am looking for is a new property type called File.  We should be able to upload multiple files per contact/company - especially if we are hosting this app ourselves.

**Comment by mendorshikh** [comment]
@ruggerid Hello there, thanks for the message. This is the feature we are planning to make soon. We call it Proposal and are planning to make it Q4 2019.

**Comment by ruggerid** [comment]
ok cool...thx
    On Wednesday, April 10, 2019, 4:07:20 PM EDT, MJ <notifications@github.com> wrote:  
 
 
@ruggerid Hello there, thanks for the message. This is the feature we are planning to make soon. We call it Proposal and are planning to make it Q4 2019.

**Comment by indraganzorig** [comment]
This improvement is already possible by creating a custom property with a file type for the Companies:

![CleanShot 2021-09-13 at 18 32 47@2x](https://user-images.githubusercontent.com/53030705/133069035-d5923af5-bd66-4ba3-b802-81a842e7d9b0.png)

![CleanShot 2021-09-13 at 18 32 22@2x](https://user-images.githubusercontent.com/53030705/133069019-d999a09b-7b12-42f7-965d-7b277deb69a4.png)
