### ISSUE TITLE
missing user password

### ISSUE THREAD

**Issue by npracht** [erxes/erxes#894]
# Description
After creating an account online (free trial to setup because i couldn't make working docker until now), i want to complete my personal profile. When i save my edited profil, it is asking me about my password that has never been asked or send by email.

## How to reproduce
1. Create an account
2. Edit your profil
3. Save
4. See it asks for a password you don't have

# Suggestion
- Send a default password by email once the account if validated.
- Ask the user to choose his password when setting up his account.

**Comment by KhongorzulD** [comment]
Hi @Anu-Ujin if it possible please give me an update on this issue whether we have solved the issue or still working on it. Thank you
