### ISSUE TITLE
Save the lead data when converting to the task/deal/ticket show on customer detail & lead/task/ticket detail sidebar and show previous visit url

### ISSUE THREAD

**Issue by npracht** [erxes/erxes#895]
# Description
Today it is possible to assign a contact to a company when displaying the contact page or from the company page. That requires 2 actions:
1. Creating the contact
2. Viewing the contact and add the company to the contact.

# Suggestion
* For a better UX, it would be very comfortable to be able to assign the company to the contact directly on the contact creation page.
* Same on the company creation page, we could directly assign the contacts to it.

**Comment by Batchimegb** [comment]
@munkhsaikhan  Same: https://github.com/erxes/erxes/issues/633
