### ISSUE TITLE
automatic company creation

### ISSUE THREAD

**Issue by npracht** [erxes/erxes#896]
# Description
When you create a contact and submit its email address, you have the domain name which is kind of unique by company (even if a company can have several domain names).

# Suggestion
1. It would be very awesome (Hubspot does it and this is a fantastic UX) that when you create a contact, it automatically create a company with the domain name from the contact email address.
2. Then it could also automatically attach contacts to the company sharing the same domain name as the contact email address domain.

**Comment by indraganzorig** [comment]
Still looking for contributors for this
