### ISSUE TITLE
Cannot login on Linux with default admin credentials

### ISSUE THREAD

**Issue by andrew-oko-odion** [erxes/erxes#900]
![image](https://user-images.githubusercontent.com/4202928/56878548-8e5c8e80-6a4c-11e9-8c4d-205be2f426ac.png)

### MY setup throws no errors 
![image](https://user-images.githubusercontent.com/4202928/56878608-dd0a2880-6a4c-11e9-8bf1-e9585274045a.png)

**Comment by shinebayar-g** [comment]
Hi @andrew-oko-odion 400 bad request usually means there is version mismatch between your images.
Make sure your images are up to date with `docker-compose pull` and restart all containers. If problem still persists please write up how to reproduce the error

**Comment by andrew-oko-odion** [comment]
Thank you @shinebayar-g it worked. 
My be we should update the docker installation guide 
all I did was  update with `docker-compose pull` as you suggested 
Thanks again

**Comment by shinebayar-g** [comment]
Glad it worked. We've deployed our documentation website on https://docs.erxes.io and it's repository is https://github.com/erxes/docs.
