### ISSUE TITLE
Cannot create brands even as Admin -- Permission denied error 

### ISSUE THREAD

**Issue by andrew-oko-odion** [erxes/erxes#901]
![image](https://user-images.githubusercontent.com/4202928/56890197-b2ca6200-6a70-11e9-9746-3671f8302458.png)

**Comment by shinebayar-g** [comment]
I think there were database migration needed when we rewrite permission system. Run this command to check if it works for you.

`docker exec -it erxes-api yarn migrate up`

**Comment by andrew-oko-odion** [comment]
Big Thanks @shinebayar-g it worked..
