### ISSUE TITLE
erxes/erxes:docker-latest docker tag went away

### ISSUE THREAD

**Issue by gobengo** [erxes/erxes#902]
Some time ago I had installed erxes and was running based on the image 'erxes/erxes:docker-latest'.

I'm not sure exactly where I got that from, probably the "Use Erxes with Docker" wiki page. The last revision on Feb 11 by @shinebayar-g changed the docker tag.
https://github.com/erxes/erxes/wiki/Use-erxes-with-Docker/_compare/2e1f42ea304f835fce84081f628c6cf61d6f7c66...68f0c75296c04fcff35e5cc03a8c27c773f43b45

FWIW  this wiki page still mentions it. https://github.com/erxes/erxes/wiki/Running-behind-Nginx

Now there are only 'master-latest' and 'develop-latest'.
https://hub.docker.com/r/erxes/erxes/tags

In the future, will you please avoid deleting docker tags that are in the documentation? Deprecating them is understandable, but it's a bummer to remove them alltogether.

Might I recommend a docker tagging strategy that incorporates the erxes version numbers? I would love to be able to run `erxes/erxes:0`, `erxes/erxes:1`, `erxes/erxes:1.2`, `erxes/erxes:1.2.1` and opt-in to updates according to normal semver.
The ['node'](https://hub.docker.com/_/node/) image does a good job of this and can serve as inspiration.

You may even want to republish the 'docker-latest' tag to the hub for now in case this has affected other people and they just haven't reported it yet.

**Comment by shinebayar-g** [comment]
Hi @gobengo , I totally understand your point and sorry for the inconvenience. Indeed our docker tags should be symantic like our repository does. Currently It's hard to track down which image is generated on which commit which is sucks ofc.. Thank you for the suggestion and we'll work on our tags. 🕵

**Comment by jalberto** [comment]
this is a very important requirement to be able to use docker properly

**Comment by karser** [comment]
Indeed, using semver (e.g `erxes/erxes:v0.9.15`) would be awesome!

**Comment by gobengo** [comment]
@shinebayar-g hmm. I've had something deployed against 'develop-latest' since I created this ticket. I just restarted it in a way that caused the latest to be fetched, but now my previous configuration doesn't work and there are mongodb errors (e.g. `erxes-widgets-api-7c5b7bd95b-t9jgx erxes-widgets-api [ioredis] Unhandled error event: RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN.`).

I can fix it, and am not particularly surprised since I'm running on such a loose tag.

What I want to check in on: Is there any plan to publish more stable (semver) docker tags to the erxes/erxes hub.docker.com images?

If not, I will rehost them under my own name and fork.

**Comment by shinebayar-g** [comment]
Hi @gobengo . I've updated drone-ci config file in this [commit](https://github.com/erxes/erxes/commit/ccc73385b8cc3cd91518c90d9efe2dd5d976d0a4) to prepare for semver docker tag releases. We're going to release new version this weekend with detailed changelog. From then on you can use semver releases. :sweat_smile:

**Comment by gobengo** [comment]
@shinebayar-g Awesome! I see some semver tags in here now: https://hub.docker.com/r/erxes/erxes/tags

Thanks!
