### ISSUE TITLE
Issues running erxes with docker

### ISSUE THREAD

**Issue by leonhatori** [erxes/erxes#963]
I am having the following error when running "**docker-compose up -d**". 
Can anyone help me? Thanks!

leonhatori@leonhatori:~/Desktop/erxes$ docker-compose up -d
redis is up-to-date
Starting erxes ... 
erxes-widgets is up-to-date
Starting mongo ... error

Starting erxes ... error
032bafe5058fc3e633065898f42): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use

ERROR: for erxes  Cannot start service erxes: driver failed programming external connectivity on endpoint erxes (4c44cd4c53e611c24e58e7a9ddcfa653268be05429a8f10c344eee677828976e): Error starting userland proxy: listen tcp 0.0.0.0:3000: bind: address already in use

ERROR: for mongo  Cannot start service mongo: driver failed programming external connectivity on endpoint mongo (37c326b7db7af88959391a4fe104ec5c6a7d7032bafe5058fc3e633065898f42): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use

ERROR: for erxes  Cannot start service erxes: driver failed programming external connectivity on endpoint erxes (4c44cd4c53e611c24e58e7a9ddcfa653268be05429a8f10c344eee677828976e): Error starting userland proxy: listen tcp 0.0.0.0:3000: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by shinebayar-g** [comment]
Hello @leonhatori . 
> listen tcp 0.0.0.0:3000: bind: address already in use
> listen tcp 0.0.0.0:27017: bind: address already in use

Looks like you're already running MongoDB on your server (27017 port) and another program is running on your 3000 port.

You can solve this issue by changing overlapping ports to another unused port.
for example, change erxes port to something like `3001:80` and MongoDB port to `27018:27017`
